### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by L1cardo** [ripperhe/Bob#1]
这个是很棒的软件！！！ 真的超级好用！！
首先很感谢开发了这么好的软件，并且是开源的（上架 app store 都能赚好多钱）
 
1. 状态来左键显示翻译界面，右键显示设置菜单（有时可能会忘记快捷键，可以快速在状态栏进行翻译）
2. 如果点击了朗读，界面消失后应该停止朗读
3. 截图翻译的时候，鼠标右键应该退出截图
4. 建议提供可以设置自己翻译 api 的选项（默认和自己的之间可以切换，这样就少了一些安全性问题，虽然现在也没有）
5. ui 的完善（虽然很好了，但是可以更好看，更舒服）
5. 软件名字和 logo 可以换一下。。。。（说实话emmm，不太好看）

以上的建议，如果是 swift 的话我可以帮忙的，但是 oc 语言啥都不会，只能辛苦一下作者了

加油！祝这个软件越来越好！！！

**Comment by ripperhe** [comment]
@L1cardo 

感谢肯定 🤝
1. 第一点我没看太明白，如果忘记的话，是不是可以点击 status item 那个图标然后看一下?
![image](https://user-images.githubusercontent.com/13943595/71323206-838ac880-250b-11ea-9204-b2d6c8f9de81.png)
2.朗读这个确实应该关掉，我下个版本加上
3.截图这个我设置了按 esc 退出，我下次把鼠标右键也加上
4.自己翻译的 api 指的是接入（百度翻译、有道翻译等）官方的 SDK 吗？如果有需求的话，后期也可以考虑加上
5. UI 这个后期你也可以帮忙设计设计 😍
6. 软件名字和 logo 这个可能不太符合大家的审美，这个我再考虑考虑

还有就是我其实也想用 Swift 写，不过工作都是用的 OC，对 Swift 不太熟悉，后期如果有余力的话，可以考虑用 Swift 重写一遍，到时候就可以找你帮忙了，希望能继续关注 😃

**Comment by L1cardo** [comment]
第一个就是
左键：
![image](https://user-images.githubusercontent.com/33802186/71323342-05c7bc80-250d-11ea-849c-2e2621df3e8a.png)
右键：
![image](https://user-images.githubusercontent.com/33802186/71323343-0ceeca80-250d-11ea-9c64-4b0d662cf8b6.png)

**Comment by L1cardo** [comment]
短期内 swift 重写一遍不现实，你肯定也有工作。
但是非常期待 swift 版本，我相信会有这么一天的！！！

**Comment by ripperhe** [comment]
行，我明白了，我考虑下，我觉得左右键这个挺方便的

**Comment by L1cardo** [comment]
还有一个，这个界面能做成实时监测的吗？  不用按 enter， 实时翻译
![image](https://user-images.githubusercontent.com/33802186/71323445-30664500-250e-11ea-9bbd-9eccb3c4c831.png)

**Comment by ripperhe** [comment]
确实，短期内不会重写了，毕竟还有好多个要改的点，而且暗黑模式还没适配，要是你会 OC 就好了 😭，最近搞这个真心有点累，第一次写 Mac，遇到不少坑

**Comment by L1cardo** [comment]
> 确实，短期内不会重写了，毕竟还有好多个要改的点，而且暗黑模式还没适配，要是你会 OC 就好了 😭，最近搞这个真心有点累，第一次写 Mac，遇到不少坑

哈哈，加油啦！！！  肯定还会有很多小伙伴会帮助的！！

**Comment by ripperhe** [comment]
这个实时监听我也考虑过，不过我发现要是调用过于频繁，网站会封一会儿 IP，过一阵又好了，所以采取了 enter

**Comment by L1cardo** [comment]
> 这个实时监听我也考虑过，不过我发现要是调用过于频繁，网站会封一会儿 IP，过一阵又好了，所以采取了 enter

嗯嗯 好的，希望越做越好！！  这个 app 是我今天最大的收获！！

**Comment by ripperhe** [comment]
好滴，谢谢啦，这软件对你有用我也很开心！！！

**Comment by Turo233** [comment]
软件非常Nice！！
我觉得logo和名字像现在这么个性完全没问题;
建议界面可以更『苹果』一点，目前用的时候略微有些违和，如果能像原生的翻译UI一样就完美了，哈哈;
总之，非常Nice！

**Comment by ripperhe** [comment]
@L1cardo 
Licardo，我适配暗黑模式了，然后快捷键改为了技术符号表示，截图模式可以右键退出了，加了圆角，关闭翻译视图可以停止朗读了。。。
@Turo233 
你可以感受一下新版UI是不是要「苹果」一点儿了。。。

**Comment by crper** [comment]
@ripperhe 也可以参考 chrome 扩展 saladict , 这个扩展在 chrome 端用起来很舒服和完善。

https://github.com/crimx/ext-saladict

大佬，可以看看优秀的地方，在客户端也实现一波。

**Comment by AY-afkafk** [comment]
有个小建议，能不能设计一个简约一点的logo。。这个logo显示在上面有点吓人🤣🤣🤣

**Comment by ripperhe** [comment]
@crper 好滴，回头好好研究一下

**Comment by ripperhe** [comment]
@AY-afkafk 😂 行，我看看怎么把 logo 弄得不这么吓人

**Comment by AY-afkafk** [comment]
> @AY-afkafk 😂 行，我看看怎么把 logo 弄得不这么吓人

哈哈哈哈哈也可以给用户设置的机会，我看到上面也有人喜欢这个有个性的logo哈哈哈哈哈

**Comment by ripperhe** [comment]
> > @AY-afkafk 😂 行，我看看怎么把 logo 弄得不这么吓人
> 
> 哈哈哈哈哈也可以给用户设置的机会，我看到上面也有人喜欢这个有个性的logo哈哈哈哈哈

👌没问题
