### ISSUE TITLE
OCR 接口使用是否有限制?

### ISSUE THREAD

**Issue by izuolan** [ripperhe/Bob#10]
作者好, 有道的 OCR 接口是否有限制次数? 如果使用人多了是不是要收费? 或者给一个配置选项用户填 OCR 接口私钥?

**Comment by ripperhe** [comment]
暂时没有限制，用的网页接口，所以也暂时不会收费，但是存在失效风险，所以后期准备在现有基础上加上可配置自己的翻译接口和 OCR 接口私钥的功能
