### ISSUE TITLE
腾讯优图通用OCR，验证失败，请求异常

### ISSUE THREAD

**Issue by chavyleung** [ripperhe/Bob#102]
## 运行环境
* Device: MacBook Pro (15-inch, 2018)
* macOS: 11.0 Beta版(20A5395g)
* Bob Version: 0.5.2

## 描述问题
腾讯优图通用OCR
验证时提示：验证失败，请求异常

抓包数据: 
https://api.youtu.qq.com/youtu/ocrapi/generalocr
```html
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty/1.9.15.1</center>
</body>
</html>

```

**Comment by ripperhe** [comment]
@chavyleung 目前确实有问题，还没有修复

**Comment by chavyleung** [comment]
ok, 我在用其他的服务, 这个我只是随手试试的时候发现的, 不急

**Comment by ripperhe** [comment]
腾讯优图官方马上下线了，用其他服务吧。我把这个 BUG 熬死了。😅
