### ISSUE TITLE
macOS big sur 11.0.1 beta1 闪退

### ISSUE THREAD

**Issue by jfdnet** [ripperhe/Bob#103]
## 运行环境
* Device: MacBook air 2020
* macOS: 11.0.1 beta1
* Bob Version: 0.5.2

## 描述问题
快捷键启动bob 不管是输入，截图，还是划词。
都有一定概率导致bob闪退。

**Comment by ripperhe** [comment]
这应该是兼容性问题，我工作的主力机不方便升级 macOS 11，只能等正式版出了再处理下，抱歉了。

**Comment by vito-karboncard** [comment]
> 这应该是兼容性问题，我工作的主力机不方便升级 macOS 11，只能等正式版出了再处理下，抱歉了。

正式版来啦
