### ISSUE TITLE
图文识别使用的哪个平台的呢？

### ISSUE THREAD

**Issue by CloseServer** [ripperhe/Bob#104]
你好，如题，用的是有道的还是百度的图片转文字呢？

谷歌支持图文识别吗？官方文档好像没有。

**Comment by ripperhe** [comment]
https://ripperhe.gitee.io/bob/#/general/quickstart/service

这里有写的哈，0.5.0 默认使用的是百度 OCR，你可以自行配置其他平台的。

**Comment by CloseServer** [comment]
@ripperhe   0.4.0 使用的是哪个OCR 平台呢？

**Comment by ripperhe** [comment]
@CloseServer 使用的有道
