### ISSUE TITLE
Apple语音合成无法使用

### ISSUE THREAD

**Issue by NoelZong** [ripperhe/Bob#105]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, 2016)
* macOS: 10.14.6
* Bob Version: 0.5.2

## 描述问题

无法使用默认的Apple语音合成，点击任意小喇叭时弹出红色叉号提示“不支持该语言”。尝试过中文英文均未果，brew和压缩包重装还是无法解决问题。使用腾讯云语音合成可以正确合成语音。

**Comment by ripperhe** [comment]
好的，了解了。

**Comment by ripperhe** [comment]
@NoelZong 0.5.3 版本修复了这个问题

**Comment by zhaosiye** [comment]
运行环境：
Device：Intel NUC 黑苹果
macOS：10.14.6
Bob Version：0.5.4

问题同上，依然是无法使用默认的Apple语音合成。
