### ISSUE TITLE
能否加一个划词自动翻译的功能

### ISSUE THREAD

**Issue by huhan-123** [ripperhe/Bob#107]
能否添加一个化词自动翻译（不需要按快捷键）这样的功能

**Comment by cjahv** [comment]
可以使用 popclip插件
https://ripperhe.gitee.io/bob/#/general/integration/popclip

**Comment by huhan-123** [comment]
好的，非常感谢

**Comment by cjahv** [comment]
不客气，如果解决了可以关闭这个issues

**Comment by huhan-123** [comment]
虽然还不能达到选中自动翻译的功能（需要点击插件图标），但是也能接受了，谢谢
