### ISSUE TITLE
翻译使用谷歌翻译及谷歌cn翻译，提示获取TKK失败

### ISSUE THREAD

**Issue by warriorBrian** [ripperhe/Bob#108]
## 运行环境
* Device: MacBook Pro (16-inch, 2019)
* macOS: 10.15.7
* Bob Version: 0.4.0
## 描述问题

**如下图，提示获取tkk失败，谷歌cn翻译及谷歌翻译**

![image](https://user-images.githubusercontent.com/28696399/98074391-5508a880-1ea5-11eb-8d68-db25a4307112.png)

**Comment by chuckbyron** [comment]
me too

**Comment by ripperhe** [comment]
请使用 0.5.0 版本

**Comment by warriorBrian** [comment]
@ripperhe 0.4.0没有办法解决这个问题么，0.5.0的翻译界面不太喜欢，想保持使用0.4.0版本的界面。

**Comment by ripperhe** [comment]
@warriorBrian 

0.5.x UI 应该还会有调整，哪怕最终觉得 0.5.x 的 UI 不 OK，最终改成了一个更像 0.4.0 的 UI，那个版本本质上也是从 0.5.x 的代码接着改的结果。

0.4.0 就是老版本，这边不会再根据 0.4.0 的代码去单独维护一条 0.4.x 的线，BUG 也不会再解决了。希望理解 🤝
