### ISSUE TITLE
翻译结果太少

### ISSUE THREAD

**Issue by weichengwu** [ripperhe/Bob#110]
## 运行环境
* Device: Mac mini
* macOS: Catalina 10.15.7
* Bob Version: 0.5.2

## 描述问题

翻译结果太少，一个英文单词只会返回一个中文释义，完全没有动名词说明、音标、同义词等等，请问这是 API 的原因还是软件的原因？用的是彩云 API。

![image](https://user-images.githubusercontent.com/17878528/98344646-7eb10380-204e-11eb-9f9f-cd8decf569aa.png)

**Comment by ripperhe** [comment]
@weichengwu 
因为 API 接口只提供了这些数据，你可以考虑使用有道和搜狗的服务，会有更多释义。
