### ISSUE TITLE
为什么现在不能用谷歌翻译

### ISSUE THREAD

**Issue by aslibdnw** [ripperhe/Bob#111]
为什么变成了百度翻译？

**Comment by ripperhe** [comment]
@aslibdnw 
可以去偏好设置添加哈，需要自己的秘钥，详细使用方法见：
https://ripperhe.gitee.io/bob/#/general/quickstart/service

当然，你也可以考虑使用谷歌翻译插件：
https://github.com/roojay520/bobplugin-google-translate
