### ISSUE TITLE
翻译时翻译窗口抖动很严重🙏

### ISSUE THREAD

**Issue by naturs** [ripperhe/Bob#114]
## 运行环境
* Device: MacBook Pro 
* macOS: 10.13.6
* Bob Version: 0.5.2

## 描述问题
翻译时翻译窗口抖动很严重

![small-clip.gif](https://i.loli.net/2020/11/10/PxCFSXYnUDoEBrH.gif)

**Comment by ripperhe** [comment]
抱歉了，10.13 系统确实没适配好，有好几个用户反馈会抖动了，不太好解决。
有没有可能升级系统？😅
后期如果有经历，我看下是否需要做一个无动画的开关，看看能不能一定程度上解决这个问题。

**Comment by naturs** [comment]
> 抱歉了，10.13 系统确实没适配好，有好几个用户反馈会抖动了，不太好解决。
> 有没有可能升级系统？😅
> 后期如果有经历，我看下是否需要做一个无动画的开关，看看能不能一定程度上解决这个问题。

好的，谢谢
