### ISSUE TITLE
万人血书   增加 生词导入到单词本(扇贝,有道)的功能!

### ISSUE THREAD

**Issue by jackey-jiang** [ripperhe/Bob#115]
不可多得的神仙app!!! 希望大佬 加入该功能,这样就可以毫无障碍的把生词同步到扇贝或者有道了,
目前是用了其它chrome扩展,麻烦不说,体验极差,很不连贯
希望大佬们能听到无产阶级的声音

**Comment by ripperhe** [comment]
感谢支持 🤝🤝🤝

最近真的太忙了，收藏等功能后面会加上的

**Comment by VaguelyCloud** [comment]
神仙app，如果可以我愿出一分力！

**Comment by yuhaowin** [comment]
我也需要这个功能，无奈尝试写了个[小插件](https://github.com/yuhaowin/youdao-wordbook-bob-plugin)，不做翻译，只是把单词同步到单词本中。

另外，想请问一下可以在 Bob 中获取到接口的 cookie 么？ @ripperhe

**Comment by ripperhe** [comment]
@yuhaowin 暂时还不支持，如果后续支持了通知你

**Comment by yuhaowin** [comment]
谢谢，再次感谢你的回复。

**Comment by Jackjun724** [comment]
> 我也需要这个功能，无奈尝试写了个[小插件](https://github.com/yuhaowin/youdao-wordbook-bob-plugin)，不做翻译，只是把单词同步到单词本中。
> 
> 另外，想请问一下可以在 Bob 中获取到接口的 cookie 么？ @ripperhe

 [欧陆词典版的] (https://github.com/Jackjun724/eudic-plugin) ，在有道的源码上直接修改的

**Comment by yuhaowin** [comment]
> > 我也需要这个功能，无奈尝试写了个[小插件](https://github.com/yuhaowin/youdao-wordbook-bob-plugin)，不做翻译，只是把单词同步到单词本中。
> > 另外，想请问一下可以在 Bob 中获取到接口的 cookie 么？ @ripperhe
> 
> [欧陆词典版的] (https://github.com/Jackjun724/eudic-plugin) ，在有道的源码上直接修改的

我试了一下没有添加成功，有道广告很多，我已经弃用了，购买了欧路永久版，实际上欧路有开放 api。

**Comment by youxiaohanpian** [comment]
欧陆词典也请考虑一下~~！谢谢~
