### ISSUE TITLE
复制或截图长文本时有道翻译显示接口错误：翻译失败，错误码103

### ISSUE THREAD

**Issue by 520Cunha** [ripperhe/Bob#116]
## 运行环境
* Device: MacBook Pro (13-inch, 2016)
* macOS: 10.12.6
* Bob Version: 0.4.0

## 描述问题
复制或截图长文本时有道翻译显示接口错误：翻译失败，错误码103
![image](https://user-images.githubusercontent.com/74303360/98813136-ae9d4400-245e-11eb-8043-dcfea33fe140.png)

**Comment by ripperhe** [comment]
你好，请使用安装最新版 https://ripperhe.gitee.io/bob/#/
