### ISSUE TITLE
划词翻译后 bob窗口经常会立刻消失

### ISSUE THREAD

**Issue by Raychanan** [ripperhe/Bob#117]
## 运行环境
* Device: MacBook Pro (15-inch, 2016)
* macOS: 11.0.1 (20B29)
* Bob Version: 0.5.2

## 描述问题
今天刚从macOS10升级到11。问题：Bob会经常崩溃。

**Comment by Raychanan** [comment]
无法截图，就是闪退。

**Comment by cjahv** [comment]
我和你用的相同的版本，没有遇到你所说的问题

**Comment by mitoop** [comment]
macOS: 11.0.1 (20B29)
MacBook Pro (15-inch, 2017) / MacBook Pro (15-inch, 2016)
Bob Version: 0.5.2

划词翻译后 bob窗口经常会立刻消失 每次要点几次

**Comment by ripperhe** [comment]
@mitoop @Raychanan 好的，周末解决

**Comment by ccnana** [comment]
确实经常刚出结果就消失了。

**Comment by mitoop** [comment]
@ripperhe 非常感谢🙏

**Comment by ripperhe** [comment]
@Raychanan @mitoop @ccnana 已在 0.5.3 版本修复了这个问题
