### ISSUE TITLE
Big Sur 多显示器下, 非激活显示器任务栏图标变形

### ISSUE THREAD

**Issue by smallCC** [ripperhe/Bob#118]
## 运行环境
* Device:  MacBook Pro (13-inch, 2018)
* macOS: 11.0.1
* Bob Version: 0.5.2
* Other: 外接显示器

## 描述问题
Big Sur 多显示器下, 非激活显示器任务栏图标变形.
如图, 光标所在的显示器, 下正常. 另一显示器则任务栏图标变形.
<img width="270" alt="bob_icon1" src="https://user-images.githubusercontent.com/5841912/99243560-d401c780-283b-11eb-9525-4ff1a8a4c596.png">
<img width="438" alt="bob_icon2" src="https://user-images.githubusercontent.com/5841912/99243590-d9f7a880-283b-11eb-9366-7d8cfdede215.png">

**Comment by ripperhe** [comment]
方便 QQ（453942056） 联系我么？ 我周末尝试解决下，麻烦你帮忙测试下

**Comment by smallCC** [comment]
> 方便 QQ（453942056） 联系我么？ 我周末尝试解决下，麻烦你帮忙测试下

不好意思, 周末出去了一趟. 已经发起好友请求, 咱们重新约一下时间吧

**Comment by ripperhe** [comment]
已在 0.5.3 修复了这个问题
