### ISSUE TITLE
osx 10.12.6 版本使用0.2版本bob,电脑没有开启暗黑模式,但是bob一直是暗黑模式

### ISSUE THREAD

**Issue by lovepeacee** [ripperhe/Bob#12]
osx 10.12.6 版本使用0.2版本bob,电脑没有开启暗黑模式,但是bob一直是暗黑模式

**Comment by lovepeacee** [comment]
挺好好用的,加油🆙

**Comment by ripperhe** [comment]
感谢支持！😘
这个问题在看了，不出意外下个版本修复

**Comment by ripperhe** [comment]
[0.3.0](https://github.com/ripperhe/Bob/releases/tag/v0.3.0) 版本应该已经修复了该问题，你可以验证一下
