### ISSUE TITLE
AppleScript 调用方式优化

### ISSUE THREAD

**Issue by atian25** [ripperhe/Bob#120]
现在提供的脚本，只能用于唤醒 bob。
我这边在开发个 Alfred 插件来调用 bob，希望 AppleScript 能支持后台运行并返回一段字符串

**Comment by ripperhe** [comment]
其实 Bob 也是调用的 API，感觉如果你要调用 API，是不是可以直接集成接口？

**Comment by atian25** [comment]
那也是可以的，不过看到 bob 集成了插件流程，就刚发现 bob 很不错，想看看融合 Alfred 玩玩。之前有实现过直接调用网易 API。

**Comment by Teraflopst** [comment]
我自己写过一个 Alfred workflow，使用的是腾讯的机械翻译 API，然后和 PopClip 一起使用实现划词翻译，返回的翻译字符串就简单地用 AppleScript 弹出一个系统弹窗这样显示。

![ezgif com-gif-maker](https://user-images.githubusercontent.com/3352695/100552811-65554d00-32c4-11eb-96bc-e79c54b5cbd9.gif)
