### ISSUE TITLE
能否把翻译的 含义 名词动词显示出来

### ISSUE THREAD

**Issue by qs-lll** [ripperhe/Bob#121]
![image](https://user-images.githubusercontent.com/5264241/100539259-4b8a1a80-3270-11eb-9d62-5eacf6bd9f86.png)
这个是idea的插件 能不能像这样把完整的意思 显示出来

**Comment by ripperhe** [comment]
@qs-lll 有道翻译和搜狗翻译会有，其他的接口没有提供。
