### ISSUE TITLE
Apple语音合成更新0.5.3之后仍无法使用

### ISSUE THREAD

**Issue by NoelZong** [ripperhe/Bob#122]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, 2016)
* macOS: 10.14.6
* Bob Version: 0.5.3

## 描述问题

更新了0.5.3，使用AppCleaner删除所有bob相关文件，重启电脑下载0.5.3新包安装使用apple语音合成还是提示不支持朗读当前语种，纯中文英文都试了。腾讯云语音正常。

**Comment by ripperhe** [comment]
加我 QQ 453942056，发我日志

**Comment by ripperhe** [comment]
目前发现两位 **macOS 10.14.6** 系统的用户升级 **Bob 0.5.3** 后仍无法使用 Apple 语言合成，经日志排查判断是系统 API 的问题，目前无解

**Comment by ripperhe** [comment]
无法使用 Apple 语音合成的用户请升级 macOS 10.15 以上的系统
