### ISSUE TITLE
常用几个接口都炸了。。。。

### ISSUE THREAD

**Issue by zz5678** [ripperhe/Bob#124]
## 运行环境
* macOS: 10.15.7
* Bob Version: 0.5.3

## 描述问题
1，内置百度OCR经常出问题，提示是免费的服务不稳定
2，腾讯优图OCR申请成功了一直用不了，发现问题在这里 https://github.com/ripperhe/Bob/issues/102
![image](https://user-images.githubusercontent.com/67672527/100874656-dde42580-34df-11eb-85d3-32aef3328ab7.png)
3，彩云申请了快一周了，一直不给通过，用 bob 内置的就如上经常掉链子
![image](https://user-images.githubusercontent.com/67672527/100874887-31ef0a00-34e0-11eb-81d0-09922acdebe9.png)
4，google.cn 的插件。。。作者就在我写这个 issue 前后改好了 :grin::grin:
https://github.com/roojay520/bobplugin-google-translate/issues/6

**Comment by ripperhe** [comment]
@zz5678 
1. 内置的百度 OCR 为什么不行，报错信息里面已经描述得很明确了，需要你自己申请自己的秘钥
2. 腾讯优图有问题我在软件里面也标了，这个问题还没有修复；但是除了腾讯优图的其他的只要自己申请了秘钥应该都没问题（百度OCR、腾讯云OCR、有道OCR、搜狗OCR），软件里面应该提示了可能无法使用，以及提示用其他的服务了吧 😂
![image](https://user-images.githubusercontent.com/13943595/100875909-9e1e3d80-34e1-11eb-8aa7-b90d950d191b.png)
3. 彩云翻译不给通过我也没招，这是彩云的问题，你应该尝试联系他们，或者换个账号试试。。。但是，你可以申请百度翻译、腾讯翻译、有道翻译、搜狗翻译、谷歌翻译。。。。
4. Google 插件不行是因为谷歌改了，这个就是等插件作者更新了。这个问题不是 Bob 造成的。

所以，「常用几个接口都炸了。。。。」是不是显得有点夸张了？

**Comment by zz5678** [comment]
不算夸张，这是给各位用户汇总贴，看到这个就不用单独提问了

**Comment by ripperhe** [comment]
@zz5678  NB 👍

**Comment by ripperhe** [comment]
@D0ngsec 重复提交了 5 次应该是你在输入框输入了 5 次。如果这么明显，没法自测通过的。
