### ISSUE TITLE
谷歌翻译出问题了

### ISSUE THREAD

**Issue by AriaLyy** [ripperhe/Bob#126]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, Mid 2018)
* macOS: 10.15.3
* Bob Version: 0.5.2

## 描述问题
我使用的是谷歌api接口，从英语翻译为法语时，出现了以下问题。`'`都变成了`&#39`

![image](https://user-images.githubusercontent.com/10437293/101317548-a687c700-3899-11eb-956e-9d5a4038d83b.png)

这个是谷歌翻译的
![image](https://user-images.githubusercontent.com/10437293/101317726-07af9a80-389a-11eb-9cb1-7631e82621d4.png)

**Comment by ripperhe** [comment]
@AriaLyy 好的，了解了。下个版本修复。

**Comment by ripperhe** [comment]
0.5.4 版本已解决这个问题
