### ISSUE TITLE
Bob设置开机启动，但仍无法自启动

### ISSUE THREAD

**Issue by char1eslu** [ripperhe/Bob#127]
## 运行环境
* Device: MacBook Pro (15-inch, 2017)
* macOS: 11.0.1
* Bob Version: 0.5.3

## 描述问题
已设置自启动，但仍无法自启动
<img width="668" alt="image" src="https://user-images.githubusercontent.com/20885743/101596184-9bff3600-3a2f-11eb-9959-1e6de4385a68.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/20885743/101596201-a3264400-3a2f-11eb-93e2-8da54d0a53e8.png">
后在~/Library/LaunchAgents中设置plsit也不得行，BetterTouchTool等软件按照此方法配置可正常启动
<img width="645" alt="image" src="https://user-images.githubusercontent.com/20885743/101596373-e680b280-3a2f-11eb-9f56-92137177d89b.png">

**Comment by shibing624** [comment]
同这个问题，好像还没解决？mac 版本 11.5.2， bob版本：0.6.1

**Comment by WantD998** [comment]
同样存在这个问题 

1. Device: MacBook Pro (Retina, 15-inch, Mid 2014)
2. macOS: 10.13.6
3. Bob Version: 0.6.1

**Comment by ripperhe** [comment]
额，那把 Bob 添加到「系统偏好设置」-「用户与群组」-「登陆项」里面吧，这样应该能好使

**Comment by tw93** [comment]
@ripperhe 添加到登录项也不行
