### ISSUE TITLE
是时候加上备份功能了

### ISSUE THREAD

**Issue by zz5678** [ripperhe/Bob#128]
嗯，成功的软件都要有哦！
哈，现在一大堆申请的私有服务接口，安装的插件，这要升级或者换电脑，重装机，都需要备份啊。

另外，发现 brew cask 里早年安装了个非常古老版本
```
bob (0.4.0) != 0.5.3
```
但现在用的是从 github 直接下载安装的 0.5.3，brew 里这老家伙还不敢随便删，因为没备份，怕 brew 一锅端都给卸载了。问下是brew删，是否安全？

**Comment by ripperhe** [comment]
0.7.0 版本加了偏好设置导入导出的功能，应该可以用这个备份。
