### ISSUE TITLE
弹出窗口的位置

### ISSUE THREAD

**Issue by xtuer** [ripperhe/Bob#13]
很喜欢 Bob，希望能够提供一个选项，定义 Bob 的弹出窗口在固定位置，而不是像目前这样在鼠标附近弹出。

在固定位置弹出可以减少大脑的反应时间。

**Comment by ripperhe** [comment]
恩，合理的需求，我们考虑一下

**Comment by ripperhe** [comment]
0.5.2 版本可以选择固定位置
