### ISSUE TITLE
功能请求：支持微信翻译

### ISSUE THREAD

**Issue by simonla** [ripperhe/Bob#130]
不同于腾讯云的翻译，微信自己还有一套翻译API，效果很好，目前是免费服务的状态，希望能在bob里支持

需要在[微信开放平台](https://open.weixin.qq.com/)注册，获得appId和appSecret，然后通过[该接口](https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_access_token.html)获取accessToken，就可以使用API了，流程上不是特别复杂

[微信翻译文档介绍](https://developers.weixin.qq.com/doc/offiaccount/Intelligent_Interface/AI_Open_API.html)

**Comment by ripperhe** [comment]
@simonla 是否有尝试过对比微信翻译和腾讯云翻译结果？会不会本质上就是对腾讯云的二次包装？

**Comment by simonla** [comment]
不是二次包装，附上对比测试结果

```
input: Bob is a macOS translation application for text and pictures and manual input.

==========GoogleNMTTranslateAPI==========
Bob是用于文本和图片以及手动输入的macOS翻译应用程序。
==========GoogleNMTTranslateAPI==========

==========GooglePBMTTranslateAPI==========
Bob是用于文本和图片以及手动输入的macOS翻译应用程序。
==========GooglePBMTTranslateAPI==========

==========TencentCloudTranslateAPI==========
Bob是用于文本和图片以及手动输入的MacOS翻译应用程序。
==========TencentCloudTranslateAPI==========

==========BaiduTranslateAPI==========
Bob是一个用于文本和图片以及手动输入的macOS翻译应用程序。
==========BaiduTranslateAPI==========

==========WeChatTranslateAPI==========
Bob是一个macOS翻译应用，用于文本和图片以及手动输入。
==========WeChatTranslateAPI==========
```

**Comment by ripperhe** [comment]
@simonla 
好的，了解了，看起来还不错，我尝试一下。

**Comment by ripperhe** [comment]
@simonla 上次调研过了，忘了回你。
接入确实不难，但是申请不好申请，想必这个会难倒大部分用户。
