### ISSUE TITLE
没有开启固定按钮，失焦时依然不消失

### ISSUE THREAD

**Issue by ztwqy6688o** [ripperhe/Bob#131]
## 运行环境
* Device:  mac mini (2018)
* macOS: 11.1
* Bob Version: 0.5.3

## 描述问题
没有开启固定按钮，失焦时依然不消失
![image](https://user-images.githubusercontent.com/22748358/102456687-85cf2680-407c-11eb-95e1-78a8fc92302f.png)

**Comment by ripperhe** [comment]
@ztwqy6688o 
麻烦加我 QQ 453942056，复现几次这个问题，然后导出日志发我

**Comment by ripperhe** [comment]
@ztwqy6688o 

0.5.4 已解决这个问题
