### ISSUE TITLE
功能建议 添加翻译界面交换语言快捷键

### ISSUE THREAD

**Issue by cjahv** [ripperhe/Bob#133]
![image](https://user-images.githubusercontent.com/15372793/103077686-33a57c80-460b-11eb-8f95-842abdcc2801.png)

截图中标注的按钮快捷键 ，例如按下tab或者自定义快捷键，交换语言再翻译

**Comment by ripperhe** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/13943595/200326032-0e916059-82db-4eb6-9fc6-fcc801f07052.png">
建议两侧选中「自动检测」+「自动选择」，识别到中文会自动翻译为英文，识别到英文会自动翻译成中文
