### ISSUE TITLE
彩云小译用的明文HTTP API 传输？？？

### ISSUE THREAD

**Issue by zz5678** [ripperhe/Bob#134]
```
http://api.interpreter.caiyunai.com/v1/translator
```
惊讶了，抓 http，没想到抓到了bob 

不是我弄错了吧？这事儿还是让用户都知道的好些，明晃晃的明文把用户翻译的内容在网上传输 …… 
如果彩云小译只提供 http 接口，是不是需要警示一下用户，或者干脆就切割了吧，这样真不太好

![image](https://user-images.githubusercontent.com/67672527/103101985-fd8cea80-4654-11eb-990a-493250096d98.png)

**Comment by ripperhe** [comment]
彩云的 API ([文档链接](https://open.caiyunapp.com/%E4%BA%94%E5%88%86%E9%92%9F%E5%AD%A6%E4%BC%9A%E5%BD%A9%E4%BA%91%E5%B0%8F%E8%AF%91_API)) 确实是 HTTP + 明文秘钥，我开发的时候也感到挺诧异。

不过我对安全了解不多，没考虑到会对用户有什么明显的直接的坏处，所以没有做明确的提示。

麻烦科普下，如果可以的话，希望能举例说明下，谢谢。如有必要，我会贴到申请秘钥的文档上的。

**Comment by zenof** [comment]
@ripperhe  [https://api.interpreter.caiyunai.com/](https://api.interpreter.caiyunai.com/) 这个域名是配置了 SSL 的，建议在代码里直接用 https 协议

**Comment by ripperhe** [comment]
@zenof 感谢提醒。已修改，下个版本跟上。

**Comment by ripperhe** [comment]
0.5.4 版本已改为 https 协议
