### ISSUE TITLE
能否将OCR功能单独剥离出来

### ISSUE THREAD

**Issue by haoshaoyang** [ripperhe/Bob#136]
现在这个功能其实相当于已经实现了，但是后序还会调用翻译插件，实际上OCR这个功能本身也很常用，希望能把OCR和翻译服务分离开，提供一个只OCR不翻译的选项

**Comment by ripperhe** [comment]
感谢建议，有这方面的计划 👌

**Comment by ripperhe** [comment]
@haoshaoyang 等久了，独立 OCR 功能来了，升级 0.9.0 版本即可
