### ISSUE TITLE
谷歌语音接口无法使用

### ISSUE THREAD

**Issue by AriaLyy** [ripperhe/Bob#137]
## 运行环境
* Device: MacBook Pro 2018, 15-inch
* macOS: 10.15.7
* Bob Version: 0.5.4

## 描述问题
我已使用了科学上网工具，但是验证api时，等了10多秒，谷歌语音合成的接口还是提示网络异常，并且谷歌后台我已经打开了api的限制
![image](https://user-images.githubusercontent.com/10437293/103193470-7f139f80-4917-11eb-8f61-45c8e7cacc56.png)

开了下上网工具的日志，应该是生效的
![image](https://user-images.githubusercontent.com/10437293/103193822-956e2b00-4918-11eb-93f2-f6028b6083f9.png)

**Comment by zenof** [comment]
![2020-12-28 01 44 40](https://user-images.githubusercontent.com/37714471/103198584-4d1a2300-48ae-11eb-8083-5543156c2303.gif)


试了下秒验证成功没有问题，建议楼主再检查下科学上网规则

**Comment by ripperhe** [comment]
@AriaLyy 我也是建议你检查下你的规则

这是 Google 语言合成的地址 `https://texttospeech.googleapis.com/v1/text:synthesize `

**Comment by AriaLyy** [comment]
确实是vpn的问题，重启一下就好了
