### ISSUE TITLE
强迫症设计师受不了这个图标啊！啊！啊！

### ISSUE THREAD

**Issue by shadow-zzh** [ripperhe/Bob#138]
看见更新提示：适配新图标，
终于，终于，终于改图标了。
更新完。。。
你就加了个框😭！！

**Comment by ripperhe** [comment]
淡定，哈哈哈 🤣

**Comment by ripperhe** [comment]
这个 issue 我就先关了，如果您有做好的图标，请直接发到这里哈 #129，谢谢啦
