### ISSUE TITLE
简化窗口

### ISSUE THREAD

**Issue by xtuer** [ripperhe/Bob#14]
一般选择一种翻译方式后很少改变，建议可以把翻译的选择和语言检测的 Ui 隐藏起来，可以在右上角增加一个 toggle 的按钮，点击显示，再点击就隐藏。

**Comment by ripperhe** [comment]
恩恩，这个UI改动较大，暂时不会改，但是后期准备用更合理的方式展示翻译后的UI，这个点会考虑进去

**Comment by ripperhe** [comment]
0.5.2 版本可以支持隐藏
