### ISSUE TITLE
我写了一个Raycast脚本，方便快速调用Bob

### ISSUE THREAD

**Issue by Jax0rz** [ripperhe/Bob#140]
[Raycast](https://raycast.com)是一个类似Alfred的App，脚本点这里[下载](https://github.com/Jax0rz/script-commands/blob/master/commands/navigation/bob.applescript)安装。
<img width="862" alt="CleanShot 2020-12-30 at 15 18 38@2x" src="https://user-images.githubusercontent.com/7557357/103336693-e8301a00-4ab3-11eb-963a-f2604cc11f44.png">

<img width="862" alt="CleanShot 2020-12-30 at 15 18 48@2x" src="https://user-images.githubusercontent.com/7557357/103336752-0dbd2380-4ab4-11eb-8881-33f452553209.png">

<img width="446" alt="CleanShot 2020-12-30 at 15 18 55@2x" src="https://user-images.githubusercontent.com/7557357/103336787-2299b700-4ab4-11eb-831f-ceaddbc98a80.png">

**Comment by ripperhe** [comment]
👏 感谢
