### ISSUE TITLE
建议把版本更新加进去

### ISSUE THREAD

**Issue by hellofx** [ripperhe/Bob#142]
我之前是0.5.2，一直也没提示我更新，后来无意中才发现有了0.5.4版本
然后来GitHub下载了一个0.5.4，安装后本地出现了，bob-2 bob-3两个应用程序，他好像也不会像其他软件那种自动覆盖更新安装。
建议优化，谢谢老板

**Comment by ripperhe** [comment]
1. 关于自动检查更新，是不是没有开启这里；开启之后会不定期自动检查更新

![image](https://user-images.githubusercontent.com/13943595/103417860-60d3cb00-4bc7-11eb-920e-c39b3f1acc79.png)

2. 另外，可以手动检查更新，在这里

![image](https://user-images.githubusercontent.com/13943595/103417910-94aef080-4bc7-11eb-8490-de2ea333c906.png)

3. 手动安装的正确操作方法是
    1. 下载 Bob.zip 文件
    2. 解压出文件，Bob.app
    3. 拖拽 Bob.app 文件到「应用程序」文件夹，并选择覆盖安装

按照上述方法操作应该不会出现 bob-2 bob-3 的情况，你可以看下哪一步没操作对
