### ISSUE TITLE
拆分功能扩展

### ISSUE THREAD

**Issue by inbreaks** [ripperhe/Bob#144]
考虑如下用例，目前支持情况如下，希望考虑支持下面两种情况

| Case           | Result | |
|------------|-------|--|
|hello_world |hello world| ✅ |
|helloWorld |hello World| ✅ |
|HelloWorld |Hello World| ✅ |
|hello-world |hello-world| ❌ |
|hello/world |hello/world| ❌ |

**Comment by ripperhe** [comment]
@inbreaks 感谢建议。

对于 `hello-world `，有些复合词需要用 `-` 连接，拆分之后可能会影响词义，所以不打算添加了。
对于 `hello/world `，我这边再看下有没有其他影响，没有的话就加上去

**Comment by inbreaks** [comment]
> @inbreaks 感谢建议。
> 
> 对于 `hello-world `，有些复合词需要用 `-` 连接，拆分之后可能会影响词义，所以不打算添加了。
> 对于 `hello/world `，我这边再看下有没有其他影响，没有的话就加上去

`hello-world ` 这种命名方式在coding过程中非常常见。另外在Google翻译中可以准确处理被拆分的复合词，下面的截图可供参考。

![image](https://user-images.githubusercontent.com/1317194/104808420-2736cd00-5821-11eb-9140-0f4e0e75228d.png)

**Comment by ripperhe** [comment]
这也不太能确定是否所有复合词去掉 `-` 后 Google 都能正确处理。之所以会这么认为，是因为我之前认为百度翻译能自动拆分驼峰，因为我用它翻译 `WhatAreYouDoing` 能正常识别，但后来发现它有的可以，有的词语不行。

另外，Bob 里面还有其他的翻译服务，不确定是否会引起错误，不了解内部是怎么做的，也不太希望把这种容错寄托于翻译服务上。

如果这种命名规则确实经常使用的话，那这边在设置加个选项吧，默认关闭，开启之后拆分 `-`，你觉得怎么样？

**Comment by inbreaks** [comment]
> 这也不太能确定是否所有复合词去掉 `-` 后 Google 都能正确处理。之所以会这么认为，是因为我之前认为百度翻译能自动拆分驼峰，因为我用它翻译 `WhatAreYouDoing` 能正常识别，但后来发现它有的可以，有的词语不行。
> 
> 另外，Bob 里面还有其他的翻译服务，不确定是否会引起错误，不了解内部是怎么做的，也不太希望把这种容错寄托于翻译服务上。
> 
> 如果这种命名规则确实经常使用的话，那这边在设置加个选项吧，默认关闭，开启之后拆分 `-`，你觉得怎么样？

我认为这种解决方案就目前来说是最优的。另外经过测试Google、有道等处理`-`还有细微差别，确实不宜作为默认选项。
总之，增加`-`拆分选项对coder来说是利好消息，感谢关照。

**Comment by ripperhe** [comment]
@inbreaks 0.7.0 加上了这两个拆分方式。
😭 而且我忘记了给 `-` 拆分提供选项... 先这样吧
