### ISSUE TITLE
近期， 服务中的百度通用翻译API 不能用了

### ISSUE THREAD

**Issue by webxmsj** [ripperhe/Bob#146]
## 运行环境
* Device:  MacBook Pro (15-inch, 2019)
* macOS: 11.1
* Bob Version: 0.5.4

**Comment by ripperhe** [comment]
能否截图看下？你是用的密钥还是免费的那个？

**Comment by webxmsj** [comment]
> 能否截图看下？你是用的密钥还是免费的那个？

密钥的

**Comment by ripperhe** [comment]
@webxmsj 
我这边测试没有发现问题，如果你仍旧有问题，请加我 QQ `453942056` 发送日志给我。

**Comment by webxmsj** [comment]
谢谢， 已经好了
