### ISSUE TITLE
考虑加入阿里云

### ISSUE THREAD

**Issue by Raychanan** [ripperhe/Bob#147]
以下内容为转发，可以考虑一下阿里云（**每月有百万字符的免费额度**）：

关于DeepL：各位，DeepL并不像大家想的那么好。

DeepL的问题：
**DeepL实际上，和Google翻译一样，有个根本问题：“传话筒接力”。**

Google翻译不准确的一个巨大问题，在于虽然Google也是AI翻译，但是，他把所有语言翻译为英文，然后，再把这个生成的英文，翻译成用户选择的目标语言。

这个2次翻译，就会导致巨大问题，因为翻译为中间语言的词汇，可能是多义词。于是，把这个多义词2次翻译为目标语言，往往会选择错误的意思。

比如，日语“処世術”，用户选择翻译为中文。Google会先翻译为英文"treatment"。这个词，有“对待方法”和“治疗”2个意思。再翻译为中文时，会选择“治疗”，于是Google就翻译错了。

deepl也是类似，他把所有语言，先翻译成德语，再翻译成用户选择的目标语言。它比google准确在于，deepl以前是做电子词典的，所以AI的词汇量比google大，德语词汇歧义比英语少。但是，并没有解决2次翻译导致的“传话筒接力”这个根本问题。

本人也经常使用deepl，但很快发现，翻译错误、甚至完全无法翻译的现象非常多。就是因为“传话筒接力”问题。

而国内翻译工具，都是AI翻译，引擎和deepl一样，而且没有“传话筒接力”问题，因此准确度实际上比deepl要好，仅仅只是没有宣传，缺少名气。

**本人对比过国内AI翻译引擎，其中，行文最通畅，最像人工翻译的引擎，实际上是阿里云的翻译服务！**

行文流程程度比deepl更好，词汇量和腾讯翻译一致。但是，阿里云的翻译从未做过宣传，因此大众不知道。作为质量最高的翻译服务，这里的引擎列表里甚至没有。

因此，希望降低deepl的优先级。大众用户是非常容易被名气误导的，因为从未对比，根本不知道其他选择。

如果要做，建议所有收费翻译服务，做成让用户填入自己的key或token的方式使用。谁用谁去申请。

最后：
阿里云翻译 +1

大家可以去体会下阿里云翻译：
https://www.aliyun.com/product/ai/base_alimt

更新：
阿里云API也是收费的，但是每月有百万字符的免费额度。做成填入用户自己的api key的方式，可以比较好的解决费用问题。

**Comment by ripperhe** [comment]
@Raychanan 
感谢转发 🤝。我调研下先，合适的话，近期会加上。

**Comment by JingxinLee** [comment]
同意同意。 api申请好了，坐等 ！

**Comment by ripperhe** [comment]
@Raychanan @JingxinLee 已在 0.6.1 版本添加上阿里翻译
