### ISSUE TITLE
谷歌翻译无法使用，网络异常

### ISSUE THREAD

**Issue by eliasyaoyc** [ripperhe/Bob#148]
## 运行环境
* Device: MacBook Pro (16-inch, 2019)
* macOS: 11.2.Beta
* Bob Version: 0.5.4

## 描述问题
最近几天谷歌翻译无法使用，网络异常
![image](https://user-images.githubusercontent.com/46013886/105651047-aba7e080-5ef0-11eb-8291-d1ae2b7c709c.png)

**Comment by ripperhe** [comment]
@eliasyaoyc 
感觉是因为最近 Google Cloud 的 API 国内无法访问了，你把这个域名走代理试下 `googleapis.com`

**Comment by eliasyaoyc** [comment]
我翻了墙 ...有道也不行 刚刚试了下

**Comment by ripperhe** [comment]
😓 额，那考虑重启 Mac，重启 Bob 。。。

**Comment by eliasyaoyc** [comment]
重启大发后  有道好了，谷歌还是裂开

**Comment by ripperhe** [comment]
@eliasyaoyc 解决啦？

**Comment by eliasyaoyc** [comment]
没有呀 谷歌用不了，就先用用有道。。。

**Comment by ripperhe** [comment]
好吧，那先凑合着用吧
