### ISSUE TITLE
百度翻译接口失效

### ISSUE THREAD

**Issue by zelong77** [ripperhe/Bob#150]
## 运行环境
* Device: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
* macOS: 11.1
* Bob Version: 0.5.4

## 描述问题

百度翻译接口失效了吗?
![QQ20210129-021627](https://user-images.githubusercontent.com/24781357/106181186-3f6efa80-61d8-11eb-954d-95b563b3a12f.png)

**Comment by ripperhe** [comment]
请加我 QQ 453942056 发我日志

**Comment by ripperhe** [comment]
和 @zelong77 沟通过后，问题已解决，以下主要写给遇到同样问题的其他用户。

经排查，问题出在百度翻译服务选中的版本上，可在以下链接的如下位置查看你所选的服务版本

http://fanyi-api.baidu.com/api/trans/product/desktop

![D2F8CE439CDF0FBA2AB1919B8E43FA13](https://user-images.githubusercontent.com/13943595/106408809-22f1ed00-647a-11eb-8360-ac357f663a76.png)

* 如果开通的是标准版，则无需认证，立即开通；
* 如果开通的是高级版，则需完成个人认证，立即开通；
* 如果开通的是尊享版，则需完成企业认证并审核通过后，方可开通成功。

详细可参考这个链接 https://fanyi-api.baidu.com/doc/13

@zelong77   的问题在于选中了「尊享版」，但是并没有完成企业认证。

**Comment by Hug125** [comment]
Device: MacBook Air 2018
macOS: 11.0.1
Bob Version: 0.5.4

我开通的高级版，且完成了个人认证，在正常使用了将近一个月的时间，今天开始发现无法使用。
 13:00切换成标准版，目前还会提示服务异常。
