### ISSUE TITLE
Big Sur 11.2翻译框定位问题

### ISSUE THREAD

**Issue by Skyxim** [ripperhe/Bob#152]
## 运行环境
* Device: 
* macOS: 11.2
* Bob Version: 0.5.4

## 描述问题

在11.2 翻译框不会出现在鼠标位置而是一直在状态栏下方

https://user-images.githubusercontent.com/70276018/107137735-6b158180-694a-11eb-8bc2-94bba5612924.mov

[com.ripperhe.Bob 2021-02-07--04-28-57-532.log](https://github.com/ripperhe/Bob/files/5938335/com.ripperhe.Bob.2021-02-07--04-28-57-532.log)

**Comment by ripperhe** [comment]
好的，麻烦再截一张 「偏好设置-高级」的图片，方便定位问题

**Comment by Skyxim** [comment]
> 好的，麻烦再截一张 「偏好设置-高级」的图片，方便定位问题

提醒我了，重装了系统 忘了设置，我的
