### ISSUE TITLE
可否加入单词本，将特定的单词翻译导入翻译结果中？

### ISSUE THREAD

**Issue by asnahu** [ripperhe/Bob#156]
比如LATEX这个词，google api习惯性翻译成橡胶，可实际上是一个排版软件。

**Comment by lehaifeng000** [comment]
这个软件原理是调用各大翻译软件的api，如百度翻译等等。如果你用的是公用appkey肯定不行，因为大家都是一个账号。你可以添加自己的appkey，然后进行添加。如百度翻译的api，自己注册一个appkey，然后添加术语库，那么翻译的时候百度翻译会参考你自定义的解释
<img width="1124" alt="截屏2021-03-15 上午11 15 32" src="https://user-images.githubusercontent.com/29175644/111099162-db35a980-857f-11eb-99a7-ce4d7d0fd45a.png">

**Comment by asnahu** [comment]
好明白了，谢谢🙏
