### ISSUE TITLE
楼主， 翻译出来的中文字体， 太小了， 做成一个快捷键， 可以调整字体大小的。

### ISSUE THREAD

**Issue by hawkinchina** [ripperhe/Bob#16]
楼主， 翻译出来的中文字体， 太小了， 做成一个快捷键， 可以调整字体大小的。

**Comment by ripperhe** [comment]
下个版本会在设置页面加上调整字体大小，但是不会加快捷键

**Comment by ripperhe** [comment]
[0.3.0](https://github.com/ripperhe/Bob/releases/tag/v0.3.0) 版本已支持调整字体大小，需在偏好设置页面调整
