### ISSUE TITLE
对于OCR识别的文字，能否增加自动删除换行的功能

### ISSUE THREAD

**Issue by ulpyuxa** [ripperhe/Bob#161]
如题，Bob的OCR识别文字能否增加自动删除换行的功能，

**Comment by ripperhe** [comment]
感觉可行，后面加一下

**Comment by ripperhe** [comment]
加上了，把这个开一下
![image](https://user-images.githubusercontent.com/13943595/143735521-82b1133a-a37d-4d51-8622-3f2bbe96759f.png)
