### ISSUE TITLE
腾讯翻译君 私钥 出现问题

### ISSUE THREAD

**Issue by Flipped199** [ripperhe/Bob#166]
翻译失败，错误码 InvalidParameter
Url key and value should be splited by `=`.

**Comment by ripperhe** [comment]
@Flipped199  检查下秘钥是否填错了，我刚测试 OK

**Comment by Flipped199** [comment]
> @Flipped199 检查下秘钥是否填错了，我刚测试 OK

可能是我子账号密钥有问题，我刚不通过子账号重新弄了一次，成功了，谢谢
