### ISSUE TITLE
建议加入单词本功能

### ISSUE THREAD

**Issue by iBreaker** [ripperhe/Bob#167]
如题

每次查完后下次还得查，加个生词本，没事可以背一背

**Comment by saltbo** [comment]
同求生词本

**Comment by Bolvvv** [comment]
同求生词本，另外希望支持生词本导出功能，格式可以自定，后续可以由社区其他参与者写插件进行格式转换，如bob生词本->有道生词本、bob生词本->anki等等.

**Comment by Monster0303** [comment]
跪求生词本，只能导出txt或json都可以

**Comment by ripperhe** [comment]
0.7.0 添加了收藏功能，可以导出 excel
