### ISSUE TITLE
跨平台复刻请求

### ISSUE THREAD

**Issue by grsky360** [ripperhe/Bob#171]
@ripperhe 
因为有在windows和mac切换使用的场景, 想开发一个类似的工具
想问一下是否可以参照Bob的一些设计和功能进行开发, 会进行开源并添加Thanks

**Comment by eliot-ye** [comment]
大佬666，萌新不懂桌面开发，请大佬开发完告知一声。同样有windows和mac切换使用的场景，一直苦于没有相似的工具。另外，Windows商店里有一个Pantherbar可以和pop类似，能集成的话，在翻译这一块上就真的无缝使用了

**Comment by grsky360** [comment]
@eliot-ye under developing. 平时闲的时候写写, 还在写ui... 我是做server的, 边看边写
