### ISSUE TITLE
翻译能增加音标吗

### ISSUE THREAD

**Issue by AriaLyy** [ripperhe/Bob#172]
软件很好用，但是翻译没有音标项，能否增加音标显示？
![image](https://user-images.githubusercontent.com/10437293/113117606-34206580-9241-11eb-9cb1-2f8b5f6a985c.png)

**Comment by terranc** [comment]
![image](https://user-images.githubusercontent.com/224353/115893650-0965ad80-a48b-11eb-8abe-26c0f6cd63f6.png)

**Comment by ripperhe** [comment]
同上。另外也可以在 Bob 使用有道翻译和金山词霸服务，都有这个功能。
