### ISSUE TITLE
百度翻译查词

### ISSUE THREAD

**Issue by Raychanan** [ripperhe/Bob#173]
百度翻译可以出查词结果吗？就像划词翻译这个Chrome扩展里面这样。谢谢！

![image](https://user-images.githubusercontent.com/53246211/113501746-29741200-955a-11eb-93fc-42844e5b6489.png)

**Comment by ripperhe** [comment]
目前我接入的这个 API 对普通用户没有开放查词功能。
可以升级到 0.7.0 版本，用金山词霸代替。
