### ISSUE TITLE
无法在翻译结果栏朗读日语和韩语

### ISSUE THREAD

**Issue by PerpEternal** [ripperhe/Bob#178]
## 运行环境
* Device: MacBook Pro (15-inch, 2016)
* macOS: 11.2.3
* Bob Version: 0.6.1

## 描述问题

无法在翻译结果栏朗读日语和韩语
<img width="294" alt="Screen Shot 2021-04-11 at 9 45 05 PM" src="https://user-images.githubusercontent.com/30803659/114306728-5fdbff00-9b0f-11eb-9802-d3e679c38521.png">
在输入栏都可以成功朗读
<img width="298" alt="Screen Shot 2021-04-11 at 9 45 59 PM" src="https://user-images.githubusercontent.com/30803659/114306744-6c605780-9b0f-11eb-87d5-be28c2414d48.png">

**Comment by ripperhe** [comment]
麻烦升级到 0.7.0 版本再试试
