### ISSUE TITLE
popclip 插件是个不错的点子

### ISSUE THREAD

**Issue by jiangyuan** [ripperhe/Bob#18]
https://pilotmoon.com/popclip/extensions/

天生契合的场景。

**Comment by ripperhe** [comment]
好的，正在研究

**Comment by tshu-w** [comment]
@ripperhe 其实之前有一款插件了，可以参考下 https://github.com/wizyoung/googletranslate.popclipext

**Comment by ripperhe** [comment]
> @ripperhe 其实之前有一款插件了，可以参考下 https://github.com/wizyoung/googletranslate.popclipext

嗯 我已经写好了，过几天会发布

**Comment by ripperhe** [comment]
0.3.0 版本已支持 [releases](https://github.com/ripperhe/Bob/releases)
