### ISSUE TITLE
【bug】【bobclip】 点击bobicon 不会发生任何事情 

### ISSUE THREAD

**Issue by Valar103769** [ripperhe/Bob#181]
## 运行环境
* Device: 卡特琳娜 10.15.7
* macOS: 10.15.7
* Bob Version: 0.6.1[4]

## 描述问题

选中一段文本之后，弹出工具栏，点击工具栏上的bobicon，期望弹出翻译窗口，但是实际没有任何反应

**Comment by ripperhe** [comment]
麻烦升级到 0.7.0 版本看看还有没有问题
