### ISSUE TITLE
有无可能在查询一个单词时连带把相应的词性显示出来？

### ISSUE THREAD

**Issue by terranc** [ripperhe/Bob#182]
由于有时候查一个单词的时候只是查出来一个翻译意思，但并不知道是什么词性，导致对翻译理解的时候产生困扰，不知有无这种可能。

**Comment by terranc** [comment]
原来现在可以导入词典了，自闭了

**Comment by BarryLiu1995** [comment]
> 原来现在可以导入词典了，自闭了

请问如何导入词典，是通过插件安装吗？
