### ISSUE TITLE
建议让用户自定义（源语言及目标语言）语言选项

### ISSUE THREAD

**Issue by Martian746** [ripperhe/Bob#186]
![image](https://user-images.githubusercontent.com/60570225/118561476-9dcae380-b79d-11eb-93bf-934e57909b49.png)

每个人关心的语种应该都是固定的某几个而已，Bob 的源语言/目标语言没必要列出长长一串 A-Z 的所有可选语种。

建议让用户自定义语言选项，参考 QTranslate：

![image](https://user-images.githubusercontent.com/60570225/118547910-41ab9380-b78c-11eb-8565-bffbe6cf3933.png)
![image](https://user-images.githubusercontent.com/60570225/118561016-fe0d5580-b79c-11eb-9320-22d5de4da795.png)

**Comment by ripperhe** [comment]
@Martian746  你好，请升级到最新版，可以设置常用语言了
