### ISSUE TITLE
建议：截图翻译显示在原位置

### ISSUE THREAD

**Issue by wushu037** [ripperhe/Bob#190]
能否像欧路词典或windows的有道翻译一样，截图翻译时在原位置显示翻译
现在这样相当于识别了文本后弹出一个框来翻译文本，不能很方便地把位置对应起来
就像下面这样，这是欧路的：
![image](https://user-images.githubusercontent.com/61787040/120924575-fb9c7c80-c706-11eb-8c6d-4c67f1758f03.png)

**Comment by ripperhe** [comment]
抱歉，暂时没有支持这个功能的计划

**Comment by wushu037** [comment]
> 抱歉，暂时没有支持这个功能的计划

2022年了，请问还没有这个计划吗
多么实用的功能啊
