### ISSUE TITLE
acrobat下，\n替换为空格有问题

### ISSUE THREAD

**Issue by OceanYuanY** [ripperhe/Bob#191]
## 运行环境
* Device: MacBook Pro M1(16g+512g)
* macOS: 11.4
* Bob Version: 0.6.1

## 描述问题
在Acrobat里阅读pdf，已勾选\n替换为空格，但仍出现未替代的情况。

![image](https://user-images.githubusercontent.com/33274496/121014016-171d8b00-c7cc-11eb-89b2-e157c46b52d1.png)

**Comment by GreenHatHG** [comment]
foxit阅读器同样问题

**Comment by ripperhe** [comment]
这个问题在 0.7.0 版本已经修复了，建议升级试试
