### ISSUE TITLE
apple 语音合成在您的电脑上不可用

### ISSUE THREAD

**Issue by kesozm** [ripperhe/Bob#192]
## 运行环境
* Device: MacBook Pro (15-inch, Mid 2019)
* macOS: Mojave
* Bob Version: 0.6.1

## 描述问题

<img width="397" alt="Screen Shot 2021-06-08 at 9 15 40 PM" src="https://user-images.githubusercontent.com/85459755/121282183-aeeba980-c89e-11eb-80a1-177d48255791.png">

apple 语音合成在您的电脑上不可用

如何解决？谢谢。

**Comment by ripperhe** [comment]
这个需要将电脑升级到 macOS 10.15 以上才可以
