### ISSUE TITLE
可否增加一个只识别文本的快捷键选项

### ISSUE THREAD

**Issue by 85Ryan** [ripperhe/Bob#193]
不得不说，Bob 不仅是最好用的翻译工具，也是最好用的文本识别工具。

可否在后续版本中增加一个 只文本识别不翻译的 选项，或者快捷键，因为使用 Bob 来做文本识别的场景还是很多的。

谢谢！

**Comment by ripperhe** [comment]
@85Ryan 新版本的独立 OCR 就是你想要的，试试吧

**Comment by ripperhe** [comment]
另外，感谢你对 Bob 的支持 😬
