### ISSUE TITLE
Parallels Desktop 中无法划词翻译

### ISSUE THREAD

**Issue by cjahv** [ripperhe/Bob#194]
## 运行环境
* Device: MacBook Air (M1, 2020)
* macOS: 11.4 (20F71)
* Bob Version: 0.6.1

## 描述问题
在 Parallels Desktop 中无法划词翻译无法取到文本

**Comment by ripperhe** [comment]
尝试下 0.8.0 版本，参考这个文章 https://ripperhe.gitee.io/bob/#/faq/parallels-desktop-support

**Comment by cjahv** [comment]
对于option+d这个快捷键，是否可以阻止传递到Parallels Desktop从而解决冲突问题？
