### ISSUE TITLE
希望完善断句合并

### ISSUE THREAD

**Issue by undermysk** [ripperhe/Bob#196]
<img width="1440" alt="截屏2021-06-20 16 10 50" src="https://user-images.githubusercontent.com/86183673/122666826-33fd8980-d1e2-11eb-97d4-ea45a33cf18a.png">
如图所示，选中段落后会经常出现如是问题。设置中已经开启将/n替换为空格。

**Comment by CarrotChou** [comment]
+1

**Comment by ripperhe** [comment]
这个问题应该在 0.7.0 版本已经修复了，建议升级试试。
如果还有问题，重开下 issue
