### ISSUE TITLE
翻译不支持显示音标

### ISSUE THREAD

**Issue by colinlabs** [ripperhe/Bob#198]
在之前的版本中，输入翻译有显示音标，如下图：
![image](https://user-images.githubusercontent.com/10361796/123045501-95656880-d42d-11eb-8ae5-07dd3af9db33.png)

现在版本不支持显示音标，希望调用翻译接口时，能把音标也显示出来，便于对单词的认识。
![image](https://user-images.githubusercontent.com/10361796/123045717-d198c900-d42d-11eb-8e91-f65cb945b77b.png)

**Comment by kezhuoquan** [comment]
自己配置网易词典就行了

**Comment by ripperhe** [comment]
@colinlabs  有道翻译和新加的金山词霸可以显示音标
