### ISSUE TITLE
小牛翻译版本更新后已取消免费接口，文档需要更新

### ISSUE THREAD

**Issue by phyzess** [ripperhe/Bob#199]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

7.0 版本已停止免费接口
![image](https://user-images.githubusercontent.com/25143884/124349344-25bb5e80-dc21-11eb-9c1e-7ede7d1f50dc.png)

**Comment by ripperhe** [comment]
@phyzess 已修改，感谢提醒！🤝
