### ISSUE TITLE
在IDEA中源码包的注释无法翻译

### ISSUE THREAD

**Issue by chenkaiyin1201** [ripperhe/Bob#2]

**Comment by ripperhe** [comment]
是划词翻译不能用吗？是提示的获取不到文本还是翻译失败？
你可以把需要翻译的内容和Bob的显示截图给我看一下，如果可以的话，从 `帮助-导出日志 ` 中把日志导出给我定位一下问题

**Comment by lxcsjk** [comment]
IDEA 快捷键冲突

**Comment by chengsifang** [comment]
IDEA 快捷键冲突
---
支持修改快捷键的

**Comment by chenkaiyin1201** [comment]
是快捷键的问题，因为早上没有提示就没深究。抱歉
