### ISSUE TITLE
能否换个icon，容易劝退...

### ISSUE THREAD

**Issue by ch957869975** [ripperhe/Bob#20]
如题所言。

**Comment by helloCx** [comment]
我还想说是不是把这个菜单栏隐藏起来比较好，哈哈~就是一个后台程序。

**Comment by Alex-NKG** [comment]
确实可以考虑换个icon，这个嗯，有点一言难尽

**Comment by brilliantwf** [comment]
图标劝退+1

**Comment by hheng101** [comment]
特别是菜单栏上的那个小图标......确实不好看

**Comment by helloCx** [comment]
这个已经好了啊，可以更换图标了
![image](https://user-images.githubusercontent.com/26318927/76930494-956ce380-6921-11ea-8d26-0f5bddd312f2.png)新图标贼可爱

**Comment by ripperhe** [comment]
😭 对，可以换了，也可以自定义，实在不想看也可以隐藏
