### ISSUE TITLE
Google 翻译 API 验证失败

### ISSUE THREAD

**Issue by kusazh** [ripperhe/Bob#200]
## 运行环境
* Device: M1 MacBook Air
* macOS: 11.4
* Bob Version: 0.6.1 [4]

## 描述问题

今天上午，Google 翻译无法使用，去密钥验证界面提示网络请求异常，但我可以上 google.com。

**Comment by jiangyulinnn** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/28378867/125554304-e6f7d316-5e16-447b-b727-6355ef079e6f.png">
同出现问题

**Comment by NoTalk-ly** [comment]
![image](https://user-images.githubusercontent.com/30374176/126343990-09b4dd7b-df1f-4bd5-a62d-71f03252aec5.png)

腾讯翻译君也出现相同的问题
Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
mac os version: 10.15.7 (19H2)
Bob Version: 0.6.1 [4]

**Comment by NoTalk-ly** [comment]
> ![image](https://user-images.githubusercontent.com/30374176/126343990-09b4dd7b-df1f-4bd5-a62d-71f03252aec5.png)
> 
> 腾讯翻译君也出现相同的问题
> Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
> mac os version: 10.15.7 (19H2)
> Bob Version: 0.6.1 [4]

试了下，重装0.6.0[1]版本也一样

**Comment by HuXinpengFigo** [comment]
![image](https://user-images.githubusercontent.com/36829522/126854048-c68107be-ae92-4914-88cf-87274a7fc126.png)
最新版本，彩云小译也出现同样的问题

**Comment by NoTalk-ly** [comment]
> ![image](https://user-images.githubusercontent.com/30374176/126343990-09b4dd7b-df1f-4bd5-a62d-71f03252aec5.png)
> 
> 腾讯翻译君也出现相同的问题
> Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
> mac os version: 10.15.7 (19H2)
> Bob Version: 0.6.1 [4]

使用另一个子用户的 secret id 和 secret key 后，  验证成功

**Comment by megakusa** [comment]
> ## 运行环境
> * Device: M1 MacBook Air
> * macOS: 11.4
> * Bob Version: 0.6.1 [4]
> 
> ## 描述问题
> 今天上午，Google 翻译无法使用，去密钥验证界面提示网络请求异常，但我可以上 google.com。

已通过重新申请 API 密钥解决。

**Comment by ripperhe** [comment]
根据我的经验，验证失败通常有以下几种类型，遇到问题麻烦先自查一下
1. 申请服务的时候跳过了我写的申请文档里面的某一步或者多个步骤
2. 将秘钥粘贴到 Bob 里面的时候多粘贴的一些东西，比如换行之类的。
    1. 可以选中 Bob 秘钥输入框之后，command + a 全部选中，然后按一下 delete 键全部删掉，然后重新粘贴进去。
    2. Bob 秘钥输入框只能显示一行，可能显示不全你的秘钥，这个不用管。你只需要保证你从服务商那儿复制的秘钥是全的就行。
3. 网络问题。有的服务在全局 VPN 的情况下无法访问，有的服务可能又是开了 VPN 无法访问。
4. 服务商的问题。例如百度翻译，偶尔会概率性封禁用户的秘钥一天，原因不是太明确。

当然也有可能是 Bob 的问题，不过这种概率没那么大，比较如果有明显问题，基本会大批量用户验证失败。

另外可以重启下电脑试试，实在不行加 QQ 群  971584165 找我看看
