### ISSUE TITLE
希望集成火山翻译服务

### ISSUE THREAD

**Issue by Nirnturt** [ripperhe/Bob#203]
[服务地址
](https://www.volcengine.com/product/machine-translation) 

计费：
- 文本翻译的每月免费额度为200万字符。
- 图片翻译的每月免费额度为100张免费调用。
- 语音翻译无免费额度。

优势：
- 字节跳动旗下
- 2020国际机器翻译大赛：火山翻译力夺五项冠军 [链接](https://new.qq.com/omn/20201201/20201201A0504V00.html)
- 免费额度较大

**Comment by wongFanx** [comment]
+1

**Comment by shoyuf** [comment]
火山引擎 Bob 插件 

https://github.com/maybeLab/bob-plugin-volc/releases

**Comment by Nirnturt** [comment]
Bob V1.2 版本已集成火山翻译，感谢作者
