### ISSUE TITLE
能否集成Siri的朗读声音

### ISSUE THREAD

**Issue by CarrotChou** [ripperhe/Bob#204]
目前Bob里的朗读语言是系统自带的“婷婷”，朗读的声音比较生硬，没有感情。

![](https://tva1.sinaimg.cn/large/008i3skNly1gsvjsf9gxqj30ue0oyta7.jpg)

而在系统的辅助功能里，可以看到还有Siri的朗读声音，能否把Siri的声音也集成到Bob里去，Siri朗读的声音比较接近人声。

![](https://tva1.sinaimg.cn/large/008i3skNly1gsvjsfsw7uj313c0tgmzl.jpg)

**Comment by ripperhe** [comment]
@CarrotChou  我目前暂时没有找到 Siri 声音这个选项。
可能是苹果没有开放 API，当然也可能是我没找到而已 😅。
如果有谁清楚怎么做，麻烦告知一下~

**Comment by char8x** [comment]
刚搜到这个 Issue， [NSSpeechSynthesizer](https://developer.apple.com/documentation/appkit/nsspeechsynthesizer) 可以接入吗？
<img width="707" alt="image" src="https://user-images.githubusercontent.com/6831013/216641124-0bd67a71-196b-4e44-b7d3-9690e2e3f246.png">

我发觉这个接口应该和快捷指令中的是类似的

<img width="665" alt="image" src="https://user-images.githubusercontent.com/6831013/216641433-e5774d52-a460-439d-b771-600923ad2a17.png">

**Comment by char8x** [comment]
感谢花时间调研 API，在 StackOverflow 上发现有人提了类似的[问题](https://stackoverflow.com/a/62017898/19868378)，实现起来会有 Bug 或者需要不时杀掉进程，可以先关闭这个 Issue，以后有更好的解决办法再考虑集成
