### ISSUE TITLE
双屏下粘贴的问题

### ISSUE THREAD

**Issue by Fan-SJ** [ripperhe/Bob#205]
## 运行环境
* Device:  MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
* macOS: 11.4
* Bob Version: 0.6.1

## 描述问题
双屏下，在副屏直接调bob粘贴，如果主屏有相同应用到话，就会粘贴到主屏上。比如我在副屏的pycharm上调历史记录直接粘贴，会粘贴到主屏到pycharm的另一个window中去。
现在我只能调出bob不粘贴，仅复制，然后在用com + v 的方式粘贴

**Comment by ripperhe** [comment]
抱歉，「直接调bob粘贴」这句话我没太理解清楚是什么意思。
理解 Bob 翻译完了之后就只有个复制按钮，点击复制就复制到剪切板了，粘贴的话，确实是需要自己去 command + v 去其他软件粘贴的。

**Comment by ripperhe** [comment]
没有进一步的描述，先关闭了，有问题再重开
