### ISSUE TITLE
Mac 11.2.3 版本下 录屏翻译是灰色的屏幕

### ISSUE THREAD

**Issue by jyliao** [ripperhe/Bob#206]
## 运行环境
* Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* macOS:  11.2.3
* Bob Version:  0.6.1[4]

## 描述问题
Mac 11.2.3 版本下 录屏翻译是灰色的屏幕
软件识别不到任何文字信息。

整个屏幕都是灰色的了， 确认录屏权限开启了。 电脑也重启过。

![image](https://user-images.githubusercontent.com/3973012/128370673-45ecb41b-ae58-4eff-8a65-2b1d0433b963.png)

**Comment by jyliao** [comment]
![image](https://user-images.githubusercontent.com/3973012/128446647-8fef9877-096a-4b5a-8168-9647e1d6f2e0.png)

**Comment by ripperhe** [comment]
@jyliao 请参考这篇文章 https://ripperhe.gitee.io/bob/#/faq/screenshot-error
