### ISSUE TITLE
请问bob的汉英字典文件怎么删除

### ISSUE THREAD

**Issue by kzy77** [ripperhe/Bob#207]
## 运行环境
* Device: MacBook Pro (15-inch, 2018)
* macOS: 11.5
* Bob Version: 0.6.1

## 描述问题

请问bob的汉英字典文件怎么删除，它在哪个位置，发现翻译查不出结果，没有使用价值想删除字典文件
![](https://gitee.com/chuck4j/oss/raw/master/uPic/4IhKns.png)

**Comment by ripperhe** [comment]
0.7.0 加了一个删除按钮，升级试试吧 

![image](https://user-images.githubusercontent.com/13943595/143733844-7bf91b2e-f742-4f5c-9fa2-af6451503a32.png)
