### ISSUE TITLE
建议：使用 macOS 12 的 Live Text 功能实现图片文本识别（增加）

### ISSUE THREAD

**Issue by plain-dev** [ripperhe/Bob#208]
## 建议

- 在 **macOS 12** 增加一种识别图片文本的方式，基于 `Vision framework`
- 文本识别在本地进行，充分发挥 `Core ML` 的能力

## 参考资料

- [Extract document data using Vision - WWDC21 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2021/10041/)
- [Locating and Displaying Recognized Text | Apple Developer Documentation](https://developer.apple.com/documentation/vision/locating_and_displaying_recognized_text)

**Comment by ripperhe** [comment]
@plain-dev  现已添加这个功能，麻烦升级一下 0.8.0
