### ISSUE TITLE
有道英文无法发音

### ISSUE THREAD

**Issue by 60ke** [ripperhe/Bob#209]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

有道英文无法发音，![HfJQzB](https://gitee.com/worileqing/upic/raw/master/uPic/HfJQzB.png)

**Comment by whoisix** [comment]
要配置语音合成

**Comment by ripperhe** [comment]
@60ke 需要绑定语言合成实例，参考这个文章的 「创建语音合成实例」这部分说明 https://ripperhe.gitee.io/bob/#/service/translate/youdao

**Comment by yonxao** [comment]
同样的问题，确认语音合成勾选了。而且创建了两个应用试了都不行
![image](https://user-images.githubusercontent.com/24690883/205162408-cd7fc450-1bcb-4142-9fe0-05d882b5b852.png)
![image](https://user-images.githubusercontent.com/24690883/205162738-f10ffa9f-2a37-4c60-b515-c5d115e72e63.png)
