### ISSUE TITLE
chrome中当同时选中网页和地址栏文字时的翻译问题

### ISSUE THREAD

**Issue by 0xlane** [ripperhe/Bob#211]
# 运行环境
* Device: MacBook Pro (Retina, 16-inch, Mid 2019)
* macOS: 11.5.2 (20G95)
* Bob Version: 0.6.1

## 描述问题
当先选中网页的文字，然后选中地址栏中的文字，option+d进行划词翻译，翻译的文字时网页的文字，而不是当前选中的地址栏中的文字：
![image](https://user-images.githubusercontent.com/22788893/132441764-61ea078f-e268-41bb-b169-ced57e37cd98.png)

**Comment by ripperhe** [comment]
是的，确实会有这个问题。
但是是为了保证绝大多数情况下在 Chrome 取词的效果更优，做出了这个牺牲。

如果这是一个强需求，想要规避掉这个问题，可以把 Chrome 这个权限关掉。
![image](https://user-images.githubusercontent.com/13943595/143733657-73955e9f-b774-4317-9054-a59b08c2321b.png)

这样虽然应该不会有这个问题了，但是可能会有一些其他的问题：
https://ripperhe.gitee.io/bob/#/faq/chrome-permission

目前暂未找到两全其美的方案。
