### ISSUE TITLE
文字翻译：多个接口，只显示返回结果最快的那一个

### ISSUE THREAD

**Issue by mefengl** [ripperhe/Bob#212]

**Comment by ripperhe** [comment]
目前看来这些翻译引擎也都还比较快，所以暂时没有用速度来区分的打算。
你是出于什么考虑？

**Comment by mefengl** [comment]
“目前看来这些翻译引擎也都还比较快”，我使用两个引擎，腾讯和彩云，有时使用相当高频，特别是查一大段文字时，往往是腾讯的结果先出来（有时会是彩云先）。在我正看先出来的结果到一半时，另一个会弹出来，会打断我阅读。

**Comment by Vitarum** [comment]
使用场景可能是这样：大部分时间几个翻译结果都半斤八两，所以看到最快的翻译结果就足够了。在效果不满意的情况下才会查看多选的翻译引擎综合考虑。所以可以设置一个选项：是否仅显示最快结果。【此时另外的翻译引擎也在翻译，通过下拉菜单查看】整体还是处于界面简洁高效的考虑

**Comment by Vitarum** [comment]
使用场景可能是这样：大部分时间几个翻译结果都半斤八两，所以看到最快的翻译结果就足够了。在效果不满意的情况下才会查看多选的翻译引擎综合考虑。所以可以设置一个选项：是否仅显示最快结果。【此时另外的翻译引擎也在翻译，通过下拉菜单查看】整体还是处于界面简洁高效的考虑

**Comment by ripperhe** [comment]
@mefengl @Vitarum 好的，理解了，在后续版本加一下
