### ISSUE TITLE
大佬有支持win的计划吗

### ISSUE THREAD

**Issue by iBreaker** [ripperhe/Bob#213]
rt

mac上用起来很顺手, win的有支持的计划吗

**Comment by iBreaker** [comment]
要是没有的话... 我可以搞下

**Comment by knight-666** [comment]
强烈建议支持win，现在win没有比这个软件更好用的工具

**Comment by knight-666** [comment]
> > 强烈建议支持win，现在win没有比这个软件更好用的工具
> 
> 😁 大佬这么长时间没回话, 我已经打算自己搞了

大佬在qq群里比较活跃，这里貌似不太活跃

**Comment by Littlegolden** [comment]
> > 强烈建议支持win，现在win没有比这个软件更好用的工具
> 
> 😁 大佬这么长时间没回话, 我已经打算自己搞了

你开搞吧，win 还是蛮有需求的

**Comment by Shibx414** [comment]
@iBreaker 等你了

**Comment by ripperhe** [comment]
@iBreaker 暂无计划
