### ISSUE TITLE
建议增加快速切换服务选项

### ISSUE THREAD

**Issue by AngryBigCat** [ripperhe/Bob#214]
用了一上午了，也添加了好多个文本翻译的服务，一直在对比文本翻译的效果，但是又不想全部勾选上，害怕浪费免费使用额度，这就得不停得打开偏好设置面板去勾选服务并保存，就很繁琐。

于是乎，就想到了可否用类似ClashX的快速切换节点的操作方法，来快速切换服务

![image](https://user-images.githubusercontent.com/14774417/134635491-0649f41f-f47e-4150-a708-e2ccf9ec24e3.png)

**Comment by ripperhe** [comment]
0.7.0 版本可以在翻译窗口设置，升级试试
