### ISSUE TITLE
建议在语言选择下拉框添加搜索功能

### ISSUE THREAD

**Issue by knight-666** [ripperhe/Bob#215]
建议在语言选择下拉框添加搜索功能

目前可翻译语言非常多，但是想找到某一个比较困难，建议添加搜索功能

![image](https://user-images.githubusercontent.com/28332512/134771202-243a8d50-870c-4735-8909-c3fe81b48eec.png)

**Comment by ripperhe** [comment]
我已经把常用语言放在前面了，请问下你是用来翻译哪个语言吗？
加搜索框确实是个可以优化的点，不过觉得不是很重要，所以没花时间在这个上面

**Comment by ripperhe** [comment]
@knight-666 最新版可以设置常用语言了，可以把自己常用的语言放前面，能解决这个问题
