### ISSUE TITLE
bug: when press CMD+D in MAS, bob will quit

### ISSUE THREAD

**Issue by dutry** [ripperhe/Bob#216]
System: MacOS 11.5.2
Bob version: 0.6.1 [4]

鼠标点击在Mac App Store的界面中（特指对某个app页面中，简介的那一部分），如果按CMD+D，bob会自动退出，很不方便。

**Comment by dutry** [comment]
百分百复现，在mojave上也测试了一下，也是这样的，是bob软件的问题。

**Comment by ripperhe** [comment]
@dutry 能否截图说明一下

**Comment by wwk7225** [comment]
在Monterey下没能复现，不过我觉得这大概不是操作系统版本造成的问题。

（Monterey上）商店里的简介似乎都是无法选中的，这种情况下划词翻译（默认快捷键是option + d）用不了。

或许你可以考虑将快捷键改成其他的（把command + d改回option + d？），同时也检查一下是不是和其他软件的快捷键冲突了。

**Comment by ripperhe** [comment]
无法复现，且没有进一步描述，先关闭了
