### ISSUE TITLE
申请百度翻译私人密钥后，不知道在哪里填写密钥

### ISSUE THREAD

**Issue by yaoyaolii** [ripperhe/Bob#217]
### 运行环境
Bob Version: 0.6.1

按照[教程](https://ripperhe.gitee.io/bob/#/service/translate/baidu)成功获取私人密钥之后，在 <填写密钥>这一步卡住了，教程中是这样描述的
![image](https://user-images.githubusercontent.com/31785560/135196559-438fc4e6-1f8c-41d3-95e3-e497383170c0.png)

但是我的Bob<文本翻译>页面是这样的，没有看到填写密钥的地方，其他的服务，例如google翻译倒是可以看到填写密钥的输入框。
![image](https://user-images.githubusercontent.com/31785560/135197143-65af8560-47bb-4cae-9643-ee12c507c8c2.png)

想请问这个问题怎么解决呢？

**Comment by ripperhe** [comment]
@yaoyaolii 你得点下方的那个 「+」号，然后加一个「私人秘钥」那一栏的百度翻译

![image](https://user-images.githubusercontent.com/13943595/135197765-c9d8666b-5960-41e5-ad9c-2af6e5cd2fea.png)
