### ISSUE TITLE
提供"-\n"自动变成""的规则功能

### ISSUE THREAD

**Issue by Silbernitrat** [ripperhe/Bob#218]
使用场景：
![image](https://user-images.githubusercontent.com/33633362/135622063-00de28fd-d912-4ed1-a68c-7d6a26b5b284.png)

单词切分后翻译出错，现在只能"\n"变成" "，不能满足需求，"synonyms"单词会变成"syn- onyms"

**Comment by ripperhe** [comment]
0.7.0 版本尝试处理了这个换行连字符的问题，升级试试
