### ISSUE TITLE
fontsize 請問能否再設定更大一點的字體

### ISSUE THREAD

**Issue by Aqzhyi** [ripperhe/Bob#219]
![image](https://user-images.githubusercontent.com/1500206/135749152-9b1bce2b-86eb-48a5-ae9c-6177d0d35d0f.png)

這個對我來說，還是不夠大，人老了眼睛看不清楚 😢 謝謝

**Comment by ripperhe** [comment]
你好，1.4.0 版本增加了两号更大的字体
