### ISSUE TITLE
软件设置开机自启,快捷键无效

### ISSUE THREAD

**Issue by WaterSunMount** [ripperhe/Bob#220]
## 运行环境
* Device: MacBook Pro（16 英寸，2019） 黑苹果
* macOS: 11.6
* Bob Version: 0.6.1[4]

## 描述问题
> 已排查不是快捷键冲突问题
1. 软件设置开机自启
2. 截屏翻译和划词翻译都使用了自定义快捷键
3. 开机后不点开设置界面,使用快捷键无效,点开设置界面,快捷键可以使用了

## 解决办法
系统偏好设置-> 用户与群组->登录项->Bog的隐藏去掉勾选就可以了

**Comment by ripperhe** [comment]
升级到最新版，再看看还有没有这个问题

**Comment by spiropanton** [comment]
没有了，已经修复

**Comment by ripperhe** [comment]
> 没有了，已经修复

好的 👌🏻
