### ISSUE TITLE
自行添加的引擎是否能做缓存处理，避免尽量提前消耗完免费额度。

### ISSUE THREAD

**Issue by truebit** [ripperhe/Bob#221]
自行添加的引擎是否能做缓存处理，避免尽量提前消耗完？

针对每个添加成功的引擎，对每次搜索结果进行LRU缓存，如果下次使用了缓存的结果，直接给出答案。
另外可以增加一个清除缓存的按钮，用于清除缓存操作。

**Comment by ripperhe** [comment]
主要是考虑到翻译句子很难完全匹配上，翻译单词的话就没几个字符，所以没做缓存
