### ISSUE TITLE
建议实现自定义正则替换功能

### ISSUE THREAD

**Issue by Flipped199** [ripperhe/Bob#222]
看到增加了\n替换空格，突然想到是否可以提供自定义正则替换功能，经常翻源码注释但是英文水平又不咋地的我，用bob翻译会多出一堆注释符号，影响阅读体验，特此来提一提建议，希望采纳

**Comment by ripperhe** [comment]
恩恩，确实有这个问题，尝试下 0.7.0 版本的这个选型能否解决你的问题。
![image](https://user-images.githubusercontent.com/13943595/143729168-b4fea2b9-569b-4ed1-a425-fa41b07efb70.png)

另外提供自定义替换的功能，我再考虑考虑

**Comment by Flipped199** [comment]
非常感谢
