### ISSUE TITLE
是否可以更新选项（菜单栏不显示图标）

### ISSUE THREAD

**Issue by evangewille** [ripperhe/Bob#223]
big sur后菜单栏图标变宽，是否可以增加设置功能选择【不显示于菜单栏】
虽然有软件功能可以实现隐藏图标，但是还是希望软件自身能增加此功能，让菜单栏变的更清爽。

软件平时都是开机默认开启的，使用过程中也不会去菜单栏设置。

希望能增加此功能，感谢。🙏

**Comment by BlinVin** [comment]
装个bartender

**Comment by ripperhe** [comment]
@evangewille 升级到最新版，在「偏好设置-通用-通用设置」里面可以关闭
![image](https://user-images.githubusercontent.com/13943595/143678133-849108b1-c93d-4f92-95c1-440fa900cbc3.png)
