### ISSUE TITLE
有地方关闭自动发音吗

### ISSUE THREAD

**Issue by zerochina2020** [ripperhe/Bob#224]
有时候选中较长的内容，会出现下图黑色部分，要发音很长时间，听着挺烦的。
![image](https://user-images.githubusercontent.com/11956058/142177592-487bbb78-40fe-4a5e-a6fa-5b737331c709.png)

**Comment by ripperhe** [comment]
额，Bob 没有这个功能，你看看是啥其他软件搞出来的。
