### ISSUE TITLE
0.7.0内置金山词典强制区分大小写

### ISSUE THREAD

**Issue by haoshaoyang** [ripperhe/Bob#226]
首字母大写无法识别
![image](https://user-images.githubusercontent.com/20434917/143719241-9348d78b-6aa7-47e7-aa2d-6ced373d77a9.png)
小写可以正常识别
![image](https://user-images.githubusercontent.com/20434917/143719255-8cd37319-0298-494d-92a8-23d90845cfc3.png)
感觉词典这部分没必要做的这么精准，模糊的相近释义总比没有强

**Comment by wwk7225** [comment]
我试了一下，感觉不是bob的问题，更像是这个接口本身对大写字母兼容不佳……
查USA没结果，查usa却有，而且用小写usa查出来的就是USA
America也是一样的问题，一样的现象
China不好说，主要是C小写了就是另一个意思了
感觉可以再观察观察，如果这个完全服务处理不了大写问题，大概只能无论内容如何全都强制转小写了（China这种大小写不同意思的就永远都翻译不出来了）

**Comment by ripperhe** [comment]
确实是金山词霸接口的问题，看着像是有大写都无法识别，我考虑下咋处理

**Comment by haoshaoyang** [comment]
> 我试了一下，感觉不是bob的问题，更像是这个接口本身对大写字母兼容不佳…… 查USA没结果，查usa却有，而且用小写usa查出来的就是USA America也是一样的问题，一样的现象 China不好说，主要是C小写了就是另一个意思了 感觉可以再观察观察，如果这个完全服务处理不了大写问题，大概只能无论内容如何全都强制转小写了（China这种大小写不同意思的就永远都翻译不出来了）

或许可以调两次接口，全小写一次，严格匹配一次，严格匹配优先级高，没有结果的情况下使用全小写的结果

**Comment by wwk7225** [comment]
> > 我试了一下，感觉不是bob的问题，更像是这个接口本身对大写字母兼容不佳…… 查USA没结果，查usa却有，而且用小写usa查出来的就是USA America也是一样的问题，一样的现象 China不好说，主要是C小写了就是另一个意思了 感觉可以再观察观察，如果这个完全服务处理不了大写问题，大概只能无论内容如何全都强制转小写了（China这种大小写不同意思的就永远都翻译不出来了）
> 
> 或许可以调两次接口，全小写一次，严格匹配一次，严格匹配优先级高，没有结果的情况下使用全小写的结果

其实我的意思就是连试都不用试了，金山的这个接口感觉只要有大写字母就必然失败。
严格匹配America会无结果，但用america查出来的却是America。
![大写](https://user-images.githubusercontent.com/40191996/143747684-668981a5-7157-4b01-a84a-b08523127195.png)
![小写](https://user-images.githubusercontent.com/40191996/143747905-c90d2be8-90c5-4c39-b6f1-5a3f6dbd5e40.png)
所以不是他词库缺东西，而是有大写字母调用必出错。如果真是这样的话，调用的时候直接暴力全转小写就是了，反正也不存在严格匹配大小写能匹配上的可能性。
（Bob作为一个服务调用工具，决定不了被调用的服务本身到底是不是严格匹配。服务提供商提供的接口是严格匹配的，结果就是严格匹配的，除非他们还提供额外的选项允许调用者手动区分严格/不严格。只不过iciba这个接口看起来小毛病有点多，压根处理不了有大写字母的情况。）

**Comment by zerochina2020** [comment]
这个问题有解决吗，Bob是否能加一个取词转小写配置，如果开启取到的词自动转小写，让用户自己选择

**Comment by ripperhe** [comment]
发现金山只能识别小写，现在已经全部强制转换为小写了，大家升级一下 0.8.0 版本
