### ISSUE TITLE
升级0.7.0之后无法获取文字

### ISSUE THREAD

**Issue by ma3252788** [ripperhe/Bob#230]
## 运行环境
* Device: iMac (21.5-inch, 2017)
* macOS: 10.15.3
* Bob Version: 0.7.0

## 描述问题

升级之后，使用快捷键呼出bob就不能获取文字进行翻译了，每次呼出都是空的。
![image](https://user-images.githubusercontent.com/22229456/143983277-1a85c4dc-0cb5-4e25-b8fa-311ac858518a.png)

**Comment by ripperhe** [comment]
@ma3252788 
0.7.0 我更换了快捷键系统，把快捷键重置了。所以如果你之前修改过快捷键，可能会有点问题。

你确认一下看看你现在所使用快捷键是不是「划词翻译」的快捷键，看现象有点像调用的时候「输入翻译」的快捷键。

**Comment by ma3252788** [comment]
> @ma3252788 0.7.0 我更换了快捷键系统，把快捷键重置了。所以如果你之前修改过快捷键，可能会有点问题。
> 
> 你确认一下看看你现在所使用快捷键是不是「划词翻译」的快捷键，看现象有点像调用的是「输入翻译」的快捷键。

谢谢大佬，已经确认是这个问题。
