### ISSUE TITLE
划词翻译时取词错误

### ISSUE THREAD

**Issue by mzbb** [ripperhe/Bob#232]
<img width="880" alt="截屏2021-12-02 07 04 30" src="https://user-images.githubusercontent.com/19501430/144328514-abe8cf64-7e73-47a1-a8b0-97f8404d1eba.png">

这个页面的地址是：https://open.caiyunapp.com/%E4%BA%94%E5%88%86%E9%92%9F%E5%AD%A6%E4%BC%9A%E5%BD%A9%E4%BA%91%E5%B0%8F%E8%AF%91_API
我试了一下，如果这个单词的前面是空格后面是标点符号，那么取词大概率就会失败。看起来像是一个bug，辛苦修一下，十分感谢。另外，这个软件真的挺好用的。

**Comment by ripperhe** [comment]
@mzbb  我用 Chrome 试了下，暂未发现这个现象。
你用的是什么浏览器？尝试用下其他的浏览器试试，看看是这个浏览器特有的问题

**Comment by mzbb** [comment]
@ripperhe 我的浏览器版Microsoft Edge ，版本 96.0.1054.34 (官方内部版本) (arm64)，电脑是MacBook pro 2020 m1版本的，我刚刚也在chrome上试了一下，没有发现这个问题，但是edge浏览器确实还是不正常的，总是丢掉第一个字母

**Comment by ripperhe** [comment]
@mzbb 好的，我后面测试下 edge 下的使用情况

**Comment by ripperhe** [comment]
@mzbb 我用 edge 尚未发现你的这个问题。麻烦你再试试还有没有这个问题。有的话私聊导出日志给我。
QQ: 453942056

**Comment by YuYangOUC** [comment]
@ripperhe 
我遇到几次“T”开头的段落，截图翻译会漏掉“T”：

1. ![image](https://user-images.githubusercontent.com/55630833/151949686-ec77ae04-0400-4751-b425-587673e64e50.png)
![image](https://user-images.githubusercontent.com/55630833/151949999-abc64fc8-c560-4ca1-96ce-0ddb07436a67.png)

2. ![image](https://user-images.githubusercontent.com/55630833/151949782-3fb8e537-baf3-4914-a963-449f25adfe5c.png)
![image](https://user-images.githubusercontent.com/55630833/151950137-50c6bf60-bd57-48e3-9886-d95fcb536f48.png)

**Comment by mqiezi** [comment]
打开edge后重启下bob似乎就可以了

**Comment by ripperhe** [comment]
Bob 最新版已修复该问题
