### ISSUE TITLE
设置隐藏图标后,重启电脑图标仍然显示

### ISSUE THREAD

**Issue by you-hengh** [ripperhe/Bob#233]
## 运行环境
* Device: MacBook Pro M1 max
* macOS: 12.0.1 
* Bob Version: 0.7.0

## 描述问题

 
![image](https://user-images.githubusercontent.com/34816426/144525945-027f69de-87d0-4f81-b510-a32dc8f5fa3d.png)

我设置了开机自启动 并且隐藏图标,但是我电脑重启的时候 还是会发现 程序的图标显示了出来

**Comment by ripperhe** [comment]
@you-hengh 已知问题，下个版本修复，感谢反馈 🤝

**Comment by ripperhe** [comment]
问题已修复，麻烦升级一下 0.8.0
