### ISSUE TITLE
弹窗位置错误？（多个屏幕）

### ISSUE THREAD

**Issue by zhangciwu** [ripperhe/Bob#236]
## 运行环境
* Device: MacBook Pro (Retina, 16-inch, 2019)
* macOS: 12.0.1
* Bob Version: 0.7.0

## 描述问题
不管文字在哪里，翻译窗口总是在左上角
![image](https://user-images.githubusercontent.com/3340597/144997545-fdf5d024-e651-469a-9552-09782bf7a1a4.png)

两个屏幕，排列如下：
![image](https://user-images.githubusercontent.com/3340597/144997622-d5ef4e9a-4f27-4afc-9915-08dd7baa11d9.png)

**Comment by ripperhe** [comment]
请问下这个问题在最新也可以复现吗？
如果还有问题，你设置的翻译窗口位置是什么？
是否有隐藏菜单栏图标？

**Comment by ripperhe** [comment]
有用户反馈是设置为显示在图标下方，并且使用 Bartender 隐藏了 Bob 图标，导致了这个问题，看起来不需要解决。

目前没有进步的信息，先关闭了，后续如果有需要再重开。

**Comment by zhangciwu** [comment]
你好，的确我用了bartender，我改成居中显示即可
另外这个可以增加一个“在选中文字下方”的选项吗？
（sorry回复有点晚）

**Comment by ripperhe** [comment]
我没法准备判断文字的范围，所以也无法显示在文字下方，你可以用「鼠标位置」代替下
