### ISSUE TITLE
根据选中文本是单词还是句子，智能选择默认翻译 Provider

### ISSUE THREAD

**Issue by chanjsq** [ripperhe/Bob#24]
因为英文单词 → 中文，使用百度翻译比较详细；英文句子 → 中文使用 Google 比较准确。所以如果可以设置单词、句子各自的默认翻译服务提供者，会比较方便。望考虑，谢谢！

**Comment by ripperhe** [comment]
恩，确实会存在这种情况，不过这个需求整体架构改动较大，需求考虑下如何设计更好一些，也许后面会加上

**Comment by ripperhe** [comment]
0.5.2 版本可以同时开启多个翻译源，也许可以在一定程度上解决你这个问题

**Comment by chanjsq** [comment]
看到了，非常棒
