### ISSUE TITLE
请求增添直接在界面上调整窗口大小的功能

### ISSUE THREAD

**Issue by zhuozhiyongde** [ripperhe/Bob#242]
如题，现在可以在设置里调整窗口大小，然而日常使用中经常需要根据需求自行调整大小，请问能否增添直接像其他窗口一样，在外置窗口调整大小并且保存设置功能？
即直接对弹出的窗口进行拉伸/缩放，而无需前往设置页面。

**Comment by ripperhe** [comment]
主要是既要自动撑开，又要拉伸比较麻烦，所以没做

**Comment by ripperhe** [comment]
商店版已经添加可以拉伸翻译窗口宽度的功能
