### ISSUE TITLE
有道查询的结果点击播放提示播放音频失败

### ISSUE THREAD

**Issue by LynnLLY** [ripperhe/Bob#248]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

![CleanShot 2021-12-20 at 15 19 39@2x](https://user-images.githubusercontent.com/37694927/146727587-0d2222da-4393-43f3-a434-6aa5faeebc86.png)

**Comment by ripperhe** [comment]
@LynnLLY 有道的申请步骤里面有一步做了才支持音频播放，你是不是漏掉了？

**Comment by LynnLLY** [comment]
@ripperhe 好的,我在看看教程

**Comment by LynnLLY** [comment]
![CleanShot 2021-12-21 at 09 08 41@2x](https://user-images.githubusercontent.com/37694927/146853900-340b1f30-e353-4d74-925b-9e6995c29519.png)

@ripperhe 
我是开了语音翻译,但还是不行

**Comment by ripperhe** [comment]
是「语音合成」哈，不是「语音翻译」，你再找下
![image](https://user-images.githubusercontent.com/13943595/146854132-ca62d577-ff52-46ee-a8c2-a0e962e60b2c.png)

**Comment by LynnLLY** [comment]
@ripperhe 
好的,感谢
