### ISSUE TITLE
“隐藏菜单栏图标”重启后失效

### ISSUE THREAD

**Issue by fenbox** [ripperhe/Bob#249]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, Mid 2015)
* macOS: 12.1
* Bob Version: 0.7.0[13]

## 描述问题

1. 设置“开机启动”且勾选“隐藏菜单栏图标”
2. 重新启动电脑
3. 开机后，菜单栏仍然显示图标

![image](https://user-images.githubusercontent.com/360618/147224642-b5ea4511-521b-41a7-8728-f103a100baff.png)

**Comment by ripperhe** [comment]
@fenbox 感谢反馈，已知问题，下个版本修复

**Comment by ripperhe** [comment]
大家更新一下 0.8.0 版本
