### ISSUE TITLE
音标现实不知道为什么没有了？

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [ripperhe/Bob#251]
软件非常好用，不知道为什么音标从0.5版本之后开始没有了？

**Comment by ripperhe** [comment]
@YELLOWHOMEIN 显示服务是可以配置的，有的服务有。去 Bob 偏好设置 - 翻译 - 服务 里面添加
* 金山词霸 免费
* 有道翻译 收费，不过会送体验金，能用很久
