### ISSUE TITLE
优化翻译卡片

### ISSUE THREAD

**Issue by fuuqiu** [ripperhe/Bob#253]
优化建议1：默认情况下，我是设置快捷键方便划词翻译，为了减小翻译卡片默认关闭输入框，但是偶尔需要调整划词后的输入情况，比如一些格式的调整，快速输入一些不能划词的单词获得翻译情况，希望这里有一个快捷图标显示输入框
优化建议2：使用翻译软件，对于大部分用户来说都是英语翻译中文，希望展示的目标语言和要翻译语言的选项可以缩小或隐藏。
![image](https://user-images.githubusercontent.com/35496061/149543234-3472afab-a95c-4dea-bb75-04d3302c52ff.png)

**Comment by ripperhe** [comment]
@fuuqiu 感谢建议。
第 1 个已经加上了，跟下个版本发版。
第 2 个「希望展示的目标语言和要翻译语言的选项可以缩小或隐藏」具体是指哪个区域？麻烦截图说明下哈

**Comment by fuuqiu** [comment]
![image](https://user-images.githubusercontent.com/35496061/149659066-a136552d-3336-4eee-b19e-29858cedfe9f.png)
如图所示，可以隐藏目标语言和翻译语言。99%的情况下只需要把英语翻译成中文，可以大部分内容都留给真正关注的译文。

**Comment by ripperhe** [comment]
> ![image](https://user-images.githubusercontent.com/35496061/149659066-a136552d-3336-4eee-b19e-29858cedfe9f.png) 如图所示，可以隐藏目标语言和翻译语言。99%的情况下只需要把英语翻译成中文，可以大部分内容都留给真正关注的译文。

明白了，这个的话，你看看是不是这个选项
![image](https://user-images.githubusercontent.com/13943595/149705135-e8ccdea7-af56-4d4a-9716-376eec48dec3.png)

**Comment by fuuqiu** [comment]
非常完美，截图的时候居然没有注意到这个。

**Comment by ripperhe** [comment]
@fuuqiu 好的 👌🏻
先开着把，第一个加上了我再关

**Comment by fuuqiu** [comment]
好的，期待收到更新推送

**Comment by ripperhe** [comment]
@fuuqiu  这个需求应该都已经做完了哈，先关闭了

**Comment by fuuqiu** [comment]
嗯嗯已经实现，且已入手Pro版，目前使用频次非常高的一款应用。期待未来的发展

**Comment by ripperhe** [comment]
好的 感谢支持啦 🤝🏻
