### ISSUE TITLE
为什么限制5个文本翻译服务, 能多一些吗

### ISSUE THREAD

**Issue by aitsc** [ripperhe/Bob#254]

**Comment by ripperhe** [comment]
@aitsc 太多了展开的时候可能会有抖动，影响体验，所以简单限制了下。
请问下实际使用中你会有超过 5 个情况吗？

**Comment by aitsc** [comment]
我开了5个对比翻译句子, 还想开2个专门用于单词查询的. 我看插件挺丰富的, 功能不一样, 还有简体转换的, 主要想同时开了可以应用不同场景.

**Comment by unix2dos** [comment]
> 请问下实际使用中你会有超过 5 个情况吗？

能不能可以配置服务数量，因为有的插件也要占用一个服务。

**Comment by ripperhe** [comment]
@aitsc @unix2dos 先已将限制设置为 10 个了，不过目前翻译历史还是只能保存 5 个服务历史，忘了修改，后面改下
