### ISSUE TITLE
每次Bob启动后，会在~/Documents里面新建mmkv文件夹

### ISSUE THREAD

**Issue by imkaihao** [ripperhe/Bob#255]
## 运行环境
* Device: MacBook Pro (15-inch, 2016)
* macOS: 10.15.7
* Bob Version: 0.7.0

## 描述问题

Bob启动后，会在~/Documents新建mmkv文件夹。
可能的原因：https://github.com/Tencent/MMKV/issues/474

**Comment by ripperhe** [comment]
感谢反馈，已经问题，下个版本修复。

**Comment by ripperhe** [comment]
@imkaihao 更新一下 0.8.0 版本
