### ISSUE TITLE
之前ocr识别会保留行格式，现在为什么识别后所有的都在同一行，都只是用空格隔开了

### ISSUE THREAD

**Issue by yuelingyin** [ripperhe/Bob#259]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
如果你在服务里面用 有道 OCR 的话，效果会好一些。
目前主要是服务商处理的段落信息，Bob 没做太多处理，后期会优化一下。

**Comment by wongFanx** [comment]
打开勾选换行符替换空格, 会出现文本不分段落的情况.
![5BA861BE66DE25948821CB30531954CA](https://user-images.githubusercontent.com/14831158/160226912-96065dc0-6e72-4b00-93cd-660ff7aa566e.jpg)

**Comment by wongFanx** [comment]
关闭换行符替换空格, 会出现文本错误断句的问题.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/14831158/160226943-c79939c2-a5ab-4ad7-a16b-8baaa997bab8.png">

**Comment by ripperhe** [comment]
可以升级下 0.9.0 版本，段落识别有一些优化
