### ISSUE TITLE
建议自动移除原文中的换行符并替换为空格

### ISSUE THREAD

**Issue by alanyeah** [ripperhe/Bob#26]
很多英文文献在翻译时同一个句子会有误判从而导致翻译结果有出入
<img width="660" alt="image" src="https://user-images.githubusercontent.com/13883526/73825213-87ae4380-4836-11ea-9833-d2ff1b7f85b3.png">

**Comment by ripperhe** [comment]
好的，我在下一个版本的偏好设置加一个选项，手动开启

**Comment by tshu-w** [comment]
@ripperhe 另外还有换行连字符也会对有道翻译结果造成挺大影响，不知道有没有启发式方法可以处理，比如：
 im
-portant

**Comment by ripperhe** [comment]
@alanyeah  你好，0.4.0版本在 偏好设置 >  高级 中添加了一个将换行符替换为空格，你可以尝试下能不能解决你的问题

**Comment by ripperhe** [comment]
@tshu-w 后面可以考虑处理下这个细节

**Comment by cherryamme** [comment]
@ripperhe  您好，关于换行替换为空格这个，在wps中行末尾是空格+换行，替换为空格就变为两个空格了，能不能添加个自己设置换行替换的选项，将换行设为空白
