### ISSUE TITLE
希望增加对连词 ff、fi、fl、ffi、ffl 的优化支持

### ISSUE THREAD

**Issue by ysd007** [ripperhe/Bob#261]
目前版本，如果PDF中是连字 ff、fi、fl、ffi、ffl，Bob中还是当成一个字符来识别的，导致无法翻译，需要删除后自己在输入ff、fi等才可以识别。希望Bob能在后期版本中，加入PDF连字 / 合字（ligature）的识别与优化。

**Comment by ripperhe** [comment]
@ysd007 更新 0.8.0 版本试试，做了一些优化

**Comment by ysd007** [comment]
> @ysd007 更新 0.8.0 版本试试，做了一些优化

太赞了，麻烦作者打开赞赏

**Comment by ripperhe** [comment]
> > @ysd007 更新 0.8.0 版本试试，做了一些优化
> 
> 太赞了，麻烦作者打开赞赏

哈哈哈，感谢支持，给你发一个吧

![IMG_0950](https://user-images.githubusercontent.com/13943595/155991981-a91826cf-e176-40b0-be34-1996ddd241e2.JPG)
