### ISSUE TITLE
Parallels Desktop中 Windows 11 如何取消 option+D 打开 Teams 这个快捷键

### ISSUE THREAD

**Issue by zhongmuxiao** [ripperhe/Bob#262]
## 运行环境
* Device: MacBook Pro 16-inch Mid 2019
* macOS: 12.2.1
* Bob Version: 0.8.0

## 描述问题

在Parallels Desktop虚拟机中使用 Bob 0.8.0进行划词翻译，快捷键会有冲突，按option+D就会打开 Teams，这个快捷键如何取消打开 Teams？

**Comment by ripperhe** [comment]
@zhongmuxiao 
说实话，这玩意儿我目前也不知道咋关，不是太了解 Windows，我现在是换个快捷键就好了。

https://ripperhe.gitee.io/bob/#/faq/parallels-desktop-support

如果有谁知道麻烦帮忙解答下吧

**Comment by zhongmuxiao** [comment]
> @zhongmuxiao 说实话，这玩意儿我目前也不知道咋关，不是太了解 Windows，我现在是换个快捷键就好了。
> 
> https://ripperhe.gitee.io/bob/#/faq/parallels-desktop-support
> 
> 如果有谁知道麻烦帮忙解答下吧

快捷键用习惯了，换了不方便。如果有办法解决这个快捷键冲突，那是最好的。虚拟机划词翻译对我来说暂时还不是刚需。

**Comment by ripperhe** [comment]
> > @zhongmuxiao 说实话，这玩意儿我目前也不知道咋关，不是太了解 Windows，我现在是换个快捷键就好了。
> > https://ripperhe.gitee.io/bob/#/faq/parallels-desktop-support
> > 如果有谁知道麻烦帮忙解答下吧
> 
> 快捷键用习惯了，换了不方便。如果有办法解决这个快捷键冲突，那是最好的。虚拟机划词翻译对我来说暂时还不是刚需。

理解，不过从 Bob 端解决感觉的可能性不太大，可能只能看看 Windows 有没有啥设置能规避掉。

如果实在不行，想到一个退阶方案是给划词翻译加个备用的快捷键，就是两个快捷键都能触发划词翻译，这样 option + d 不用改。

**Comment by zhongmuxiao** [comment]
@ripperhe 可以看看多少人有这个需求，两个快捷键还不如换快捷键

**Comment by ripperhe** [comment]
> @ripperhe 可以看看多少人有这个需求，两个快捷键还不如换快捷键

是的，不过都有也不冲突

**Comment by ripperhe** [comment]
现在看来这个问题没有好的解决方案，如果准备在 Parallels Desktop 中使用，还是建议换一个快捷键
