### ISSUE TITLE
可以增加支持windows和linux的平台吗

### ISSUE THREAD

**Issue by LTAND** [ripperhe/Bob#266]

**Comment by JokerFrankZ** [comment]
同求，全平台党用Win的时候一直没找到一个和Bob一样优秀的全局翻译软件

**Comment by plain-dev** [comment]
***Windows*** 平台推荐这个 [https://github.com/biyidev/biyi](https://github.com/biyidev/biyi)

**Comment by ripperhe** [comment]
#58 #65

**Comment by ripperhe** [comment]
你好，目前来说暂时没有这方面的计划

**Comment by product-think2049** [comment]
> 

qtranslate  推荐
