### ISSUE TITLE
这个自建免费的 deepl api 怎么配置到bob插件里面呢？

### ISSUE THREAD

**Issue by zlfengshare** [ripperhe/Bob#267]
这个自建免费的 deepl api 怎么配置到bob插件里面呢？
https://hub.docker.com/r/zu1k/deepl

装完docker后，运行端口显示：然后不知道怎么弄了，有大神知道怎么弄么？

DeepL Translate Api

POST {"text": "have a try", "source_lang": "auto", "target_lang": "ZH"} to /translate

https://github.com/zu1k

**Comment by zlfengshare** [comment]
找到方法了，配合这个插件就可以使用了
docker 镜像： https://hub.docker.com/r/zu1k/deepl
bob 插件： https://github.com/clubxdev/bob-plugin-deeplx

**Comment by ripperhe** [comment]
赞 👍🏼
