### ISSUE TITLE
Google 翻译收费情况

### ISSUE THREAD

**Issue by Ink29** [ripperhe/Bob#268]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

请问我成功添加了Google translate，但设置过程中只有填写信用卡信息，没有看到多少字以上会收费的信息，请问在哪里可以查看？

**Comment by ripperhe** [comment]
@Ink29 可以参考这个文档 https://cloud.google.com/free/docs/gcp-free-tier?hl=zh_CN#free-tier-usage-limits
