### ISSUE TITLE
0.8.0 弹框延迟较大

### ISSUE THREAD

**Issue by echoeureka** [ripperhe/Bob#269]
## 运行环境
* Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* Processor: 2 GHz Quad-Core Intel Core i5
* Memory: 16 GB 3733 MHz LPDDR4X
* Graphics: Intel Iris Plus Graphics 1536 MB
* macOS: 12.2.1
* Bob Version: 0.8.0

## 描述问题
0.8.0 版本弹框弹出延迟明显较慢，在我换回 0.7.0 后弹框延迟明显大幅度减小，应该可以确定是版本的问题。

**Comment by ripperhe** [comment]
@ryanmoyo 麻烦告知下是在哪个 app 取词慢？
如果可以的话，麻烦分别用两个版本在同一个 app 下取词，我这边看下差异

**Comment by ryanmoyo** [comment]
应该不是取词的问题，就是直接弹出输入场景

**Comment by Stage18** [comment]
+1

**Comment by ripperhe** [comment]
请更新 0.9.0 试试看

**Comment by echoeureka** [comment]
看起来 0.9.0 已经解决了这个问题 👍
