### ISSUE TITLE
Bob 0.3.0 无法安装输入翻译插件

### ISSUE THREAD

**Issue by lin-honghui** [ripperhe/Bob#27]
求解？

**Comment by ripperhe** [comment]
能否描述一下详细的症状，提供一下截图什么的？

**Comment by lin-honghui** [comment]
> 能否描述一下详细的症状，提供一下截图什么的？

你好，我下载的最新release的Bob 0.3.0，然后尝试安装Bob PopClip，但Bob PopClip下载完双击无法打开？不知道我是哪一步出的问题？

**Comment by ripperhe** [comment]
你电脑安装了 PopClip 这个软件没？

**Comment by lin-honghui** [comment]
> 能否描述一下详细的症状，提供一下截图什么的？



> 你电脑安装了 PopClip 这个软件没？

没有安装，Bob输入翻译按钮显示是灰色的，但是我刚刚试了下，输入翻译是可以正常使用的（虽然还没装插件）。非常感谢您的耐心解答，软件很喜欢，期待越来越好～

**Comment by ripperhe** [comment]
1. 如果要使用插件调用的话，你电脑要先安装 PopClip，然后再安装插件，详情可以看 [Bob-PopClip](https://github.com/ripperhe/Bob-PopClip) 的说明
2. "Bob输入翻译按钮显示是灰色的" 这个本仓库的常见问题中有说明，不影响使用。选中文本按下划词翻译快捷键即可翻译

感谢支持 🤝
