### ISSUE TITLE
内存占用持续变多

### ISSUE THREAD

**Issue by carpediem-777** [ripperhe/Bob#271]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by carpediem-777** [comment]
我在m1 mac上使用bob，随着使用翻译次数变多 内存也持续增多

**Comment by ripperhe** [comment]
@carpediem-777 应该是存在内存泄漏，下个版本优化下这方面

**Comment by DreamsCat** [comment]
> @carpediem-777 应该是存在内存泄漏，下个版本优化下这方面

+1，我这里使用，只要查询一次，内存就增加多几 M，希望尽快优化，不然越查内存占用越大

**Comment by superchong-zc** [comment]
+1，M1设备几天不关机，惊讶的发现内存超过1G，但是重启软件后就不会了

**Comment by ripperhe** [comment]
大家更新 0.8.1 版本试试
