### ISSUE TITLE
长时间使用内存占用过大（7.9G），可能是有内存泄漏

### ISSUE THREAD

**Issue by XuanBoWu** [ripperhe/Bob#274]
## 运行环境
* Device:  Mac mini (M1, 2020)
* macOS:  12.1
* Bob Version: 0.8.0[16]

## 描述问题

内存占用太大，和使用时间成正比
![image](https://user-images.githubusercontent.com/38022643/158728490-ce2018c5-8718-401e-9ec5-95bf8423a2e6.png)

**Comment by XuanBoWu** [comment]
补充：使用系统内置文本识别的时候内存占用增长明显（每调用一次50M～100M）
使用腾讯云图片翻译api的时候增长不明显

**Comment by ripperhe** [comment]
@XuanBoWu 收到，感谢反馈。
看起来这个问题很严重，下个版本重点处理下这个问题。

**Comment by ripperhe** [comment]
#271
