### ISSUE TITLE
自定义语言切换栏显示的语言

### ISSUE THREAD

**Issue by PerpEternal** [ripperhe/Bob#275]
目前是显示所有语言，看的有些眼花缭乱，希望能自定义，切换的时候方便一点
<img width="343" alt="Screen Shot 2022-03-20 at 11 40 48" src="https://user-images.githubusercontent.com/30803659/159147065-c1d21ec3-d877-4230-a36b-4e5749c23dd3.png">

**Comment by ripperhe** [comment]
@PerpEternal 确实，可以设置会好一些，先记下了

**Comment by victorchor2868** [comment]
希望能增加搜索功能, 可以更简单和快速搜索到语言

**Comment by PerpEternal** [comment]
感觉可以像 Finder 那样，键入首字母实现快速定位

**Comment by ripperhe** [comment]
各位，请升级到最新版，可以设定常用语言，能解决这个问题
