### ISSUE TITLE
自动划词翻译等

### ISSUE THREAD

**Issue by mining-id** [ripperhe/Bob#276]
感谢作品，已经打赏

在每天的使用中，有两个可能会提升效率的建议，供参考：
### 1. 自动划词翻译
目前是选中文字后，然后点击popclip中的bob按钮。因为个人的popclip按钮比较多，然后要从中寻找到bob，加上是高频操作，有点麻烦
<img width="348" alt="image" src="https://user-images.githubusercontent.com/94845005/159164347-f301fddc-9016-430a-8f8c-2da0e3e1d8df.png">

如果可以设置自动翻译，效率就会很高。类似达达
<img width="768" alt="image" src="https://user-images.githubusercontent.com/94845005/159164542-ff52d152-2a77-4a9c-b3c4-9dc3ae6f1b15.png">

https://github.com/waynecz/dadda-translate-crx/

### 2. 截图识别支持自动换行
<img width="262" alt="image" src="https://user-images.githubusercontent.com/94845005/159165240-c13582bb-af01-43bf-bf41-f56b721a1503.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/94845005/159165277-b3505416-1b84-4364-a8c6-59a9022c5074.png">

因为经常用到截图识别并复制功能，但现在的识别效果不能换行，所以需要自己手动调整，比较麻烦

### 3. 截图识别支持识别二维码

目前在电脑端遇到二维码，都是要掏出手机扫一扫，如果可以支持截图识别就方便多了。
下面是微信PC端的功能
![image](https://user-images.githubusercontent.com/94845005/159164764-0987dbd3-4aa3-499d-96af-d1399ab9fa05.png)

### 4. 另外一个强迫症
感觉固定和其他按钮大小、颜色都不一样，个人感觉有点别扭
<img width="446" alt="image" src="https://user-images.githubusercontent.com/94845005/159165158-a24733f7-666c-4497-ab1a-e9def72f82ae.png">

以上，供参考。
再次感谢，祝好！

**Comment by ripperhe** [comment]
@mining-id  感谢支持 🤝
## 1. 自动划词翻译
这个没加是因为 Bob 是个全局翻译的软件，取词会用到剪切板，如果划词自动翻译有概率会造成剪切板混乱，并且容易跟 PopClip 冲突，所以暂时也没考虑做。
如果不好找，可以考虑把 Bob 图标往前放一放。😁
## 2. 截图识别支持自动换行
这个是目前有的文本识别服务能支持自动换行，有的不能。我记得有道是可以的。
另外，如果要保留换行，需要把这个开关关掉
<img width="686" alt="image" src="https://user-images.githubusercontent.com/13943595/159199467-0233246b-659e-42bb-9ba7-5001d25672fc.png">
另外，会在未来的独立 OCR 功能里面优化相关逻辑
## 3.截图识别支持识别二维码
这个也会在未来的独立 OCR 功能里面实现
## 4. 另外一个强迫症
貌似这个图标确实要大一点，后面看看要不要调整。
颜色的话，钉住之后颜色会变成一样的，没钉住确实不一样。

**Comment by mining-id** [comment]
@ripperhe 感谢回复！

第二个（换行）是我没有认真研究软件，抱歉。已经解决了，感谢！

关于第一个（自动划词），也许可以统计下按快捷键或者点击PopClip按钮的数据可以判断下做自动翻译的价值

当然现在的产品已经很好了，以上建议都是锦上添花😄

再次感谢您的贡献！祝好

**Comment by ripperhe** [comment]
@mining-id 
# 2. 截图识别支持自动换行
0.9.0 版本优化了段落识别，你可以尝试把强制合并的开关关掉试试。
# 3.截图识别支持识别二维码
0.9.0 版本的独立 OCR 功能支持二维码识别了
# 4. 另外一个强迫症
图标统一了

**Comment by mining-id** [comment]
@ripperhe  哇，感谢大佬回复

每次更新都立刻有使用，目前使用非常完美！

但我也反思我有乱提需求。。。二维码的那个建议，几天后微信的mac版就支持了，我发现它的很方便，因为支持微信相关的二维码，可以实现扫码登陆和打开小程序，非常方便，相比之前，其他工具的二维码识别就没有这个优势了。所以我目前主要用微信截图的二维码识别功能。

——————————

另外，原来的截图翻译很简单，既能翻译又能OCR，不用考虑场景选择功能，截图就是了。  新版更新的OCR相关功能（截图OCR、访达选图OCR、静默截图OCR）看出来非常大的功能，但我个人的使用感受是产品复杂了。担心新用户会有困惑？ 希望是多余的担心

————————————

在使用过程中，还有个需求和场景，供参考：
因为我的英语不大好，使用英文软件的时候，经常要截图翻译。这就衍生出2个不便：
1. 就是要把翻译窗口定住，然后反复的使用快捷键，进行截图翻译。 每次使用快捷键就很麻烦，所以我现在的解决办法是使用Keyboard Maestro在翻译窗口生成一个快捷方式，每次截图的时候点击快捷方式，就比快捷键快很多，可以看这个录像：
https://user-images.githubusercontent.com/94845005/171468582-fb479008-8617-48ff-8bc9-d181d12bc8d4.mp4
所以，如果bob能在翻译窗口上增加一个再次截图的按钮，可能会比较高效？
<img width="425" alt="image" src="https://user-images.githubusercontent.com/94845005/171469667-97600d7f-a392-4d4c-b015-5b664feae90f.png">



2. 软件中有很多菜单，但bob的截图翻译功能无法截取菜单，所以我得用系统的截图功能截取菜单（https://support.apple.com/zh-cn/HT201361），然后在粘贴到预览中，然后在用bob的翻译截图功能进行翻译，如果bob支持从粘贴板中ORC并翻译，就太好了！

以上不成熟的建议

感谢您！祝好！

**Comment by ripperhe** [comment]
感谢建议。🤝

**关于二维码**

识别二维码相当于是「顺便」的事情，之前也有多人提起过，所以加上啦。
我个人觉得，主要是应对这样一种场景吧。如果长期使用 Bob 进行文本识别，当遇到二维码需要识别的时候，不需要切换软件，不要记住需要切换一个软件这件事儿。

**关于独立 OCR**

是的，我也有考虑到，确实变复杂了，不过总体看来，好处应该是大于坏处的。核心在于独立 OCR 不仅仅是功能的拆分，更是增强。
用户仍旧可以无脑使用截图翻译，但是如果长期单纯为了 OCR 的用户，可以直接放弃截图翻译了，多了一种选择，无论是阅读还是编辑都会比截图翻译有更好的体验。

**关于需求**

**Comment by mining-id** [comment]
@ripperhe 感谢回复


**关于二维码**
我设置了快捷键，⌥+S 是用bob的截图翻译，⇧+⌥+S是调用微信的截图功能，所以也挺好记忆。当然没有一个快捷键来的方便

**关于独立 OCR**
感谢大佬解答，确实产品定位不一定要局限在翻译。可以是识别文字+翻译。


**「无法截取菜单」指的什么呢？子菜单吗**
抱歉，经过确认，我又提了个蠢问题，是我自己的设置问题。原来bob是可以截菜单的。但因为我用Keyboard Maestro在翻译窗口生成一个快捷方式，然后就不能了，我自己改下就行。再次感谢回复，给您添麻烦了。


**再和大佬分享一个我个人经常使用bob的场景**
就是我截图翻译之后，经常下一步动作是要搜索，进行详细的了解。
这个时候我就用Keyboard Maestro配置了一个动作，我个人觉得也挺方便的。这个是录屏：

https://user-images.githubusercontent.com/94845005/171555141-0f64c24b-bd3d-4f20-b995-26b47c30880a.mp4


以上可能都是小众需求。我觉得bob非常好，希望可以做的更简单，让更多的人用上。
感谢大佬的作品
