### ISSUE TITLE
Bob常驻后台多次使用后内存占用呈线性增长

### ISSUE THREAD

**Issue by iHzx** [ripperhe/Bob#279]
## 运行环境
* Device: MacBook Pro 14`2021
* macOS: Monterey 12.3
* Bob Version: 0.8.0

## 描述问题

当长时间运行Bob并多次使用后 应用的内存占用情况会逐渐增加(似线性增长,没有释放的迹象)，当重启应用后可以恢复。
希望作者对此问题修复，谢谢。

**Comment by ripperhe** [comment]
@iHzx 更新 0.8.1 版本试试

**Comment by ripperhe** [comment]
#271
