### ISSUE TITLE
建议可以支持双击形式的快捷键，如双击command启动划词翻译

### ISSUE THREAD

**Issue by chaofan2685** [ripperhe/Bob#28]
## 运行环境

* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
这个需求之前也有人提过，不过现在的使用的快捷键框架不支持，UI也需要调整，暂时不会改。

如果强烈需求的话，可以使用 Alfred 的 workflow 辅助实现，也就是设置一个 Hotkey，然后执行脚本发出调用 Bob 的快捷键即可，我刚做了一个，你可以直接在这里下载 [Bob.alfredworkflow](https://raw.githubusercontent.com/ripperhe/oss/master/2020/0215/Bob.alfredworkflow)，添加到 Alfred，然后设置自己想要的快捷键，如下所示

<img width="712" alt="Bob workflow" src="https://user-images.githubusercontent.com/13943595/74584036-a667c380-5008-11ea-8f6d-a61c15f7a8dd.png">

**Comment by chaofan2685** [comment]
好的，谢谢

**Comment by ripperhe** [comment]
0.7.0 支持双击 command 了，升级试试吧

**Comment by chaofan2685** [comment]
昨晚已经更新了，太棒了


发自王朝凡

------------------ 原始邮件 ------------------
发件人: Ripper ***@***.***&gt;
发送时间: 2021年11月28日 16:36
收件人: ripperhe/Bob ***@***.***&gt;
抄送: 炒饭 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ripperhe/Bob] 建议可以支持双击形式的快捷键，如双击command启动划词翻译 (#28)






0.7.0 支持双击 command 了，升级试试吧

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
