### ISSUE TITLE
希望能增加M1芯片的deepl翻译

### ISSUE THREAD

**Issue by opehisa1** [ripperhe/Bob#280]

**Comment by Silentely** [comment]
为什么要单独说m1芯片的deepl翻译？现有的deepl插件能在m1上使用

**Comment by opehisa1** [comment]
是用docker吗 我用docker好像不太行。能具体教教我吗

**Comment by Silentely** [comment]
> 是用docker吗 我用docker好像不太行。能具体教教我吗

我用api版，docker版本你参考这个https://github.com/clubxdev/bob-plugin-deeplx

**Comment by opehisa1** [comment]
。。。。我看不懂怎么破。。。<img width="977" alt="image" src="https://user-images.githubusercontent.com/102612058/161012641-2adf8ed4-8390-411b-aaae-6bed218a0e18.png">

**Comment by Silentely** [comment]
说得很明白啊、
你第一步安装docker 
`brew install --cask docker`  
第二步部署镜像
`docker run -itd -p 8080:80 zu1k/deepl`
第三步下载插件配置地址

**Comment by opehisa1** [comment]
我不会用docker   T T，能不能加你联系方式帮我弄一下。。。

**Comment by Silentely** [comment]
> 我不会用docker T T，能不能加你联系方式帮我弄一下。。。

QAQ，这已经是傻瓜式的操作，你只需要输入命令安装就可以了。要么你用api free版本但是需要你去注册个帐户拿到密钥

**Comment by opehisa1** [comment]
已经弄好啦 群里的各位大佬帮我解决了
