### ISSUE TITLE
金山词霸，词组翻译的时候会出现首个词组掉到最后的情况

### ISSUE THREAD

**Issue by buildyuan** [ripperhe/Bob#281]
## 运行环境
* Device: MacBook Pro M1 ,  2020
* macOS: 12.3
* Bob Version: 0.8.1

## 描述问题
例如，在翻译 “阿里巴巴与四十大盗” 这个词组的时候，“ali” 这个词会在最后面，参考一下附带的截图

<img width="399" alt="WX20220330-112810@2x" src="https://user-images.githubusercontent.com/31715808/160745843-93a1c692-63f0-4b76-9b94-f25579c09f62.png">

**Comment by wakewon** [comment]
在 0.10.1 版本上未能复现。或许安装新版本试试？

**Comment by ripperhe** [comment]
你好，最新版本已修复
