### ISSUE TITLE
快捷键打开划词翻译时如果没有选中词,打开很慢,大概1秒以上

### ISSUE THREAD

**Issue by nulllpoint** [ripperhe/Bob#282]
我只设置了划词翻译的快捷键, 
如果没有选中词时, 打开直接输入就好, 
如果选中了词就直接翻译, 
过去的几个版本都很流畅, 
直到更新了2022年最近的版本发现如果没有选中词, 使用快捷键打开划词翻译时, 要等1秒以上, 选中的话则很快

**Comment by yimtcode** [comment]
我也有同样的问题，发现有选中内容反应很快，没有选择内容反应大约要1秒左右。

**Comment by RuiFG** [comment]
同有这个问题，期望解决

**Comment by nulllpoint** [comment]
> 我也有同样的问题，发现有选中内容反应很快，没有选择内容反应大约要1秒左右。



> 同有这个问题，期望解决

新版本0.9.0中此问题已经解决了, 再次感谢作者, 有史以来用过的最好用的翻译软件
