### ISSUE TITLE
在Acrobat中划词翻译异常

### ISSUE THREAD

**Issue by Peekabooc** [ripperhe/Bob#284]
## 运行环境
* Device: MacBook Pro (16-inch, 2019)
* macOS: 12.3.0, 12.3.1
* Bob Version: 0.8.1[18]

## 描述问题

在Adobe Acrobat Pro DC(2021.005.20058)中使用划词翻译时，Bob将直接无响应，使用其他功能均正常，复制文字正常，此时Bob的CPU占用会非常高（20%），已经尝试过的解决办法：
1.  重启电脑；
2. 更新macOS至最新；
3. 重装Bob ；

**Comment by of1102** [comment]
我也有这个问题，之前版本没有遇到这种问题。现在只能复制再粘贴翻译，很麻烦。

**Comment by ripperhe** [comment]
> 我也有这个问题，之前版本没有遇到这种问题。现在只能复制再粘贴翻译，很麻烦。

确定之前版本没有问题吗？能帮忙看下之前哪个版本是没问题的吗？
如果能帮忙找出第一个出问题的版本应该比较好解决这个问题，我这边复现不了这个问题。

**Comment by Peekabooc** [comment]
> 

目前我也无法复现这个问题了，我出现问题的版本最早是0.8.0，随后我升级到0.8.1版本后，问题依然没有解决。但是最近使用不再有类似的问题了，这期间我也没有更新过Acrobat。

**Comment by ripperhe** [comment]
> > 
> 
> 
> 
> 目前我也无法复现这个问题了，我出现问题的版本最早是0.8.0，随后我升级到0.8.1版本后，问题依然没有解决。但是最近使用不再有类似的问题了，这期间我也没有更新过Acrobat。
> 
> 
> 
> > > 我也有这个问题，之前版本没有遇到这种问题。现在只能复制再粘贴翻译，很麻烦。
> 
> > 
> 
> > 确定之前版本没有问题吗？能帮忙看下之前哪个版本是没问题的吗？ 如果能帮忙找出第一个出问题的版本应该比较好解决这个问题，我这边复现不了这个问题。
> 
> 
> 
> 

看起来这个问题确实比较诡异

**Comment by of1102** [comment]
目前Bob版本0.8.1 Acrobat版本2021.007.20091 有该问题出现。

**Comment by Peekabooc** [comment]
刚刚重新复现了此问题。
在[这篇论文](https://arxiv.org/abs/1804.02767)，划词翻译一切正常；切换到[另外一篇论文](https://arxiv.org/abs/2004.10934)，使用划词翻译后，bob无响应，但是重新转到之前正常的pdf（也就是前一篇论文）中，在没有重启bob的情况下，bob会自动恢复正常。似乎与PDF的格式有关。
在其他pdf阅读器并没有此问题（我仅测试了浏览器和PDF Expert）。Acrobat版本2021.005.20058。

**Comment by Xu-Wave** [comment]
I also encountered this bug a few seconds ago

**Comment by Xu-Wave** [comment]
No problem with version 0.6.1

**Comment by ripperhe** [comment]
各位，之前对取词做了一些优化，最新版本 Bob 还有这个问题吗？
