### ISSUE TITLE
输入翻译模式下可否增加自动翻译功能

### ISSUE THREAD

**Issue by Superoutman** [ripperhe/Bob#285]
RT，目前输入翻译时需按回车确认，不知可否增加输入实时翻译的功能？
另外，快捷键调出窗口后，再次按此快捷键如果能关闭窗口就更赞了。有时按错键调出窗口后，还得ESC或鼠标点击下才能关闭窗口，稍有不便哈。请大佬酌情考虑🙏

**Comment by wakewon** [comment]
实时翻译不太可行，多次重复请求也会造成不必要的用量消耗（输入一半的内容翻译起来也没有太大的价值）。

再次按同一个快捷键就关闭窗口，感觉不太合适。毕竟，如果有连续多处的识别需求，现在的快捷键设定可以在不关闭窗口的前提下，继续进行下一次识别。如果如你所说，想要开启下一次识别还必须关闭窗口，感觉有点得不偿失了（更何况现在已经有好几种关闭窗口的方式了，而且哪种都不麻烦）。

**Comment by Superoutman** [comment]
> 现在的快捷键设定可以在不关闭窗口的前提下，继续进行下一次识别。

刚发现，原来还有这个功能，看来之前的想法也却有不妥

**Comment by ripperhe** [comment]
你好，由于翻译资源确实比较珍贵，所以此功能就不做了哈，先关闭了
