### ISSUE TITLE
增加查词后收藏单词的快捷键

### ISSUE THREAD

**Issue by fredericky123** [ripperhe/Bob#288]
感谢开发者！
可否增加查词后收藏单词的快捷键

**Comment by fredericky123** [comment]
比如为 option f (favorites)

**Comment by ripperhe** [comment]
@fredericky123 现在就有，command + s

**Comment by fredericky123** [comment]
> @fredericky123 现在就有，command + s

啊，原来如此，感谢！

**Comment by ripperhe** [comment]
不客气 🤝🏾



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fredericky123 ***@***.***&gt;
发送时间: 2022年4月21日 17:12
收件人: ripperhe/Bob ***@***.***&gt;
抄送: Ripper ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ripperhe/Bob] 增加查词后收藏单词的快捷键 (Issue #288)





  
@fredericky123 现在就有，command + s
  
啊，原来如此，感谢！
