### ISSUE TITLE
Bob 能否记录翻译源的折叠状态？

### ISSUE THREAD

**Issue by zhongmuxiao** [ripperhe/Bob#289]
我在翻译中添加了四个翻译 api，这四个翻译源不是同时被需要，有的只是想在主要的翻译源翻译不好的情况下做个参考。

所以，能否记录我对某个翻译源的折叠状态，Bob 自动跳过折叠的翻译接口，而不是每次都一股脑的请求所有的翻译源，这样不仅慢，且没有必要，应该不会有很多人需要同时看四个翻译版本吧。

**Comment by zhongmuxiao** [comment]
最好在每个翻译 API 设置界面，增加一个默认折叠状态的选项。

**Comment by ripperhe** [comment]
新版本加了一个保持翻译服务折叠状态的功能，应该能从一定程度上满足你的需求

**Comment by ripperhe** [comment]
「这样不仅慢，且没有必要，应该不会有很多人需要同时看四个翻译版本吧。」
其实我不太赞同这句话，确实有不少用户就是想对照着看。

**Comment by zhongmuxiao** [comment]
> 新版本加了一个保持翻译服务折叠状态的功能，应该能从一定程度上满足你的需求

已经用上了，感谢

**Comment by zhongmuxiao** [comment]
> 「这样不仅慢，且没有必要，应该不会有很多人需要同时看四个翻译版本吧。」 其实我不太赞同这句话，确实有不少用户就是想对照着看。

用户的需求是多种多样的，确实不能一概而论，谢谢能给出多一个选择

**Comment by ripperhe** [comment]
> 选择

确实是，不客气 🤝🏻
