### ISSUE TITLE
请求在任意界面打开生词本的快捷键

### ISSUE THREAD

**Issue by fredericky123** [ripperhe/Bob#292]
不知可否实现，以便迅速打开生词本进行查阅

**Comment by wakewon** [comment]
右键点击收藏按钮即可。

其实如果是希望学习用途的话，最好的方法还是导出成文件，附加处理后导入专门的词汇学习软件。

**Comment by fredericky123** [comment]
> 
> 其实如果是希望学习用途的话，最好的方法还是导出成文件，附加处理后导入专门的词汇学习软件。

场景是已经收藏了些单词，时不时回顾下，不用专门的去学习，在任意界面直接打开bob的收藏夹用于复习
> 右键点击收藏按钮即可。
我不是想要收藏单词，而是想查阅生词本

**Comment by wakewon** [comment]
> > 其实如果是希望学习用途的话，最好的方法还是导出成文件，附加处理后导入专门的词汇学习软件。
> 
> 场景是已经收藏了些单词，时不时回顾下，不用专门的去学习，在任意界面直接打开bob的收藏夹用于复习
> 
> > 右键点击收藏按钮即可。
> 
> 我不是想要收藏单词，而是想查阅生词本

是的，我其实之前理解了你的意思了。左键点击收藏按钮是收藏当前翻译结果，右键点击收藏按钮就是直接跳转到设置中的收藏列表。你可以试一下。

其实其他按钮有的右键点击时也会跳转到相应的设置页面，你也可以看一看。
