### ISSUE TITLE
建议【OCR窗口位置】多一个选项：【不出现窗口】

### ISSUE THREAD

**Issue by snodr** [ripperhe/Bob#300]
建议【OCR窗口位置】多一个选项：【不出现窗口】。方便扫完可以直接粘贴而不出现窗口打扰。谢谢！
<img width="291" alt="截屏2022-05-08 下午5 33 41" src="https://user-images.githubusercontent.com/81018733/167290334-f9348b1a-fd88-49a9-ba85-8750f9cd0389.png">

**Comment by ripperhe** [comment]
新版本加了一个静默截图 OCR 的功能，可以实现你要的效果
