### ISSUE TITLE
更新至最新版本后服务缺失

### ISSUE THREAD

**Issue by zronghui** [ripperhe/Bob#301]
## 运行环境
* Device: MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
* macOS: 10.14.6
* Bob Version:  0.9.0

## 描述问题

如↓图所示，没有任何内置或私钥服务，之前添加过好几个服务的私钥

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/15062201/167295262-d1fab2e5-70dc-472b-a43e-93ca040bf801.png">

**Comment by ripperhe** [comment]
@zronghui 加我 QQ 453942056，我跟一下这个问题

**Comment by ripperhe** [comment]
经排查，应该是我用了一些新特性导致的，macOS 10.14.6 的用户貌似都有问题，我看看能不能兼容下这个系统版本

**Comment by lee29** [comment]
> 

Mojave状况验证，是的，没有任何服务了～

**Comment by koor** [comment]
10.13 High Sierra也有同样问题

**Comment by leonhart118** [comment]
10.13.6 同样，都不显示了，但不影响使用，怎么办？用旧版本还是等升级？

**Comment by ripperhe** [comment]
0.10.0 应该已经修复了这个问题，麻烦大家更新下
