### ISSUE TITLE
神奇，单翻译一个穷字，会立马闪退

### ISSUE THREAD

**Issue by garrickvan** [ripperhe/Bob#306]
## 运行环境
* Device: A1398 2015 
* macOS: Monterey 12.3.1
* Bob Version: 0.9.0 

## 描述问题

这个Bug是彩蛋吗？刚更新完发现的
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3366781/167782664-6287bdf8-a9ac-4f52-9b33-614ab11354a8.png">
下一步按回车就立马闪退了，其他的单字或长句暂时没发现闪退的问题

**Comment by ripperhe** [comment]
感谢反馈，已知问题，下个版本修复

**Comment by loyio** [comment]
还真是啊，其他都不会闪退。

**Comment by ripperhe** [comment]
已修复，麻烦大家更新下最新版本
