### ISSUE TITLE
识别翻译对Clash for Windows窗口失效

### ISSUE THREAD

**Issue by carpediem-777** [ripperhe/Bob#307]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by carpediem-777** [comment]
在Clash for Windows 客户端的窗口中截图取词翻译时会定位到访达
![image](https://user-images.githubusercontent.com/24445264/167999125-0a2007fd-25d5-451c-8b2c-13d688dafa77.png)

**Comment by ripperhe** [comment]
感谢反馈，麻烦用手机录个视频看一下

**Comment by carpediem-777** [comment]
https://user-images.githubusercontent.com/24445264/168052511-58b3bbf3-aac9-4288-a5af-97c142983706.mp4

**Comment by ripperhe** [comment]
@carpediem-777 我猜测可能是 Clash 的视图层级比 Bob 还高导致的

**Comment by carpediem-777** [comment]
噢，可能是，不过不影响，别的app上还没有出现过这个问题

**Comment by ripperhe** [comment]
好的，后面看下好不好解决

**Comment by ripperhe** [comment]
> > 好的，后面看下好不好解决
> 
> 
> 
> 需要单独为这个app解决吗？感觉蛮小众的，你人也太好了

@dingangui 没有没有，我不是说专门为这个软件解决，只是后面想看下能不能统一处理视图层级问题

**Comment by wakewon** [comment]
未能复现。CFW 版本 0.19.18，Bob 版本 0.10.1，系统 Monterey 12.3.1，Intel

**Comment by aLIEz-xue** [comment]
我这边也是这样，昨天安装 cfw 更新，所以用 bob 翻译了下，然后出现了这个问题，但是问题影响不大

**Comment by aLIEz-xue** [comment]
补充一下，发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达，例如上面视频里 Google 浏览器在 cfw 的下方，测试关闭 Google 浏览器就正常了，复现不限于 Google 浏览器。

**Comment by wakewon** [comment]
> 补充一下，发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达，例如上面视频里 Google 浏览器在 cfw 的下方，测试关闭 Google 浏览器就正常了，复现不限于 Google 浏览器。

我这里来看的话，我的cfw是不会保持在最上层的。对照着前面的视频来说的话，如果开着cfw，然后点击下浏览器，这个时候cfw会直接被盖在后面，而不是依然显示在最上。我不知道cfw有没有设置可以让它界面永远显示在最上层，单从我这里看的话，它是不会显示在最上层的。

在我这里，如果点击了cfw页面（窗口关闭按钮是彩色的），这个时候截图翻译是正常的，跳转访达我这里是可以复现的，但这并没有影响翻译的正常进行，仅仅是把访达叫出来了而已。如果点击了cfw以外的其他软件，cfw直接会被盖在后面看不见，自然截图也就截图不到了。但我确实不知道视频里为何cfw仍然能显示在最前。

（btw，我是直接点击cfw的托盘图标打开的，虽然用spotlight搜出来也一样）

**Comment by aLIEz-xue** [comment]
> 

看半天没懂你想表达什么，跳转访达导致截图翻译窗口一闪而过，为什么不影响它的正常运行。我也没懂你说的“视频里 cfw 为何显示在最前”，明显在 6 秒时他点击了浏览器使浏览器最前，然后在 11 秒时使用聚焦或者其他软件使 cfw 窗口最前，然后因为 cfw 下面有 Google 浏览器的窗口，截图翻译窗口一闪而过，操作没有问题。

https://user-images.githubusercontent.com/59567929/168475406-3159cdba-0dba-48f6-8a50-ab69d879b318.mp4

**Comment by aLIEz-xue** [comment]
> > 补充一下，发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达，例如上面视频里 Google 浏览器在 cfw 的下方，测试关闭 Google 浏览器就正常了，复现不限于 Google 浏览器。
> 
> 我这里来看的话，我的cfw是不会保持在最上层的。对照着前面的视频来说的话，如果开着cfw，然后点击下浏览器，这个时候cfw会直接被盖在后面，而不是依然显示在最上。我不知道cfw有没有设置可以让它界面永远显示在最上层，单从我这里看的话，它是不会显示在最上层的。
> 
> 在我这里，如果点击了cfw页面（窗口关闭按钮是彩色的），这个时候截图翻译是正常的，跳转访达我这里是可以复现的，但这并没有影响翻译的正常进行，仅仅是把访达叫出来了而已。如果点击了cfw以外的其他软件，cfw直接会被盖在后面看不见，自然截图也就截图不到了。但我确实不知道视频里为何cfw仍然能显示在最前。
> 
> （btw，我是直接点击cfw的托盘图标打开的，虽然用spotlight搜出来也一样）

只要 cfw 作为活动窗口（窗口关闭按钮是彩色的），OCR 和截图翻译就一闪而过

https://user-images.githubusercontent.com/59567929/168476402-e8ced1c0-52c2-4ab1-aa10-5c80a06fc123.mp4

**Comment by wakewon** [comment]
> > > 补充一下，发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达，例如上面视频里 Google 浏览器在 cfw 的下方，测试关闭 Google 浏览器就正常了，复现不限于 Google 浏览器。
> > 
> > 
> > 我这里来看的话，我的cfw是不会保持在最上层的。对照着前面的视频来说的话，如果开着cfw，然后点击下浏览器，这个时候cfw会直接被盖在后面，而不是依然显示在最上。我不知道cfw有没有设置可以让它界面永远显示在最上层，单从我这里看的话，它是不会显示在最上层的。
> > 在我这里，如果点击了cfw页面（窗口关闭按钮是彩色的），这个时候截图翻译是正常的，跳转访达我这里是可以复现的，但这并没有影响翻译的正常进行，仅仅是把访达叫出来了而已。如果点击了cfw以外的其他软件，cfw直接会被盖在后面看不见，自然截图也就截图不到了。但我确实不知道视频里为何cfw仍然能显示在最前。
> > （btw，我是直接点击cfw的托盘图标打开的，虽然用spotlight搜出来也一样）
> 
> 只要 cfw 作为活动窗口（窗口关闭按钮是彩色的），OCR 和截图翻译就一闪而过
> 
>  cfw.mp4

突然发现最早的视频看错了，非常抱歉。我又重新尝试了下，现在我成功复现这个问题了。以下是一些补充：

如果 Bob 窗口没有固定在最前，翻译结果窗口就会瞬间消失。如果使用“显示翻译窗口”功能，可以看到翻译结果。

如果 Bob 翻译窗口固定在最前，翻译结果是可以正常显示的，弹出的访达窗口会盖在后面。我的窗口最近都固定在最前了，所以之前的测试中我没有受到这个问题的影响。如果临时需要的话，可以考虑固定 Bob 窗口在最前，或者利用“显示翻译窗口”功能查看结果。OCR 也同理

**Comment by ripperhe** [comment]
没有固定的话，窗口失焦就会自动消失，所以看起来根本问题就是为何 Finder 会出来？

**Comment by wakewon** [comment]
> 我这边也是这样，昨天安装 cfw 更新，所以用 bob 翻译了下，然后出现了这个问题，但是问题影响不大

另外想确认一下，之前有成功识别过 cfw 界面吗？还是说只是因为 cfw 更新了，才想起试一下，之前也没有试过？

我这里把 cfw 回退到 0.19.15，Bob 回退到 0.8.1，这个问题也是依然存在的。我怀疑这个问题很有历史了，只不过一直没人关注。

> 发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达

之前这一点我没能复现。新建了一个桌面，只放了 cfw，在 cfw 是活动窗口时仍然会出现跳访达的问题。我怀疑只与 cfw 是不是活动窗口有关。

**Comment by aLIEz-xue** [comment]
> > 我这边也是这样，昨天安装 cfw 更新，所以用 bob 翻译了下，然后出现了这个问题，但是问题影响不大
> 
> 另外想确认一下，之前有成功识别过 cfw 界面吗？还是说只是因为 cfw 更新了，才想起试一下，之前也没有试过？
> 
> 我这里把 cfw 回退到 0.19.15，Bob 回退到 0.8.1，这个问题也是依然存在的。我怀疑这个问题很有历史了，只不过一直没人关注。
> 
> > 发现单独的 cfw 窗口不会影响 OCR 和翻译，但是一旦 cfw 下面还有窗口，OCR 及翻译都会跳转访达
> 
> 之前这一点我没能复现。新建了一个桌面，只放了 cfw，在 cfw 是活动窗口时仍然会出现跳访达的问题。我怀疑只与 cfw 是不是活动窗口有关。

我发的视频里展示了只有 cfw 窗口但仍出现问题，之前那条回复有问题，没测试完，也没删，刚刚删除了。现在就像你说的，只要 cfw 作为活动窗口就会出现问题。其他暂时没啥补充的。

**Comment by ripperhe** [comment]
1.4.0 版本已修复
