### ISSUE TITLE
Bob 0.10 在 mac12.3.1 下跟快捷指令冲突的问题

### ISSUE THREAD

**Issue by cdk8s-zelda** [ripperhe/Bob#308]
## 运行环境
* macOS: 12.3.1
* Bob Version: 0.10

## 描述问题

- 0.9.0 的版本不会有该问题，目前已经回滚
- 0.10.0 下不管是输入翻译、划词翻译都会报如下图这个错
- 感谢这个软件！

![iShot2022-05-15_01 48 53](https://user-images.githubusercontent.com/51701412/168443114-4bed5512-7ed0-4cf6-89d0-f4e8d155c3ed.png)

**Comment by VidvanTeng** [comment]
我的也是这样，不管设置任何快捷键，截图翻译之后都会提示。
macOS: 12.3.1
Bob Version: 0.10
软件其他方面是很好用的，感谢作者！
<img width="388" alt="iShot_2022-05-15_02 53 45" src="https://user-images.githubusercontent.com/105094687/168444932-ee80e5b7-0450-4fc8-b60e-faed220dcf71.png">

**Comment by ripperhe** [comment]
![Xnip2022-05-15_08-32-32](https://user-images.githubusercontent.com/13943595/168452499-45d2b8fc-31f7-4416-ae95-79dab25d29c5.jpg)

@cdk8s-zelda @VidvanTeng 朋友们，看见我图里框柱的这个服务没？
这是系统的翻译服务，我 0.10.0 集成的，你需要点击蓝色的那个字，进行配置，否则就会报错。
如果不想用，可以去 「Bob 偏好设置 - 翻译 - 服务 - 文本翻译」把这个服务删掉就行啦。

**Comment by ripperhe** [comment]
刚发了一个新版，现在即便不配置系统服务也不会报错了

**Comment by laninblue** [comment]
感谢作者付出，我用了一年多了，非常方便。
0.9的时候一切正常，更新了0.10就跟Hbuilder冲突，只要一运行，Hbuilder就提示插件出错，然后就没法进行代码提示了。
刚刚更新了最新版，仍然是这样，报一样的错误。

**Comment by ripperhe** [comment]
> 

@laninblue 那你把名叫「翻译」这个服务关掉试试？

**Comment by VidvanTeng** [comment]
我收到作者回复信息，按向导配置了文件，没有再报错。后来作者二次信息更新了版本，我更新后同样没有再报错，不过之前配置过的文件也没有再修改。
非常感谢作者，我觉得这个软件比市面上其他翻译平台更轻便好用。

**Comment by cdk8s-zelda** [comment]
> 刚发了一个新版，现在即便不配置系统服务也不会报错了

- 感谢作者，经过测试：0.10.1 已经没问题了。

**Comment by ripperhe** [comment]
> 

感谢支持。
0.10.0 版本加了系统翻译，没有配置会报错。
0.10.1 版本优化点是，如果你没有配置，也不让快捷指令报错。
和你的描述吻合 👌

**Comment by laninblue** [comment]
谢谢，关闭了翻译服务，就不和HBuilder冲突了。

**Comment by ripperhe** [comment]
> 谢谢，关闭了翻译服务，就不和HBuilder冲突了。

好的，不客气 👌

**Comment by wakewon** [comment]
> 谢谢，关闭了翻译服务，就不和HBuilder冲突了。

我这里看的话，在开启了“翻译”服务但没有正确安装相应的快捷指令后，会引发别的软件的玄学问题。但正确安装快捷指令之后就没事了，“翻译”服务也可以正常用。不过我没有条件测试和HBuilder是否情况相同。

当然，直接禁用这个服务也可以避开这个问题。
