### ISSUE TITLE
Bob翻译文本识别服务使用Google OCR后无法识别日语

### ISSUE THREAD

**Issue by vfanghao** [ripperhe/Bob#309]
https://user-images.githubusercontent.com/40256755/168584679-669ec335-6580-4b1f-b04a-b1fd7845f31a.mp4

## 运行环境
* Device: MacBook Pro (13-inch, M1, 2020)
* macOS: 12.3.1 (21E258)
* Bob Version: 0.10.1 [30]

## 描述问题

Bob翻译文本识别服务使用Google OCR后无法识别日语

**Comment by ripperhe** [comment]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/13943595/168585453-1e951342-f0ce-45fe-b8e1-aa83d3fdc3c7.png">
@vfanghao 得把这里选成日语

**Comment by vfanghao** [comment]
@ripperhe 谢谢您，刚把这里修改了一下就好了！！刚开始用有些地方还不是很熟悉请见谅

**Comment by ripperhe** [comment]
> @ripperhe 谢谢您，刚把这里修改了一下就好了！！刚开始用有些地方还不是很熟悉请见谅

不客气 🤝
