### ISSUE TITLE
建议增加PopClip插件

### ISSUE THREAD

**Issue by truebit** [ripperhe/Bob#31]
建议增加PopClip插件，这样划词翻译会方便很多。

**Comment by ripperhe** [comment]
@truebit 你好，现在已经有了哦，你可以看一下 README  的[使用方法](https://github.com/ripperhe/Bob#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

**Comment by truebit** [comment]
抱歉，没看到。
