### ISSUE TITLE
更新版本后0.10.1内置翻译使用不了

### ISSUE THREAD

**Issue by dengshenkk** [ripperhe/Bob#311]
## 运行环境
* Device:  MacBook Pro (Retina, 13-inch, Mid 2021)
* macOS: Monterey 12.3.1 (21E258)
* Bob Version: 0.10.1[30]

## 描述问题

更新完最新的版本`0.10.1[30]`后内置的翻译用不了,是**翻译**,不是百度翻译试用版, 其他使用key的翻译没问题

**Comment by ripperhe** [comment]
@dengshenkk 麻烦截图说明下，最好能有视频

**Comment by dengshenkk** [comment]
![image](https://user-images.githubusercontent.com/28993720/168753825-b67e7b9e-9c98-4ade-a147-1f4fb91c72c0.png)


> @dengshenkk 麻烦截图说明下，最好能有视频

**Comment by ripperhe** [comment]
请问点击那个蓝色按钮「点此查看如何配置」有反应不？

**Comment by dengshenkk** [comment]
> 请问点击那个蓝色按钮「点此查看如何配置」有反应不？

打开了https://ripperhe.gitee.io/bob/#/faq/use-apple-translate 重新添加捷径可以用了. 记得之前不需要做什么操作啊.

**Comment by ripperhe** [comment]
> 

额，之前根本没有「翻译」这个服务啊，新加的功能
