### ISSUE TITLE
使用捷径翻译失败

### ISSUE THREAD

**Issue by hiyangguo** [ripperhe/Bob#313]
## 运行环境
* Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* macOS: 12.3.1 (21E258)
* Bob Version: 0.10.1[30]

## 描述问题

按照说明安装了捷径。调用mac系统的翻译时出错。
<img width="442" alt="image" src="https://user-images.githubusercontent.com/15609339/169092145-ed098972-e6e7-487e-8901-d6807c0d436a.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/15609339/169092180-7a3b9ed0-0b1b-475a-8fd8-b5c07fc8bdb6.png">

**Comment by ripperhe** [comment]
新版本看起来没问题了，先关闭
