### ISSUE TITLE
非英语的OCR截图翻译

### ISSUE THREAD

**Issue by yanull** [ripperhe/Bob#314]
希望Bob可以支持西班牙语、俄语等其他语言的截图翻译

**Comment by ripperhe** [comment]
@yanull 现在是支持的，不过有前提条件：
1. 需要你所使用的「文本识别」和「文本翻译」服务都支持你想要翻译的语言，具体哪个服务支持哪些语言可以在「Bob 偏好设置-翻译-服务」里面查看
2. 最好是把你的源语言选成对应的语言
<img width="446" alt="image" src="https://user-images.githubusercontent.com/13943595/169514521-b0d51252-e468-417e-9f9a-387d28bf7cf6.png">
