### ISSUE TITLE
bob 和wps冲突

### ISSUE THREAD

**Issue by liupeng0518** [ripperhe/Bob#318]
## 运行环境
* Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* macOS:12.3.1 
* Bob Version: 0.10.2

## 描述问题

每次按下按下option+d 唤醒翻译时，wps office就会重启一个wps service。
<img width="627" alt="image" src="https://user-images.githubusercontent.com/7855765/169966238-7bde582a-9cd9-4e57-bc7a-68247d3b820c.png">

**Comment by liupeng0518** [comment]
每按一次，多一个wps office service，更换快捷键也不行

**Comment by ripperhe** [comment]
感谢反馈，我后面查一下

**Comment by ripperhe** [comment]
@liupeng0518 请问使用最新版的 wps 和 Bob 还能复现该问题吗？
我这边不能复现，并且我这边只是模拟 cmd + c 取词，没有额外的操作，大概率是 wps 本身存在一些问题。

**Comment by liupeng0518** [comment]
自从从appstore上下载后就没遇到了，谢谢。
/close

**Comment by ripperhe** [comment]
好的，感谢 🤝
