### ISSUE TITLE
UI界面

### ISSUE THREAD

**Issue by XunDejin** [ripperhe/Bob#32]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Early 2015
* macOS: 10.12.6
* Bob Version: 0.3.0

## 描述问题
您好，UI选择语言这里是红色，很刺眼，希望能够解决或者本地怎么修改
![image](https://user-images.githubusercontent.com/48345592/74601775-a20cda80-50dc-11ea-81ad-9f1cfd824546.png)

**Comment by ripperhe** [comment]
你好，你可以加一下 QQ 群 971584165，然后私聊我一下吗？我晚点给你发个单独的安装包先用着，下个版本修复

**Comment by XunDejin** [comment]
好的，谢谢您
