### ISSUE TITLE
滑词翻译窗口光标位置从右侧开始输入

### ISSUE THREAD

**Issue by Superper** [ripperhe/Bob#320]
## 运行环境
* Device: Mac book pro (retina,14-inch, mid 2021, soc apple m1x)
* macOS: 12.4  
* Bob Version: 0.10.2[32]

## 描述问题

滑词翻译窗口光标位置从右侧开始输入
<img width="404" alt="image" src="https://user-images.githubusercontent.com/35536015/170814229-add5272c-33e9-41e2-9140-7b6d7c028752.png">

**Comment by Superper** [comment]
有的，是使用过程中某次打开突然就跑到了右边，这种状态下伴随了几次闪退，闪退重新打开后依然在右边。
后来电脑重启后正常。

**Comment by ripperhe** [comment]
好的，我后面尝试修复一下。

**Comment by ripperhe** [comment]
@Superper 请问现在还能复现吗？

**Comment by Superper** [comment]
好事是不能，就碰到过那一次，之后更新了版本印象里就没再出现过了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月14日(星期一) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ripperhe/Bob] 滑词翻译窗口光标位置从右侧开始输入 (Issue #320)





 
@Superper 请问现在还能复现吗？

**Comment by ripperhe** [comment]
好的，感谢回复，那这个 issue 先关闭了，我这边未能复现，也未找到可疑代码。
如果你还遇到问题，能复现的话，直接加我 QQ 453942056，我这边跟进下。
