### ISSUE TITLE
可以增加在已打开输入窗口的情况下使用相同的快捷键关闭翻译窗口的功能吗？

### ISSUE THREAD

**Issue by yifan0414** [ripperhe/Bob#321]
在使用过程中，常常会使用快捷键打开翻译窗口，然后查找一个单词或一个段落意思。然后关闭的时候返回原来的编辑框的时候只能使用⎋esc 键。
所以可以增加第二次使用快捷键（比如打开输入窗口）的作用是关闭输入窗口呢？这样也符合大部分快捷键的使用逻辑

**Comment by ripperhe** [comment]
也可以用 `Command + W`

**Comment by SnakeHit** [comment]
之前使用的有道词典和欧路词典都实现了这个功能，可能是我使用习惯了😂。

**Comment by ripperhe** [comment]
理解，我考虑考虑吧
