### ISSUE TITLE
是否可以增加音标

### ISSUE THREAD

**Issue by angiie** [ripperhe/Bob#325]
是否可以增加 音标 ，虽然说我并不是学生，很多时候确实也没办法的声音。

**Comment by ripperhe** [comment]
参考这个 https://ripperhe.gitee.io/bob/#/faq/translate-show-dict

**Comment by XZYW** [comment]
用有道翻译的接口就行，但是只能显示，点击播放有点问题

**Comment by ripperhe** [comment]
@XZYW 有道的播放，巨大多数是没问题的，只有极少部分有问题。
如果全部都不能播放，很可能是申请有道秘钥没有绑定语音合成实例。
参考文档：https://ripperhe.gitee.io/bob/#/service/translate/youdao

**Comment by angiie** [comment]
> 用有道翻译的接口就行，但是只能显示，点击播放有点问题

额，还没用过有道的翻译，改天试试看。

**Comment by Superoutman** [comment]
用翻译服务倒是可以解决。不过为了音标，要另占窗口的高度，稍有牺牲。

**Comment by ripperhe** [comment]
@Superoutman 如果不用翻译的话，期望的效果大概是怎么样？

**Comment by Eric-Hsieh97** [comment]
非常非常需要音标这个功能，不管是present还是report

**Comment by ripperhe** [comment]
目前确实只有这个方案显示音标 https://bobtranslate.com/faq/translate-show-dict.html
