### ISSUE TITLE
英汉词典资源包下不下来，能否自己下载，复制到指定位置

### ISSUE THREAD

**Issue by guo-xun** [ripperhe/Bob#326]
服务->文本翻译->简明英汉词典配置
点击下载，一直下载失败，能否自己下载资源，放在指定位置，谢谢。
<img width="1000" alt="图片" src="https://user-images.githubusercontent.com/44690875/172112943-3140331d-266a-47a9-843b-20d665cd64d8.png">

**Comment by ripperhe** [comment]
@guo-xun 抱歉，一直很忙，没来得及写文章，请参考这篇文章 https://bobtranslate.com/faq/ecdict-download-fail.html
