### ISSUE TITLE
开机自启勾选了，但不自启

### ISSUE THREAD

**Issue by ltcooooooo** [ripperhe/Bob#328]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ltcooooooo** [comment]
开机不不会自启

**Comment by ripperhe** [comment]
1. 你是否在 系统偏好设置 》 用户与群组 》登录项 里面添加了 Bob，如果添加了，请将其删除。
2. 此外，勾选上 Bob 偏好设置 》通用设置里面的 开机自启动。
3. 如果两个都做了，还是不行；那就等我更新吧，后面我会调整自启动方案，应该就没问题了。

**Comment by ltcooooooo** [comment]
> 1. 你是否在项目系统首选项设置》用户与其他人一起在里面添加了 Bob，如果添加删除其登录。
> 2. 此外，勾选上 Bob 首选项设置》通用设置里面的自启动启动。
> 3. 如果都做了，还是不行；那就等更新吧，接下来我会调整自启动方案，我想我会有问题。

感谢作者回复，用户群组里面删除之后，问题解决了。当时勾选上是试图解决

**Comment by ripperhe** [comment]
好的 🤝
