### ISSUE TITLE
添加免费的微软语音合成支持

### ISSUE THREAD

**Issue by XYZliang** [ripperhe/Bob#330]
[微软语音合成](https://azure.microsoft.com/zh-cn/free/cognitive-services/)完全免费，无需科学上网和开通Azure，测试的窗口应该是可以提取出api的（吾爱论坛已经有提取版app），合成的声音非常自然，很多抖音解说就是这个声音！

**Comment by zouchao** [comment]
1 人血书

**Comment by XYZliang** [comment]
edge也有tts引擎，github上有不少提取版使之单独在Windows和安卓上使用，可以参考下

**Comment by ripperhe** [comment]
Bob 内部已经集成微软语音合成服务，可升级到最新版使用
