### ISSUE TITLE
升级macOS Ventura 13.0 Beta后，英文朗读出现问题

### ISSUE THREAD

**Issue by asfdchen** [ripperhe/Bob#331]
## 运行环境
* Device: MacBook M1 Pro (14-inch, 2021)
* macOS: Ventura 13.0 Beta
* Bob Version: 0.10.2

## 描述问题
升级macOS Ventura 13.0 Beta后，点击小喇叭英文朗读出现问题，空洞诡异的声音

**Comment by Albert-Qiguan** [comment]
试试在Bob-设置-翻译-服务-语音合成-离线语音合成-选择声音里更改一下英文声音选项？在 macOS 13下Bob默认好像会选择字母表顺序第一个的语音，也就是那个Albert，是一个空洞的老人的声音感觉，改回默认的Samantha应该就好了
<img width="1003" alt="截屏2022-06-27 下午6 27 58" src="https://user-images.githubusercontent.com/64722222/176038600-0a1794f8-685a-47a6-a576-dd75b2c2be90.png">
