### ISSUE TITLE
源于语言检测异常

### ISSUE THREAD

**Issue by XYZliang** [ripperhe/Bob#336]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, 2019)
* macOS: 13.0beta
* Bob Version: laster

## 描述问题
如图，当我尝试翻译以下文字，bob将原语言识别为了德语
`感谢你们的帮助和Jamie Eisenreich的解决方案
我已经在测试版系统上成功安装了Logitech Options+。
按照类似的思路我查看了LogiOptions的安装包内容，我发现在LogiMgr Installer.app/Contents/Resources下有一个LogiMgr.pkg，直接打开就能正常安装，现在我已经成功安装Logitech Options+和LogiOptions。`
<img width="436" alt="image" src="https://user-images.githubusercontent.com/59312540/174705432-8c3b4c95-261a-4c1f-9894-de88b503c7d6.png">

**Comment by ripperhe** [comment]
我试了下，确实有问题。这个语言识别的模型确实有些 bad case，不过暂时没法处理，只能手动切换一下。
