### ISSUE TITLE
能加个设置不输出日志文件么？

### ISSUE THREAD

**Issue by EXHades** [ripperhe/Bob#338]
`~/Library/Application\ Support/com.ripperhe.Bob/VirtualSandbox/Library/Caches/MMKit/MMLogs/Default`  
下的日志记录好像有点多。。。
<img width="981" alt="image" src="https://user-images.githubusercontent.com/22260242/176173826-d35f277b-0818-435d-b97b-9d7bf3fee650.png">

**Comment by ripperhe** [comment]
你好，暂时不会，因为整体的磁盘占用不会太多，主要方便解决问题

**Comment by EXHades** [comment]
在 v2ex 看到上架 AppStore，第一时间购买支持了。。。
<img width="363" alt="image" src="https://user-images.githubusercontent.com/22260242/177524332-90b5f82e-e202-4645-8b0f-524055ec6903.png">

作者有空的话希望加个日志记录开关吧。。要 debug 时再开就好了，主要是里面记录的太详细了，有点怕

**Comment by EXHades** [comment]
主要是有时候翻译一些比较敏感的信息。。不希望有记录

**Comment by Achieve777** [comment]
+1
希望有个开关能够控制是否写日志

**Comment by ripperhe** [comment]
@EXHades @Achieve777 好的，我后续加一下吧

**Comment by ripperhe** [comment]
@EXHades @Achieve777 1.1.0 版本已添加，忘了给你们同步

<img width="450" alt="image" src="https://user-images.githubusercontent.com/13943595/182530136-e2a6b914-4ca3-48f1-a4e2-7b92bfd4bbe0.png">
