### ISSUE TITLE
请问何时可以支持deepl的api以及开一个telegram群

### ISSUE THREAD

**Issue by CaiPeterCai** [ripperhe/Bob#339]
https://www.deepl.com/zh/pro-api

**Comment by CaiPeterCai** [comment]
在App Store上同时买了Bob和Popclip搭配使用感觉很爽

**Comment by CaiPeterCai** [comment]
还有你在
https://bobtranslate.com/guide/quickstart/translate.html
这个页面的Popclip的教程地址少了.html
正确地址应该是
https://bobtranslate.com/guide/integration/popclip.html

**Comment by ripperhe** [comment]
> 还有你在 https://bobtranslate.com/guide/quickstart/translate.html 这个页面的Popclip的教程地址少了.html 正确地址应该是 https://bobtranslate.com/guide/integration/popclip.html

感谢提醒，刚刚修复了

**Comment by ripperhe** [comment]
> 在App Store上同时买了Bob和Popclip搭配使用感觉很爽

感谢支持啊，那相当于我还帮 PopClip 打了一波广告，哈哈哈

**Comment by ripperhe** [comment]
> https://www.deepl.com/zh/pro-api

deepl 其实添加不麻烦，我后面看看。之前是因为有的开发者加了 deepl api 被要求去掉，而且申请也麻烦，所以我一直没加。

**Comment by CaiPeterCai** [comment]
> > https://www.deepl.com/zh/pro-api
> 
> deepl 其实添加不麻烦，我后面看看。之前是因为有的开发者加了 deepl api 被要求去掉，而且申请也麻烦，所以我一直没加。

好吧，我暂时用的v2ex的热心朋友推荐的插件来解决的😄
https://github.com/geekdada/bob-plugin-deepl-translate
