### ISSUE TITLE
无法添加屏幕录制的权限

### ISSUE THREAD

**Issue by kagwind** [ripperhe/Bob#340]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Mid 2020, Intel)
* macOS:  10.15.7
* Bob Version:1.0.0 [45]

## 描述问题
隐私选项里无法添加屏幕录制的权限。
已尝试以下操作：
1. 按照app提示解锁后将app icon拖至屏幕录制权限右侧的列表。 结果：无任何效果。
2. 运行 'tccutil reset ScreenCapture com.hezongyidev.Bob' 后重启电脑，执行Bob的截图操作。 结果：列表中仍然不出现Bob的图标。
3. 执行 2 后再执行 1。 结果：无任何效果。

**Comment by ripperhe** [comment]
@kagwind 抱歉，这个在 10.15 系统确实有问题，昨天已经修改了，预计今天会提到 App Store 审核

**Comment by kagwind** [comment]
刷了一天App Store，新版本还没上架。
有点想买，但是还是想先试用一下。

**Comment by ripperhe** [comment]
@kagwind 我等下提，不过审核需要时间，速度快的话，明天能过，到时候通知你

**Comment by kagwind** [comment]
Bob 1.0.0 [46] 应该解决了。
