### ISSUE TITLE
Bob能否提供一下更换App图标的选项?

### ISSUE THREAD

**Issue by code4you2021** [ripperhe/Bob#345]
Bob是一个很棒的App，每天工作和小孩看英语新闻起到很大的作用，非常感谢开发者制作了这么好用的一款App。

希望开发者提供一下更换App图标的选项，目前这个图标看着太有个性了
能否提供一个选项，让用户更换它。

**Comment by zhucp18** [comment]
macOS的话可以试试自行更换APP的图标
https://macosicons.com/how-to#/how-to

**Comment by zhucp18** [comment]
@code4you2021

**Comment by ripperhe** [comment]
@code4you2021 我也建议自行更换，可以参考 @zhucp18 的建议，macOS App 内部不支持更换 App 图标
