### ISSUE TITLE
多次翻译，捷径报错，无法翻译

### ISSUE THREAD

**Issue by liuliangyz** [ripperhe/Bob#346]
## 运行环境
* Device: MacBook Pro m1 13
* macOS: 12.4
* Bob Version: 1【45】

## 描述问题
多次翻译，捷径提示报错。
![iShot_2022-07-06_15 40 01](https://user-images.githubusercontent.com/14066306/177497887-44e35bbb-9e21-465b-bbbc-2aa88f490ee4.png)

**Comment by ripperhe** [comment]
@liuliangyz 通过捷径调用系统翻译是个实验性功能，确实不稳定，主要是 Apple 的快捷指令本身不太稳定，Bob 无法控制。
遇到这种情况可以尝试重新安装一下这个快捷指令，如果不行的话， 我这边也没有什么太好的办法。

**Comment by ripperhe** [comment]
@liuliangyz 目前发现是网络代理或者抓包工具的问题，关闭掉应该就行了
