### ISSUE TITLE
增加 腾讯翻译 的支持选项

### ISSUE THREAD

**Issue by sbilly** [ripperhe/Bob#35]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, Mid 2014)
* macOS: 10.15.3
* Bob Version: 0.3.0

## 请描述你的建议

微信的翻译效果不错，腾讯也提供了免费的翻译 API（ https://cloud.tencent.com/document/product/551 ），希望增加 腾讯翻译 的支持选项。

**Comment by ripperhe** [comment]
好的，后面会加上

**Comment by ripperhe** [comment]
0.5.2 版本已支持腾讯翻译
