### ISSUE TITLE
能否给「历史记录」一个快捷入口或快捷键？

### ISSUE THREAD

**Issue by Yorkun** [ripperhe/Bob#352]
**能否给「历史记录」一个快捷入口或快捷键？**
「历史记录」对于我算是高频操作，目前只能在「偏好设置」里查看，有点不方便。

**Comment by ripperhe** [comment]
@Yorkun 后续会考虑一下

**Comment by tisfeng** [comment]
需要～

**Comment by ripperhe** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/13943595/205323672-0eb03d9c-9290-423f-add2-698699da99a1.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/13943595/205323740-a0f6e63e-0e7c-41ae-a52a-0a6998604b57.png">
各位，1.4.0 版本加了一个按钮，可以快捷跳转到历史记录
