### ISSUE TITLE
同時翻譯繁體中文和簡體中文

### ISSUE THREAD

**Issue by mejona** [ripperhe/Bob#353]
希望能**同時翻譯繁體中文和簡體中文**。因為有時簡體的翻譯品質較好，有時繁體的較好，如果能同時顯示兩者，相信會方便不少，謝謝！

理想的介面是長這樣：
（原文）英文
（譯文）macOS內建的**繁體**
（譯文）macOS內建的**簡體**
（譯文）有道翻譯的**簡體**

**Comment by ripperhe** [comment]
@mejona 感谢反馈，暂时不会考虑做得这么复杂
