### ISSUE TITLE
商店版OCR功能提取出的文字不能划词翻译

### ISSUE THREAD

**Issue by acocoadog** [ripperhe/Bob#354]
## 运行环境
* Device: MacBook Air (M1, 2020)
* macOS:12.4 
* Bob Version: 1.0.1

## 描述问题

如题，显示划词翻译没有获取到文本
社区本则没有此问题

**Comment by ripperhe** [comment]
@acocoadog 请具体描述下在哪些软件下使用不能划词？有没有可以划词的？

**Comment by acocoadog** [comment]
所有软件下都存在这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zongyi ***@***.***&gt;
发送时间: 2022年7月18日 09:35
收件人: ripperhe/Bob ***@***.***&gt;
抄送: acocoadog ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ripperhe/Bob] 商店版OCR功能提取出的文字不能划词翻译 (Issue #354)





 
@acocoadog 请具体描述下在哪些软件下使用不能划词？有没有可以划词的？

**Comment by ripperhe** [comment]
@acocoadog 好的，了解了。刚开始理解成了不能划词翻译，原来是不能划词翻译 Bob 的 OCR 窗口。

**Comment by acocoadog** [comment]
是在Bob的OCR界面直接对识别结果不能划词翻译
之前的社区版是可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zongyi ***@***.***&gt;
发送时间: 2022年7月18日 09:35
收件人: ripperhe/Bob ***@***.***&gt;
抄送: acocoadog ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ripperhe/Bob] 商店版OCR功能提取出的文字不能划词翻译 (Issue #354)





 
@acocoadog 请具体描述下在哪些软件下使用不能划词？有没有可以划词的？

**Comment by acocoadog** [comment]
请问这个问题还有修复的可能吗
或者在OCR识别界面加一个一键翻译的功能也行🤣
我录了一个视频展示这个问题

https://user-images.githubusercontent.com/109275092/200466374-a1fefb46-4217-483f-9c07-0be6e6e2b0d7.mp4

**Comment by ripperhe** [comment]
@acocoadog 你好，要修复的，之前有其他计划，还没来得及，接下来这个版本会集中处理下客诉

**Comment by acocoadog** [comment]
好的好的，辛苦你们了🥳

**Comment by ripperhe** [comment]
碍于沙盒 App 的问题，确实无法解决划词问题。
不过 1.4.0 版本在 OCR 窗口加了「翻译」按钮，点击之后会跳转到翻译窗口，也算是解决了吧，先这样啦 🤝
