### ISSUE TITLE
窗口位置希望加上上次的位置.

### ISSUE THREAD

**Issue by hlgithub369** [ripperhe/Bob#355]
每次拖开位置后再次翻译又会跑到中间挡着
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/15081751/178941234-5e4deaf7-e697-42f5-ba98-18802facb0d5.png">

**Comment by ripperhe** [comment]
@hlgithub369 后面考虑下

**Comment by h4rk8s** [comment]
> @hlgithub369 后面考虑下

这个功能的场景，主要是分屏后的位置记忆，本来想提issue，搜了一下“位置”关键字，发现了这个issue， +1

**Comment by ripperhe** [comment]
1.4.0 版本已添加上次位置

**Comment by hlgithub369** [comment]
> 1.4.0 版本已添加上次位置
谢谢.
