### ISSUE TITLE
Bob会造成全局键盘输入无响应的问题

### ISSUE THREAD

**Issue by Bolvvv** [ripperhe/Bob#356]
## 运行环境
* Device: MacBook Air M1
* macOS: 12.4
* Bob Version: 1.0.1[46]

## 描述问题

在使用聚焦搜索时，使用快捷键（option+a）唤醒Bob进行输入翻译时，会出现全局键盘输入无响应的问题。

具体复现步骤：
1. command+space 唤醒聚焦搜索
2. option+a 唤醒Bob搜索
3. 点击屏幕中其他任意位置（此时bob编辑框和聚焦搜索框都会消失），键盘输入变得无响应

我的mac上还安装了bartender 4，不清楚这个软件是否会造成影响。

**Comment by ripperhe** [comment]
@Bolvvv 我这边可以复现，后续看下如何解决

**Comment by Bolvvv** [comment]
这是来自QQ邮箱的自动回复邮件。
 
你好，我已收到你的邮件，会及时进行回复，谢谢。

**Comment by ripperhe** [comment]
@Bolvvv 我研究了一下，目前没找到规避的方案，主要是我这边确实没有做什么额外的操作。

另外，我测试了一下，把 Bob 替换成 Alfred 等一系列这种悬浮式的 App 都会有这个问题，但是如果 Bob 和 Alfred 等 App 交叉是没有问题的，所以很可能是聚焦搜索本身的 BUG，暂时不打算解决了。

实在出现这种情况之后，貌似重新启动一个有输入框的软件就可以破除了。
