### ISSUE TITLE
用了自定义的ssl证书后 不能使用自带的翻译了

### ISSUE THREAD

**Issue by dengshenkk** [ripperhe/Bob#358]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Mid 2020)
* macOS: 12.3.1 
* Bob Version: 0.10.2

## 描述问题

使用charles等抓包调试工具后(已经在钥匙串中始终信任, 可以正常抓包https), 自带的翻译功能一直提示证书异常, 也没办法在bob中手动信任证书, 提供以下截图. 希望能提供一个解决方法.谢谢
<img width="400" alt="image" src="https://user-images.githubusercontent.com/28993720/179176230-ed40b92f-f7d1-4f48-9b54-6f383cf17046.png">

**Comment by ripperhe** [comment]
@dengshenkk 「翻译」是 Apple 内部发的请求，我这边处理不了

**Comment by ripperhe** [comment]
@dengshenkk 考虑下能否将 `sequoia.apple.com` 这个域名绕过抓包。
可以参考下这个 issue #405
