### ISSUE TITLE
是否应该保存一份完整的log帮助排查问题

### ISSUE THREAD

**Issue by chinaboard** [ripperhe/Bob#359]
目前log只有在导出日志的时候才有，其实会缺失非常多的信息，应该是有个常态化的log，按日志大小或天进行rotation

**Comment by ripperhe** [comment]
@chinaboard 感谢建议，不过导出的其实就是完整的啊，持久化到本地的。。。

**Comment by abisuq** [comment]
修下闪退的问题吧。心态爆炸了。
