### ISSUE TITLE
目前是商店版用户，请问作者可否加入字节跳动旗下的火山翻译

### ISSUE THREAD

**Issue by macchen123** [ripperhe/Bob#361]
感觉火山翻译引擎目前在学术论文翻译这块儿效果比其他平台好一些，请问作者可否抽空开发一下相关插件

**Comment by ripperhe** [comment]
有用户开发了火山引擎 Bob 插件，你可以先用着
https://github.com/maybeLab/bob-plugin-volc/releases

后续我看下要不要集成

**Comment by macchen123** [comment]
好的，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zongyi ***@***.***&gt;
发送时间: 2022年7月20日 12:06
收件人: ripperhe/Bob ***@***.***&gt;
抄送: macchen123 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ripperhe/Bob] 目前是商店版用户，请问作者可否加入字节跳动旗下的火山翻译 (Issue #361)





 
有用户开发了火山引擎 Bob 插件，你可以先用着
 https://github.com/maybeLab/bob-plugin-volc/releases
 
后续我看下要不要集成

**Comment by ripperhe** [comment]
你好，1.2.0 版本已加入，请将 Bob 升级到最新版

**Comment by macchen123** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zongyi ***@***.***&gt;
发送时间: 2022年9月19日 17:18
收件人: ripperhe/Bob ***@***.***&gt;
抄送: macchen123 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ripperhe/Bob] 目前是商店版用户，请问作者可否加入字节跳动旗下的火山翻译 (Issue #361)





 
你好，1.2.0 版本已加入，请将 Bob 升级到最新版
