### ISSUE TITLE
无法翻译 一直显示无法翻译 尝试了任何语句

### ISSUE THREAD

**Issue by michelledxt** [ripperhe/Bob#362]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
看不到图片呢，图片是不是发送失败了？

**Comment by ripperhe** [comment]
不好意思，我还是看不到图片哈，你可以自己在这个网站来看看
https://github.com/ripperhe/Bob/issues/362

**Comment by michelledxt** [comment]
请问这样可以看见吗

**Comment by ripperhe** [comment]
不可以，图片没上传成功，你多等一会儿

**Comment by michelledxt** [comment]
<img width="885" alt="截屏2022-07-20 下午9 34 23" src="https://user-images.githubusercontent.com/109670876/179986598-823d0070-d4ab-4599-bf9b-d6a7a7514e40.png">

**Comment by michelledxt** [comment]
现在呢

**Comment by ripperhe** [comment]
现在可以了，已经看到了。我给你解释下哈。

百度翻译试用版，就是试用的，用不了你去点那个「点此查看解决方案」进去看，或者直接进这个链接也行 https://bobtranslate.com/faq/translate-fail.html
看完你就知道啥意思了，都在这个文章里面。

然后金山词霸是个词典呀，只支持中英文查词，不支持翻译句子的。

**Comment by michelledxt** [comment]
意思是除了pro之外 我还需要购买一个私人秘钥对吗

**Comment by ripperhe** [comment]
是的，不过私人秘钥一般不需要购买，申请就行了，每个月基本都有免费额度，你认真研究下这篇文章
https://bobtranslate.com/guide/advance/service.html

**Comment by ripperhe** [comment]
不是回复过一遍了吗？

是的，不过私人秘钥一般不需要购买，申请就行了，每个月基本都有免费额度，你认真研究下这篇文章
https://bobtranslate.com/guide/advance/service.html
