### ISSUE TITLE
能否添加去除翻译原文中 「-空格」 的功能

### ISSUE THREAD

**Issue by deng-zian** [ripperhe/Bob#364]
翻译论文时经常会遇到英文单词换行被断开，直接用Bob翻译时会出现下面的情况👇
A new framework is introduced to address in a **uni- fied** way the consensus of multiagent systems and the **synchroniza- tion** of complex networks.
能否在偏好设置->翻译处理->文本处理的模块中，添加将翻译原文中 「-空格」 去掉的功能

**Comment by deng-zian** [comment]
<img width="1063" alt="截屏2022-07-23 10 11 48" src="https://user-images.githubusercontent.com/96040155/180586614-4e375124-2e04-4aff-8da1-04f55cfc99a2.png">
付费版推出第一时间已经支持

**Comment by ripperhe** [comment]
你好，感谢支持。现在是会处理有连字符并且有换行的情况的，例如：

```
what are you do-
ing?
```

会处理成

```
what are you doing?
```

你指的是没有换行的情况吗？

**Comment by deng-zian** [comment]
你好，我在设置中开启了将换行符替换为空格
<img width="564" alt="截屏2022-07-25 14 23 50" src="https://user-images.githubusercontent.com/96040155/180711791-47eb01b5-1408-41da-8a17-a5d70608f168.png">
但是翻译的时候貌似只会将
```
with a time-invariant communication topology con-
sisting of general linear node dynamics. 
```
处理成
```
with a time-invariant communication topology con- sisting of general linear node dynamics. 
```
下面是我在实际翻译中的截图
<img width="556" alt="截屏2022-07-25 14 22 44" src="https://user-images.githubusercontent.com/96040155/180713608-7999200f-5fd2-46e3-b895-9b2374cebc2a.png">

**Comment by ripperhe** [comment]
我直接在当前网页划词翻译你这段话是可以合并的，你试试呢？
是不是 PDF 软件的问题？用的什么 PDF 软件？

**Comment by deng-zian** [comment]
网页中的我试了下，确实可以。我一般用系统自带的预览看PDF，普遍会出现这样的问题。我又试了不同的软件，发现确实会和使用的软件有关。我尝试用不同软件打开同一个PDF然后翻译，结果如下
- 预览会出现问题
<img width="823" alt="截屏2022-07-25 22 06 14" src="https://user-images.githubusercontent.com/96040155/180797533-479d00b0-cac6-406a-bec0-4cc6cc82949b.png">

- Safari打开会出现问题
<img width="627" alt="截屏2022-07-25 22 06 50" src="https://user-images.githubusercontent.com/96040155/180797627-da95e53c-a903-4ddc-b3ee-f377c81e2925.png">

- Chrome打开 没有问题
<img width="628" alt="截屏2022-07-25 22 05 41" src="https://user-images.githubusercontent.com/96040155/180797806-a4bdfa93-828a-4289-826f-d84c47073feb.png">

- PDF Expert 批注模式没有问题
<img width="592" alt="截屏2022-07-25 22 07 28" src="https://user-images.githubusercontent.com/96040155/180797910-5d75350d-441c-4523-8885-33e4d05884ff.png">

- PDF Expert 编辑模式有问题
<img width="609" alt="截屏2022-07-25 22 07 51" src="https://user-images.githubusercontent.com/96040155/180797953-f8f3dd78-3a80-486f-baa7-147b7681e4cd.png">

具体技术原因我不太清楚，请问是否有办法能让处理英文单词换行断开的功能普遍适用于所有pdf软件呢

**Comment by ripperhe** [comment]
感谢测试得这么详细，我怀疑是每个软件换行的标识符不太一样，麻烦你通过 Bob 菜单栏图标 》更多 》导出日志，发送到 <bobtranslate@qq.com>，我后面看一下

**Comment by deng-zian** [comment]
已发送，请查收

**Comment by ripperhe** [comment]
好的，已收到

**Comment by ripperhe** [comment]
@deng-zian 朋友，这个问题了查了一下，大概是这个原因。

有问题的那几种 Case，在复制的时候，那个软件把本身是两行的文本，合并成了一行，比如你看到的是如下所示：

```
insignif-
icant details
```

当时当你按下 cmd + c 复制之后，复制到剪切板的却是这样：

```
insignif- icant details
```

也就是说，Bob 获取到文本的时候，它就是「一行」，所以无法处理。Bob 目前只会处理两行文本，并且前一行文本末尾有连字符 `-` 的情况，「- 空格」的情况却是不会处理。

没有问题的那几种 Case，在复制之后，确实也还是两行。

**Comment by ripperhe** [comment]
直接暴力地将「-空格」的情况拼接起来，可能会引发一些意想不到的问题，所以我在考虑是否需要加一个偏好设置。

**Comment by deng-zian** [comment]
感谢回复，幸苦了。我感觉通过增加一个快捷键，或是一个按钮来处理这个问题是个好方法。当用户碰到句子中含有「- 空格」的情况时，按下快捷键或是按钮，软件便将句子中的「- 空格」去除（当然也可以再按下恢复原句）。这样就可以把判断句子中出现「- 空格」是何种情况的任务交给了用户，避免了直接暴力地将「-空格」的情况拼接起来可能引发的问题。

**Comment by ripperhe** [comment]
嗯嗯，我可能会像去除换行那样，放在翻译窗口右上角的设置里面，另外现在点击那个位置的选项后并没有刷新输入框，后面会优化下

**Comment by ripperhe** [comment]
你好，1.4.0 版本已添加上去掉「- 空格」的选项

**Comment by deng-zian** [comment]
感谢🙏发自我的 iPhone在 2022年12月2日，23:03，zongyi ***@***.***> 写道：﻿
你好，1.4.0 版本已添加上去掉「- 空格」的选项
