### ISSUE TITLE
请问下 50RMB 买断是只限制一台设备，还是与AppStore账户一起的？

### ISSUE THREAD

**Issue by nisiyong** [ripperhe/Bob#365]
## 描述问题

请问下 50RMB 买断是只限制一台设备，还是与AppStore一起的？

**Comment by ripperhe** [comment]
你好，是跟随 Apple ID 的，只要你登录相同的账号，然后在 Bob 点击「恢复购买」即可。

**Comment by nisiyong** [comment]
@ripperhe 好的，非常感谢！好产品得支持下
