### ISSUE TITLE
内存异常

### ISSUE THREAD

**Issue by harisonkhlil** [ripperhe/Bob#368]
## 运行环境
macOS 12.5 21G72 arm64
bob 商店最新版最新版

## 描述问题

<img width="615" alt="image" src="https://user-images.githubusercontent.com/70578017/181902735-0be87255-313a-4b41-a9a9-b498b16bca92.png">
这些玩意是啥呀，怎么这么大？

**Comment by ripperhe** [comment]
是不是下载了简明英汉词典

**Comment by harisonkhlil** [comment]
是的，但是简明词典也不大呀

**Comment by ripperhe** [comment]
就是这么大

**Comment by harisonkhlil** [comment]
不是只有200多m吗？

**Comment by ripperhe** [comment]
哦，那是压缩包的大小，解压之后更大
