### ISSUE TITLE
商店版显示“账户余额不足，请前往管理控制台为账户充值”

### ISSUE THREAD

**Issue by SW577** [ripperhe/Bob#371]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
@SW577 
百度翻译官方近期发布了通知，2022 年 8 月 1 日起下调翻译服务的免费调用量。
超出之后百度会自动扣费，大家留意一下！
详情看这篇文章：https://bobtranslate.com/blog/2022-07-16-baidu-change.html
