### ISSUE TITLE
AppleScript 应该如何调用 Bob的OCR功能？

### ISSUE THREAD

**Issue by stardiviner** [ripperhe/Bob#373]
Bob 的翻译功能可以通过AppleScript调用： https://v0.bobtranslate.com/#/general/integration/applescript
我想调用OCR功能应该如何调用呢？感谢问答。

**Comment by ripperhe** [comment]
@stardiviner 你好，暂时没有调用方法

**Comment by stardiviner** [comment]
会否在将来的版本中加入这个支持？

**Comment by ripperhe** [comment]
这个可以加的，麻烦你描述一下具体的使用场景

**Comment by stardiviner** [comment]
感谢你的支持。

我是在 [Emacs](https://en.wikipedia.org/wiki/Emacs) 里加入调用 macOS系统 AppleScript代码来调用Bob的翻译功能，从而实现在Emacs里支持Bob来翻译内容的。我写了一个Emacs插件： https://repo.or.cz/external-dict.el.git

如果可以的话，希望Bob能给现有的命令都加入AppleScript命令支持。因为Emacs要调用Bob无法像Linux下通过命令行来调用，所以想到这个办法。
我知道这个可能是一个小众的场景，不过还是希望在不是工作量麻烦的情况下，能够被支持。
最后感谢你们这么赞的软件，自定义支持做的非常好。

**Comment by stardiviner** [comment]
非常感谢🙏。哈哈哈，终于用上新功能了。感谢大佬的开发。
