### ISSUE TITLE
mac自带翻译提示翻译“频率过快，请稍后再试”

### ISSUE THREAD

**Issue by hellojaven** [ripperhe/Bob#374]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题
mac自带翻译提示翻译“频率过快，请稍后再试”，可是我才第二次使用啊，之前这个功能一直正常。请问这个怎么解决？

<img width="416" alt="image" src="https://user-images.githubusercontent.com/20969233/183422442-baf8cdba-1e69-44c1-b8b6-153bf8c2f787.png">

**Comment by ripperhe** [comment]
@hellojaven 你好，这是系统问题，麻烦重启电脑试试
