### ISSUE TITLE
自动检测语言功能BUG：中英文识别为意大利语

### ISSUE THREAD

**Issue by JimmyLX** [ripperhe/Bob#376]
## 运行环境
* Device: MacBook Pro (15-inch, 2017)
* macOS: 12.5
* Bob Version: 1.1.0[60]

## 描述问题

自动检测文字（是否登出当前 Facebook账号），偶尔会检测为意大利语或其他错误的语言（如下图，用了两个月，出现过两三次），无法正常翻译，需要手动选择为简体中文。
![iShot_2022-08-11_10 12 34](https://user-images.githubusercontent.com/20757519/184055067-e092cae9-ef20-4174-9c42-29dc7389e9ba.png)

**Comment by ripperhe** [comment]
你好，感谢反馈。
在某些情况下，确实会有问题，主要还是限于当前的语言识别模型，做不到绝对准确。
目前只有一个降阶方案，就是点一下「识别 xxx」那个按钮，切换一下语言，这样可以指定本次的语言。
