### ISSUE TITLE
我用的翻译和OCR都是自己申请来的？为什么要限制使用次数？

### ISSUE THREAD

**Issue by FakeNewsNextOne** [ripperhe/Bob#377]
## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
😢 大兄弟，我开发维护要花时间的啊...
购买 Pro 的费用是用于我对这个软件本身的开发、维护、写文档、以及处理客诉的时间成本，比如现在。
