### ISSUE TITLE
语言选取栏中拉丁语“Latin”的中文标成了“老挝语”

### ISSUE THREAD

**Issue by CalaW** [ripperhe/Bob#378]
## 运行环境
* Device: MacBook Pro（14英寸，2021年）
* macOS: 12.5 21G72 arm64
* Bob Version: 1.1.0[60]

## 描述问题
语言选取栏中拉丁语“Latin”的中文标成了“老挝语”

<img width="343" alt="截屏2022-08-14 21 40 25" src="https://user-images.githubusercontent.com/41041381/184540046-00be55bf-6df8-4895-b1d8-6db8f9fd2860.png">

另外是否考虑在语言选取栏中对语言进行排序？目前翻找语言还是比较麻烦

**Comment by ripperhe** [comment]
🤝 感谢反馈！
Latin 的问题会在下个版本修复。
后续也会考虑下如何让语言更好找一些。

**Comment by ripperhe** [comment]
已在 1.2.0 版本修复
