### ISSUE TITLE
希望添加语言切换的快捷键

### ISSUE THREAD

**Issue by skitta** [ripperhe/Bob#379]
希望可以添加语言切换的快捷键，比如：中文->英文，按下Tab键后可以转换成 英文->中文。

**Comment by ripperhe** [comment]
你好，如果你仅仅是用在，「中文->英文」 或者 「英文->中文」的话，可以两个都选成自动。
也就是，「自动检测 -> 自动选择」，识别到中文会自动翻译成英文，反之则会自动翻译成中文。
