### ISSUE TITLE
软件启动后快捷键失效

### ISSUE THREAD

**Issue by travelerly** [ripperhe/Bob#38]
软件启动后，快捷键不能立即使用，需要先点开设置，然后关掉之后几秒钟才能使用快捷键。

**Comment by ripperhe** [comment]
@travelerly 
请问是什么机型，什么系统版本，什么软件版本？
问题是必现的吗？
划词翻译、截图翻译、输入翻译的快捷键都用不了吗？
为何你不填模板也能直接提issue 😳

**Comment by travelerly** [comment]
> @travelerly
> 请问是什么机型，什么系统版本，什么软件版本？
> 问题是必现的吗？
> 划词翻译、截图翻译、输入翻译的快捷键都用不了吗？
> 为何你不填模板也能直接提issue 😳

我的两台设备都会出现这个问题，MacBook pro和imac，系统都是10.15.3，Bob版本都是0.3.0的，只要是每次重启系统都会出现这个问题，需要带这个软件的通用设置再关闭，几秒钟后快捷键才能用。

你说的这个提issue的模板是什么模板？

**Comment by ripperhe** [comment]
麻烦升级 0.7.0 试试吧
