### ISSUE TITLE
Popclip 导致 Jetbrains 家的 IDE 按键粘连

### ISSUE THREAD

**Issue by TDZhengYan** [ripperhe/Bob#380]
https://v2ex.com/t/872347#reply23
设置起来也很麻烦，看能不能弃用Popclip

**Comment by ripperhe** [comment]
你好，弃用是指什么呀？

**Comment by TDZhengYan** [comment]
换个不会造成idea冲突的插件。而且popclip好像有其他bug。

**Comment by ripperhe** [comment]
请问有什么其他推荐的软件的吗？
碍于实现原理，macOS 的划词取词真的很难做到完美，或多或少都会影响到剪切板以及一些其他功能，据我所知，PopClip 可能是目前做得最好的了。
