### ISSUE TITLE
截图翻译时，空格键可以拖动截图区域

### ISSUE THREAD

**Issue by liyuhang1996625** [ripperhe/Bob#381]
划词的时候的时候，可以借鉴Mac截图，空格键可以拖动划词区域～，这样体验会更好一些～

**Comment by ripperhe** [comment]
你好，感谢反馈。不过没太明白，到底指的是「划词翻译」还是「截图翻译」？

**Comment by liyuhang1996625** [comment]
抱歉没有描述清楚～我上面描述指的是「截图翻译」功能，

https://user-images.githubusercontent.com/59247255/184598694-5a2e35e6-7887-49c6-b9b4-deef6e3f889f.mp4

**Comment by ripperhe** [comment]
了解了，我后面研究一下
