### ISSUE TITLE
Bob 官网证书过期

### ISSUE THREAD

**Issue by char8x** [ripperhe/Bob#383]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Mid 2014)
* macOS:  11.6.8
* Bob Version:  1.1.0

## 描述问题
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/6831013/186557609-37e9969a-d7fa-453b-876b-190ad0017001.png">
<img width="484" alt="image" src="https://user-images.githubusercontent.com/6831013/186557668-dfb25de7-9e25-42b2-9e42-448cc802a000.png">

**Comment by ripperhe** [comment]
感谢提醒，已恢复
