### ISSUE TITLE
macOS 13.0 beta7 下自带中文输入法无法显示候选框

### ISSUE THREAD

**Issue by aifengos** [ripperhe/Bob#384]
## 运行环境
* Device: MacBook Pro, 16-inch, 2021
* macOS: Version 13.0 Beta (22A5331f)
* Bob Version: 1.1.0 [60] Pro版

## 描述问题
自带中文输入法无法出现候选词，其他app正常，重启系统没有解决

<img width="405" alt="bob_no_input_candidate" src="https://user-images.githubusercontent.com/111405504/186849193-621a9f68-0937-4109-bb66-786cfcdc26b6.png">

**Comment by YPJCoding** [comment]
13.0 Beta (22A5352e) 已经可以了

**Comment by ripperhe** [comment]
@aifengos 如楼上所说，建议试试最新版还有问题没

**Comment by aifengos** [comment]
@ripperhe 我更新到最新版的beta(22A5352e)，暂时还是不行

**Comment by ripperhe** [comment]
@aifengos OK，有试过其他输入法吗？我周末看看能否复现

**Comment by HaodongZou** [comment]
这应该是Ventura系统bug，我在Spotlight或者Raycast中经常也遇到这个问题。刚才试了一下Bob没有这个问题，系统版本beta(22A5352e)。
可以尝试一下在活动监视器中强制退出“简体中文输入方式”，有可能会解决这个问题。

**Comment by aifengos** [comment]
> @aifengos OK，有试过其他输入法吗？我周末看看能否复现

今天更新到beta (22A5358e) 问题消失了🫠多谢开发者和楼上各位的热心互动和帮助
