### ISSUE TITLE
法语OCR识别会忽略法语音符和分隔符

### ISSUE THREAD

**Issue by maomaosiyuLsc** [ripperhe/Bob#385]
运行环境
* Device: MacBook Pro（14英寸，2021年）
* macOS: 12.5.1
* Bob Version: 1.1.0[60]

## 描述问题

**OCR识别（翻译+独立OCR）时会忽略法语音符和分隔符，见附图。**
![SCR-20220826-ngq](https://user-images.githubusercontent.com/58966970/186944884-66a259ff-e83b-471d-bca9-fbf6546775e1.png)

**Comment by ripperhe** [comment]
好的，感谢反馈，法语音符我后面看下能否识别，分隔符指的是什么？

**Comment by maomaosiyuLsc** [comment]
分隔符就是省文撇，写作'，占据一个字母的位置。如上图中的l'Accord就被识别为了lAccord，其实严格讲也算是法语音符的一部分。补充信息：我使用的内置的OCR

**Comment by ripperhe** [comment]
好的，明白了，请问识别成这个效果是正确的吗？

![Xnip2022-08-30_00-33-11](https://user-images.githubusercontent.com/13943595/187336713-c49b90a1-64cb-4acd-8de6-041b98493dcb.jpg)

**Comment by ripperhe** [comment]
嗯嗯，图片会影响识别效果的，用你的原图效果会好一些。
<img width="834" alt="image" src="https://user-images.githubusercontent.com/13943595/188320412-918de145-cc90-4d2d-befc-5b20971ede33.png">

**Comment by maomaosiyuLsc** [comment]
这次识别基本正确了。

**Comment by ripperhe** [comment]
好的，跟随下个版本上线。
