### ISSUE TITLE
请问一下已经在偏好设置更改OCR插件，但实际操作起来还是旧的那一个怎么处理？

### ISSUE THREAD

**Issue by silverymoonnn** [ripperhe/Bob#386]
## 运行环境
* Device:  MacBook Air (Retina, 13-inch, 2019)
* macOS:  macOS Monterey 12.3.1
* Bob Version:  1.1.0 [60]

## 描述问题

先感谢开发者！！！使用BOB两年了一直都很好TT

已经下载了apple store版本的BOB了！使用的时候貌似出现了BUG，之前设置过的腾讯云通用OCR，因为失效了所以在设置换回了百度OCR，也已经通过验证、保存了设置；再次打开显示我选择的也都是百度OCR。不过在实际使用的时候还是显示不可用的腾讯云OCR，请问怎么处理呢？

PS百度翻译我也使用了，没有问题！就是OCR疑似有BUG...TT 感谢你们！！

<img width="398" alt="Screenshot 2022-08-27 at 10 04 33" src="https://user-images.githubusercontent.com/112224383/187010043-0db1f105-a4b5-4da5-b89b-733c2a731220.png">
<img width="729" alt="Screenshot 2022-08-27 at 10 06 51" src="https://user-images.githubusercontent.com/112224383/187010058-1bf393e5-097a-45d6-a712-593b9ff926c0.png">

**Comment by ripperhe** [comment]
你好，为了分割开「翻译功能」和「OCR 功能」，两者的服务的完全分开的。
看起来，你设置的是「OCR 功能」的服务，但是使用的是「翻译功能」的截图翻译，所以达不到预期的效果。

翻译功能相关的服务在这里设置，你应该改这里
![Xnip2022-08-27_11-04-46](https://user-images.githubusercontent.com/13943595/187011982-ff8c22e5-dcae-46e2-8530-3e67f00774de.jpg)

OCR 功能相关的服务在这里设置，对应的是独立的 OCR 窗口，单纯使用 OCR 的场景
![Xnip2022-08-27_11-04-30](https://user-images.githubusercontent.com/13943595/187012003-eab959fa-8e77-4028-9ae1-c68cfa8217fb.jpg)

**Comment by silverymoonnn** [comment]
喔！！原来是这样，谢谢你的耐心解答TT 辛苦了！学生党感到很感激TT

**Comment by ripperhe** [comment]
哈哈哈，好的，不客气 🤝
