### ISSUE TITLE
使用代理的时候翻译会失效

### ISSUE THREAD

**Issue by a11enyang** [ripperhe/Bob#39]
使用代理的时候，图片文本识别会失效，划词翻译功能也会失效

**Comment by ripperhe** [comment]
@a11enyang 这个确实会无法使用，建议使用 PAC 模式，不要使用全局模式。

**Comment by ripperhe** [comment]
请升级 0.5.2 版本

**Comment by zz5678** [comment]
> 请升级 0.5.2 版本，可以在全局翻墙的情况下使用

就不新开 issues 了，希望作者增加 proxy 功能，由于国内网络情况复杂 …… 一来保证灵活性，二可以降低隐私泄漏风险

**Comment by vvanglro** [comment]
有增加proxy功能的计划吗？
希望$http可以增加proxy参数，这样插件可以使用设置proxy.
