### ISSUE TITLE
自动识别语言不准确

### ISSUE THREAD

**Issue by tisfeng** [ripperhe/Bob#393]
## 运行环境
* Device:  MacBook Pro（16英寸，2021年）
* macOS:  12.6 (21G115)
* Bob Version:  1.2.0

## 描述问题

例如输入文本： `Bob 是一款 macOS 平台翻译和 OCR 软件`，被识别成了 `西班牙语`，没有出现期望的翻译结果。（当然我知道可以手动指定输入语言😓）

<img width="516" alt="image" src="https://user-images.githubusercontent.com/25194972/191695471-2b4d2624-e331-4f7c-847d-453c5a8a9505.png">

## 期望

希望能自动识别输入文本为 `中文`，然后正确翻译为 `英语`。

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/191697863-8d725a46-7993-46c1-b3cc-a3c77c4f8dc4.png">

**Comment by ripperhe** [comment]
感谢反馈，这个用的系统内置的语言识别模型，目前没有解决方案

**Comment by tisfeng** [comment]
可以的，既然都支持了腾讯、百度翻译 API，那就顺便支持一下对应的语种识别呗，反正都是使用用户自己的 API key。

就我有限的测试用例来说，这些 API 的识别准确度都还不错，尤其是百度的（非语种识别API，而是翻译使用 auto），比系统强太多了。

**Comment by ripperhe** [comment]
> 

嗯嗯，会考虑下，之前觉得不是很有必要就没加。

**Comment by ripperhe** [comment]
> 

厉害了，Bob 表示瑟瑟发抖，竞品 +1 😂
