### ISSUE TITLE
希望开发查询历史记录功能或是收藏功能

### ISSUE THREAD

**Issue by jiaoguoqiang** [ripperhe/Bob#40]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 请描述你的建议

非常喜欢Bob翻译软件，小巧功能强大，特别是截图翻译，功能第一了，
希望尽快开发查询历史记录功能呀或是收藏功能，跟查询记录导出功能，这个功能太重要啦。

**Comment by ripperhe** [comment]
好勒，感谢支持 🙏

**Comment by ripperhe** [comment]
已添加历史记录和收藏夹功能
