### ISSUE TITLE
谷歌翻译目前无法使用

### ISSUE THREAD

**Issue by li-Coulson** [ripperhe/Bob#402]
## 运行环境
* Device: MacBook Pro（M1 Pro）
* macOS: 12.6
* Bob Version: 1.2.0

## 描述问题
[打扰作者了，目前Pro版在使用谷歌翻译时，显示“插件未返回有效结果”，这个目前是因为谷歌翻译关闭了国内的网页访问，不过国内服务器还在，修改hosts之后，调用接口应该是没啥问题的，这个方法(https://blog.csdn.net/qq_44336875/article/details/127154776)，我在谷歌浏览器的翻译插件里已经验证通过了，浏览器插件可以使用，所以咱这个软件是不是需要更新国内的ip调用呢

**Comment by NiceNicks** [comment]
我也遇到了同样问题，反而第三方插件有选择国外接口的还可以用
<img width="383" alt="image" src="https://user-images.githubusercontent.com/14955364/194794237-1ed7299d-7ec8-4606-bf44-e411d27b032a.png">

**Comment by ripperhe** [comment]
Bob 内填秘钥 Google 翻译服务调用的是 Google 官方 API，域名是 `translation.googleapis.com`。

Bob 的 Google 翻译插件（com.roojay.bobplugin-google-translate）里面调用的应该是网页 API，使用的域名是 `translate.google.com` 或者 `translate.google.cn`。

`translation.googleapis.com` 和 `translate.google.com` 目前需要科学上网才能访问。
`translate.google.cn` 由于近期 Google 翻译退出中国，应该是已经废弃了，不能用了。

这篇文章 https://blog.csdn.net/qq_44336875/article/details/127154776 看起来是针对 `translate.google.com` 这个域名改 host，改完之后，理论上 Google 翻译插件（com.roojay.bobplugin-google-translate）在偏好设置改成国际版就可用了。

**Comment by NiceNicks** [comment]
我看谷歌云的文档里面用的是translate.google.com这个AIP了，会不会现在都统一用这个接口了
[translation.googleapis.com](https://cloud.google.com/translate/docs/reference/rest/?apix=true)

**Comment by yanghuohua** [comment]
我也遇到这个情况使用后显示{插件未返回有效结果},请问是怎么解决的

**Comment by ripperhe** [comment]
@yanghuohua 就是将 Google 翻译插件的偏好设置里面的接口版本改为.com，然后改一下 host 或者开启科学上网就行

**Comment by vvanglro** [comment]
改hosts已经失效了 服务已经404了
走科学上网吧

**Comment by ripperhe** [comment]
@roojay520 已经把 Google 翻译插件更新了 🎉，如果用的是 Google 翻译插件，就把插件更新到最新版，然后开启**科学上网**就行了。
如果用得是 Bob 内部集成的 Google 翻译，也是开启**科学上网**就行了。
