### ISSUE TITLE
建议增加腾讯交互翻译

### ISSUE THREAD

**Issue by coppea** [ripperhe/Bob#403]
官网：https://transmart.qq.com/zh-CN/index   支持token

**Comment by ripperhe** [comment]
你好，这个有接口文档吗？貌似没看到

**Comment by coppea** [comment]
> 你好，这个有接口文档吗？貌似没看到
跟官方要的，10分钟后删掉
http://2z8.cn/05E66

**Comment by ripperhe** [comment]
好的，感谢

**Comment by ripperhe** [comment]
请问下这个想比较于腾讯翻译的优势是什么？

**Comment by coppea** [comment]
强调交互式翻译，平常使用确实对比不大
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-3257f525-2b37-4abd-a1a8-0ced2610966e/ace15796-8be1-4c11-adbe-1f06f9f65019.mp4](url)

**Comment by ripperhe** [comment]
感谢，大致明白了。
这样看来的话，如果要想发挥这个交互翻译的作用，不仅仅是需要加一个翻译服务，而是要改变 Bob 现有的交互模式，重新去设计。
目前不会加了，如果有相关需求，可以直接使用腾讯交互翻译的这个网页。

**Comment by coppea** [comment]
交互式只是为了翻译更准确，除去这个，如翻译字符不限量，这都是优点；api也非常简单，只需要提供userid和token就可以了 

不内置服务的话，以Bob插件来开发也是可以的

**Comment by ripperhe** [comment]
恩恩，是的。
不过我看他没有直接在公开 API 文档和计费模式，感觉应该是属于初期测试阶段，不太确定是否稳定。确实可以尝试用插件的模式玩一玩。
