### ISSUE TITLE
Hotkey 弹出主窗口较慢

### ISSUE THREAD

**Issue by kaz10025** [ripperhe/Bob#404]
## 运行环境
* Device: 2021MBP 16”
* macOS: 13.0 Beta版(22A5373b)
* Bob Version: 1.2.0 [69]

**Comment by ripperhe** [comment]
你好，请详细描述下用什么快捷键触发的？希望能帮忙录个视频，把手指按键和电脑屏幕同时录一下。

**Comment by kaz10025** [comment]
划词翻译快捷键 我更改为option+D 
在Chrome浏览器（106.0.5249.119）中会比其他应用外稍慢

**Comment by ripperhe** [comment]
划词翻译快捷键默认就是option+D，能否录个视频，想看下大概的效果。
另外参考这个 https://bobtranslate.com/faq/export-log.html，导出一下日志，发送到 bobtranslate@qq.com。

**Comment by kaz10025** [comment]
已发送

**Comment by ripperhe** [comment]
你好，我看到了你的操作。划词翻译，是选中文本，再按快捷键。
不选文本，确实会慢，因为没取到词，会有等待的过程。
这种情况建议你用 option + a

**Comment by kaz10025** [comment]
好的了解~  不过Chrome中确实会稍慢些（有点钻牛角尖哈哈）

**Comment by ripperhe** [comment]
「不过Chrome中确实会稍慢些」
因为针对部分 app 等待时间不同，你改这个设置之后应该都会比较快，不过可能有些软件取词不见得能取成功
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/13943595/195757934-c6ec551f-f040-444e-a748-3286f11e9ebd.png">
