### ISSUE TITLE
内置翻译服务今天一直提示: 频率过快，请稍后再试

### ISSUE THREAD

**Issue by nulllpoint** [ripperhe/Bob#411]
## 运行环境
* Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* macOS: 12.6 (21G115)
* Bob Version: 0.10.3

## 描述问题
使用系统内置翻译服务, 一直提示频率过快，请稍后再试,
没有代理软件, 昨天用还正常, 今天中午开始就这样, , 退出第一次翻译就一直加载, 再次翻译就频率过快
0.10.3也更新了, 问题依旧
![Xnip2022-11-01_13-43-16](https://user-images.githubusercontent.com/42410451/199166981-4e661a6a-7068-4a3a-8a34-7c09fa4ccf0c.jpg)

![Xnip2022-11-01_13-41-51](https://user-images.githubusercontent.com/42410451/199166760-c3d75f47-67c4-4c91-a6ea-32f3b22e92af.jpg)

**Comment by ripperhe** [comment]
@nulllpoint 你好，感谢反馈。
当遇到这种情况，往往是系统翻译出问题了，没有个 Bob 正常的回调，解决方案就是重启电脑。

**Comment by nulllpoint** [comment]
> @nulllpoint 你好，感谢反馈。 当遇到这种情况，往往是系统翻译出问题了，没有个 Bob 正常的回调，解决方案就是重启电脑。

真的是, 系统翻译抽风了, 重启完恢复, 感谢您的解答

**Comment by ripperhe** [comment]
另外，加了一篇 faq，方便后来的人看 https://bobtranslate.com/faq/apple-translate-error.html

**Comment by nulllpoint** [comment]
> 另外，加了一篇 faq，方便后来的人看 https://bobtranslate.com/faq/apple-translate-error.html

好的,十分感谢您, 
我刚发现'translationd' 这个进程, kill掉以后再次调用翻译它就会启动, 这样不用重启电脑, 
毕竟工作的时候开几十个应用和网页, 重启一次太伤了hahh

**Comment by ripperhe** [comment]
感谢提醒，感觉你的方案更好，我回头让其他用户测试下

**Comment by wangrongding** [comment]
> translationd

translationd是系统进程吗？还是 Bob 的子进程？

**Comment by nulllpoint** [comment]
> > translationd
> 
> translationd是系统进程吗？还是 Bob 的子进程？

苹果的系统进程, 可以在活动监视器里看到进程打的文件, 里面有'com.apple.translationd'

**Comment by ripperhe** [comment]
> > translationd
> 
> 
> 
> translationd是系统进程吗？还是 Bob 的子进程？

系统进程

**Comment by nulllpoint** [comment]
> @nulllpoint 你好，感谢反馈。 当遇到这种情况，往往是系统翻译出问题了，没有个 Bob 正常的回调，解决方案就是重启电脑。

我发现了一个百分百触发这个问题的场景, 
上次出现这种问题好像是因为我的edge浏览器开了几十个页面,最终出现故障, 导致我的mbp卡死了,
长时间卡死可能会让`WindowServer`这个进程重置, 可能是未响应然后被强制干掉然后再唤起,
昨天因为跑一个项目又卡死了, 突然想到会不会导致内置翻译又不行了, 试了下, 果然.
所以现在有个一定能触发的方法: 
- 手动kill掉`WindowServer`
- 电脑会像用户注销登录的过程一样
- 此时再次调用bob翻译, 第一次会一直加载结果, 下一次就是`频率过快,稍后重试`

而且干掉`translationd` 和 `快捷指令` 重新唤起也不能恢复内置翻译服务的正常调用,
但是苹果自己的右键菜单翻译就没有影响,很奇怪, 
目前大概只能通过重启系统才能解决了,
我有什么地方能帮助解决这个问题么, 或者bob有没有调试日志什么的.

**Comment by ripperhe** [comment]
@nulllpoint 感谢反馈。

确实，我也发现系统的右键菜单翻译和 Bob 调用快捷指令的表现是有些不一样的，他们底层逻辑肯定是有一些不一样的。我之前在 macOS 12 的时候做过一些测试，当系统翻译开启 `设备端模式` 的时候（也就是离线翻译），系统的右键菜单可以翻译比较长的句子，但是系统快捷指令只能翻译较短的句子，长了就会报错，从这一点也可以看出来他们之间肯定是有些不同的。不是 Bob 引起了不同，是快捷指令和系统右键翻译本身就不同。

Bob 这边其实没有什么复杂逻辑，就是单纯调用快捷指令的命令行软件，Bob 界面一直加载或者频率过快，其实都是快捷指令的命令行软件没有给回调，Bob 一直在等待。**卡住，一定是快捷指令本身的问题。**

目前确实没有什么调试日志可以分析的，你可以理解为，我这里就是简单调用，调用了，然后没有然后了...

我后面再看看有没有什么方法可以规避掉快捷指令的这个问题。比如发现长时间卡住的时候，主动 `terminate` 这次调用试试。

**Comment by nulllpoint** [comment]
> @nulllpoint 感谢反馈。
> 
> 确实，我也发现系统的右键菜单翻译和 Bob 调用快捷指令的表现是有些不一样的，他们底层逻辑肯定是有一些不一样的。我之前在 macOS 12 的时候做过一些测试，当系统翻译开启 `设备端模式` 的时候（也就是离线翻译），系统的右键菜单可以翻译比较长的句子，但是系统快捷指令只能翻译较短的句子，长了就会报错，从这一点也可以看出来他们之间肯定是有些不同的。不是 Bob 引起了不同，是快捷指令和系统右键翻译本身就不同。
> 
> Bob 这边其实没有什么复杂逻辑，就是单纯调用快捷指令的命令行软件，Bob 界面一直加载或者频率过快，其实都是快捷指令的命令行软件没有给回调，Bob 一直在等待。**卡住，一定是快捷指令本身的问题。**
> 
> 目前确实没有什么调试日志可以分析的，你可以理解为，我这里就是简单调用，调用了，然后没有然后了...
> 
> 我后面再看看有没有什么方法可以规避掉快捷指令的这个问题。比如发现长时间卡住的时候，主动 `terminate` 这次调用试试。

是的, 我继续调试了一圈, 定位到就是快捷指令的问题, 
我创建了个特别简单的翻译过程
![Xnip2022-11-30_10-40-45](https://user-images.githubusercontent.com/42410451/204694679-fdc85a05-0172-46c5-bce3-9733552dc4a7.jpg)
本来正常情况下, 输入输出都没问题, 
如果设置了弹窗输入, 也可以正常弹窗提示输入必要的文本,
但是在卡死重置或干掉`WindowServer`重新唤起后, 快捷指令就没响应了, 
点击执行, 但是什么响应都没有, 既没有输出, 也没有结束.
破案了
