### ISSUE TITLE
Google 翻译

### ISSUE THREAD

**Issue by KM197310** [ripperhe/Bob#413]
由於現在 Bob 都無法使用內建的本文翻譯, 所以申請私人秘钥 for Google 翻译,
按照 Bob 提供的設定方式進行, 因為是第一次申請, 請問如何知道自己申請的  Cloud Translation  API,
是基本版 (v2) 還是高级版 ?  另外設定完後, 除了 Bob 網站裡面說明的每個月翻譯的字數限制與超出的費用外,
在 google cloud 只有申請這個 Cloud Translation  API for Bob 文本翻譯這個功能而已, 還會有其他費用產生嗎 ???

* 因為準備考認證, 需要閱讀大量英文文件, 很擔心不知道還有什麼費用產生 *

謝謝

**Comment by ripperhe** [comment]
你好，Bob 内目前使用的是基本版 (v2)，如果你不超出免费额度，是不会扣费的。

只要你没有在 Google 后台误操作，开通了什么其他的奇奇怪怪的东西，其他也没有额外的费用。理论上严格跟着教程走的，都不会引起其他的额外的费用。
