### ISSUE TITLE
必现闪退

### ISSUE THREAD

**Issue by kaz10025** [ripperhe/Bob#414]
## 运行环境
* Device: MacBook Pro（16-inch，2021）
* macOS: 12.6.1 (21G217)
* Bob Version: 1.2.0[69]

## 描述问题
https://github.com/ripperhe/Bob/issues/411
在此基础上点击刷新按钮就会闪退

**Comment by ripperhe** [comment]
感谢反馈，下个版本会修复

**Comment by ripperhe** [comment]
@kaz10025 麻烦升级下 1.3 版本，该问题已修复

**Comment by kaz10025** [comment]
> @kaz10025 麻烦升级下 1.3 版本，该问题已修复




> @kaz10025 麻烦升级下 1.3 版本，该问题已修复

已更新～后续再观察一下
