### ISSUE TITLE
腾讯云OCR 英文文档翻译后还是英文

### ISSUE THREAD

**Issue by yanghuohua** [ripperhe/Bob#419]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/60812221/201620740-2ca8d30e-5478-4bcf-8b43-1c2dd54c4879.png">
如图,这个是腾讯云问题的还是bob问题

**Comment by ripperhe** [comment]
@yanghuohua 你好，Bob 有翻译功能和 OCR 功能两个功能模块，你使用的是 OCR 功能，只会 OCR，所以不能翻译。

你想翻译图片的话，请使用翻译功能里面的「截图翻译」。

<img width="263" alt="image" src="https://user-images.githubusercontent.com/13943595/201622703-de97eeb8-109e-4f08-a04e-aa939e956562.png">

另外，我建议先简单看下 Bob 的文档，学习下如何使用。

翻译功能文档：
https://bobtranslate.com/guide/quickstart/translate.html

OCR 功能文档：
https://bobtranslate.com/guide/quickstart/ocr.html
