### ISSUE TITLE
在 Bob 的 OCR 窗口的文本框中划词翻译，「划词翻译没有获取到文本 」

### ISSUE THREAD

**Issue by Martian746** [ripperhe/Bob#422]
## 运行环境
* Device:  Mac mini 2018
* macOS:  Ventura 13.0.1 (22A400)
* Bob Version:  1.3.0 [83]

## 描述问题
复现步骤：
1. 截图 OCR。
2. OCR 窗口：在文本框中选择部分文字，用快捷键调用划词翻译功能
3. 翻译窗口：「划词翻译没有获取到文本」

不知是否是我用 Karabiner-Elements 改过键的缘故，导致 Bob 无法通过 `⌘ + C` 复制？
* 对调了 `⌘` 与 `⌃`。改键前，Windows 键盘的 `Control + C`，`Win + C` 在 macOS 中分别是 `⌃ + C`，`⌘ + C`；改键后分别是 `⌘ + C`，`⌃ + C`。
* 在 Bob 的 OCR 窗口，手动 `⌘ + C`（按 Windows 键盘的 `Control + C`）是可以正常复制的。

**Comment by ripperhe** [comment]
碍于沙盒 App 的问题，确实无法解决划词问题。
不过 1.4.0 版本在 OCR 窗口加了「翻译」按钮，点击之后会跳转到翻译窗口，也算是解决了吧，先这样啦 🤝
