### ISSUE TITLE
建议增加对驼峰式词语的解析

### ISSUE THREAD

**Issue by plain-dev** [ripperhe/Bob#43]
比如 `setPeekHeight` 在翻译时拆分成 `set peek height`

**Comment by ripperhe** [comment]
@plain-dev 

恩，我也考虑过这个，不过想到一整个句子中可能有些并不需要拆分，这样拆分或许会引起一些其他问题。

是否可以检测到只选中了单个词语，并且这个词语是驼峰的形式，就将其拆分翻译；如果是在整句中有部分驼峰则忽略。你觉得这样可行吗？

**Comment by plain-dev** [comment]
@ripperhe 不知道你手头有没有idea相关的软件，里面有一个插件[TranslationPlugin](https://github.com/YiiGuxing/TranslationPlugin)对驼峰式词语的解析挺不错的，你可以体验下😂

**Comment by ripperhe** [comment]
@plain-dev 好的，回头参考一下。👍

**Comment by ripperhe** [comment]
0.5.2 版本已添加这个功能，支持驼峰拆分，也支持蛇形拆分。
