### ISSUE TITLE
腾讯语音合成是不是无法使用了

### ISSUE THREAD

**Issue by Doutianbao** [ripperhe/Bob#440]
之前使用没问题，今天看无法使用了。
重新创建子用户，使用心得API还是不可以。
同样的API，翻译可以使用

## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
请问充钱了吗，我记得腾讯语音合成是需要付费的。

**Comment by ripperhe** [comment]
不是一直有的，只有刚开始有

**Comment by Doutianbao** [comment]
尴尬~
