### ISSUE TITLE
建议支持代码注释的翻译

### ISSUE THREAD

**Issue by edsion1107** [ripperhe/Bob#445]
能否翻译的时候识别一下是否是注释，把注释用的 `*`,`#`,`/*`等等去掉再翻译？
因为注释，尤其是多行注释都是相对规范的格式，行首的符号会导致翻译引擎断句错误。

ps：要是能推测注释的类型，如javadoc或python的docstring，再通过类似hightlight.js渲染一下，显示效果可能更棒。

**Comment by chinaboard** [comment]
这种情况可以考虑使用ocr翻译变通一下

**Comment by edsion1107** [comment]
带注释的多行文本翻译的效果有明显提升。
