### ISSUE TITLE
非常好用的软件，强于欧陆OCR翻译，强烈建议增加搜狗翻译，长句准确率很大程度上高于谷歌翻译。

### ISSUE THREAD

**Issue by Rexlambert** [ripperhe/Bob#45]
如题，经常使用翻译，经过我的对比，搜狗目前的长句短句翻译水准普遍高于谷歌翻译，非常符合中国人的语言习惯，甚至连诗句都能翻的有模有样，谷歌就不行。

**Comment by ripperhe** [comment]
@Rexlambert 
恩，正在加。不过最近确实比较忙，空闲时间不多。代码写了一部分，还没写完。

**Comment by octoer** [comment]
> 如题，经常使用翻译，经过我的对比，搜狗目前的长句短句翻译水准普遍高于谷歌翻译，非常符合中国人的语言习惯，甚至连诗句都能翻的有模有样，谷歌就不行。

说起来谷歌的中文翻译真是每况愈下，准确度已经不如百度和有道了

**Comment by sounpeng** [comment]
什么时候能加好，谢谢！

**Comment by Rexlambert** [comment]
> @Rexlambert
> 恩，正在加。不过最近确实比较忙，空闲时间不多。代码写了一部分，还没写完。

感谢你的付出，之前尝试过收费软件iText，感觉体验并没有Bob优秀，请持续完善，目前已经作为我的助理翻译工具，日后增加付费或者捐赠选项对于我来说都是可以接受的。相信很多人有同样想法。

**Comment by sounpeng** [comment]
多谢 多谢



发件人: Rexlambert <notifications@github.com>
答复: ripperhe/Bob <reply@reply.github.com>
日期: 2020年4月1日 星期三 下午2:51
收件人: ripperhe/Bob <Bob@noreply.github.com>
抄送: 鵬 孫 <sounpeng@Hotmail.com>, Comment <comment@noreply.github.com>
主题: Re: [ripperhe/Bob] 非常好用的软件，强于欧陆OCR翻译，强烈建议增加搜狗翻译，长句准确率很大程度上高于谷歌翻译。 (#45)


@Rexlambert<https://github.com/Rexlambert>
恩，正在加。不过最近确实比较忙，空闲时间不多。代码写了一部分，还没写完。

感谢你的付出，之前尝试过收费软件iText，感觉体验并没有Bob优秀，请持续完善，目前已经作为我的助理翻译工具，日后增加付费或者捐赠选项对于我来说都是可以接受的。相信很多人有同样想法。

**Comment by ripperhe** [comment]
0.5.2 版本已支持，需自行配置秘钥 <https://ripperhe.gitee.io/bob/#/service/translate/sougou>
