### ISSUE TITLE
Homebrew Cask 安装失败

### ISSUE THREAD

**Issue by sfsoul** [ripperhe/Bob#46]
## 运行环境
* Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
* macOS: 10.14.6
* Bob Version: 未成功下载

## 描述问题
使用 Homebrew Cask 安装时报错：请看截图
`brew cask install bob`

![](https://i.loli.net/2020/03/24/guzIBtYiSRGClWd.png)

**Comment by octoer** [comment]
同无法安装，但报错不一样

**Comment by ripperhe** [comment]
@sfsoul 你这个提示找不到 bob，应该是本地的 brew cask 列表很久没更新了，你更新一下试试？

**Comment by ripperhe** [comment]
@octoer 具体是什么错误？

**Comment by sfsoul** [comment]
> @sfsoul 你这个提示找不到 bob，应该是本地的 brew cask 列表很久没更新了，你更新一下试试？

更新了 Homebrew，确实是能下载了，不过上午下载了多次最终都是超时失败。后面还是采用手动安装的方式成功装上了。

**Comment by ripperhe** [comment]
@sfsoul 下载失败可能是因为是从 github 上下载，被墙了吧？

**Comment by sfsoul** [comment]
> @sfsoul 下载失败可能是因为是从 github 上下载，被墙了吧？

我本身电脑翻墙是没问题的，而且打开github速度也很快。试了好几次都是报下面的错，所以也就换种方式下载了。

![](https://i.loli.net/2020/03/25/JO6Rkh7xn5Xcvdu.png)

**Comment by ripperhe** [comment]
@sfsoul 终端fq一般需要单独设置一下，上次也有个人遇到。你如果用的ss，可以看下ss软件的菜单栏的菜单里面应该有终端命令之类的东西，你复制一下，然后在终端执行一下

**Comment by octoer** [comment]
> @sfsoul 终端fq一般需要单独设置一下，上次也有个人遇到。你如果用的ss，可以看下ss软件的菜单栏的菜单里面应该有终端命令之类的东西，你复制一下，然后在终端执行一下

看了下我也是终端没翻墙，解决了，感谢

**Comment by sfsoul** [comment]
> @sfsoul 终端fq一般需要单独设置一下，上次也有个人遇到。你如果用的ss，可以看下ss软件的菜单栏的菜单里面应该有终端命令之类的东西，你复制一下，然后在终端执行一下

谢谢，已解决~
