### ISSUE TITLE
主要觉得logo笑容太吓人了，很诡异，看的难受

### ISSUE THREAD

**Issue by waterhark** [ripperhe/Bob#47]

**Comment by ripperhe** [comment]
1. 很抱歉，logo 让你难受了。。。😥
2. 这是一个菜单栏软件， App 图标可以放到一个小角落里，不用看它
3. 菜单栏的图标可以更换，可以自定义，甚至可以隐藏（在 偏好设置-高级 中设置）

**Comment by Rentu** [comment]
哈哈 同感
