### ISSUE TITLE
换行快捷键建议

### ISSUE THREAD

**Issue by Asura19** [ripperhe/Bob#48]
在Mac上, 当换行和执行操作同时存在时, 通常都是 ⌘ 是执行操作, ⌘ + ↩是换行, 比如微信, telegram啊都是这样, 暂时没有见过Shift + ↩来换行的, 所以这个能否改一下呀

**Comment by ripperhe** [comment]
我个人习惯用 shift + enter 换行，所以一开始就加了。后面可以把 commadn + enter 换行也加上。

不过你说在 Mac 上从来没见过 shift + enter 换行着实让我有点费解，Mac 上的 QQ、微信、钉钉以及 Telegram 都是可以用 shift + enter 换行的。

**Comment by Asura19** [comment]
还真是哈~
