### ISSUE TITLE
翻译服务可以添加chatgpt吗

### ISSUE THREAD

**Issue by RikiZhu** [ripperhe/Bob#486]
类似的浏览器插件*沉浸式翻译*已经可以实现，希望bob也能安排上

**Comment by zhaoge116** [comment]
已经有人开发出了相关的插件，你可以搜一下看看，不过要自己申请Chat的API

**Comment by risezhang** [comment]
如楼上所说，插件已经有喽：https://github.com/yetone/bob-plugin-openai-translator
