### ISSUE TITLE
macOS 10.15.4系统下，划词翻译的结果无法显示（实际是已经有结果）

### ISSUE THREAD

**Issue by TengJG** [ripperhe/Bob#49]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch, Mid 2016)
* macOS: 10.15.4
* Bob Version: 0.4.0

## 描述问题
问题操作示意：
![Kapture 2020-03-27 at 14 42 31](https://user-images.githubusercontent.com/61233044/77729328-52a1be80-7039-11ea-9313-08c6cf470286.gif)

实际能复制出内容：
![image](https://user-images.githubusercontent.com/61233044/77729282-3ef65800-7039-11ea-98db-8c8a12e7704e.png)

**Comment by ripperhe** [comment]
@TengJG 总是出现还是偶然出现？

**Comment by TengJG** [comment]
> @TengJG 总是出现还是偶然出现？

我电脑上自从昨天更新了10.15.4之后，就是这样了

**Comment by TengJG** [comment]
@ripperhe 就是翻译出来的结果不显示，朗读和复制都是正常的

**Comment by ripperhe** [comment]
@TengJG 这就有点尴尬了，相当于完全没法用了哈。我还没升级，今晚上要是有空我看下这个问题，

先加个QQ群？到时候帮忙测试下...

**Comment by TengJG** [comment]
@ripperhe 👌可以的，确实没法用🤣

**Comment by TengJG** [comment]
@ripperhe 老铁，啥时候安排一波10.15.4呢？🤣

**Comment by Tokinx** [comment]
重启了下软件又好了。

**Comment by ripperhe** [comment]
0.5.2 版本已修复
