### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by jihongboo** [ripperhe/Bob#5]
首先真的很感谢作者的工作，做的真棒👍。使用了一段时间，提一点个人的小建议。
1. 能否实现单词和句子使用不同的翻译引擎，比如单词使用有道，句子使用谷歌。因为语句翻译显然Google的要好一点，但单个单词网易的解释会比较详细。
2. 能否接入有道词典的单词本 API
3. 对于语句翻译，其实彩云的翻译 API 的翻译效果可能更好，甚至好于Google。彩云翻译也提供了翻译 API，可以考虑加入。

**Comment by ripperhe** [comment]
感谢支持！🙏
1. 对于单词和句子使用不同的引擎这个功能可以考虑，目前第一步我是准备把翻译引擎和OCR引擎做到可以分开设置，更细化的设置还需要再设计一下
2. 单词本API是用于做什么的？我之前没了解过，能否简单讲一下。。。
我看到有很多人提到翻译历史和收藏单词，这个功能设计好之后，可能在未来某个版本加上。
3. 彩云翻译API下一步准备接入

**Comment by jihongboo** [comment]
刚查了下有道官方的Q&A，有道词典的单词本API没有开放，那只能做一个本地的单词收藏功能了。为作者点赞👍。

**Comment by nb5p** [comment]
我知道扇贝单词本的同步API是开放的，提了一个Issue #37 
不太清楚其他平台有没有类似的API。
有道单词本可以借鉴一下他的实现方式 [TerryX-Lee/AlfredWorkflow_YoudaoTranslate](https://github.com/TerryX-Lee/AlfredWorkflow_YoudaoTranslate)
