### ISSUE TITLE
「OpenAI 翻译」 增加 Azure 支持

### ISSUE THREAD

**Issue by vcarus** [ripperhe/Bob#506]
直接付款 OpenAI 比较繁琐。
建议插件增加 Azure OpenAI 的支持。

感谢。

**Comment by LingweiMeng** [comment]
+1，非常需要  @ripperhe 
附官方相关参考文档：
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-python

**Comment by Guyuue** [comment]
+1，非常需要。openai的付款太难搞了，希望可以支持azure的支持！

**Comment by kaiyo655** [comment]
+1 非常需要, 直接openai比较麻烦, 三方转发又有隐私问题, 如果支持Azure Openai就太好了

**Comment by kaiyo655** [comment]
> 

我可以, 但是没q, 要不你PM个电邮?

**Comment by kaiyo655** [comment]
> > > 
> > 
> > 
> > 我可以, 但是没q, 要不你PM个电邮?
> 
> 🤝🏻 非常感谢，可以发送到 [bobtranslate@qq.com](mailto:bobtranslate@qq.com)

已经发邮件了

**Comment by kaiyo655** [comment]
> @kaiyo655 收到了，非常感谢 🤝

[官方文档](https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions)
[Azure OpenAI Studio代码示例](https://oai.azure.com/portal/chat)

**Comment by kaiyo655** [comment]
希望能早点看到, 另外能不能加入自定义system和user prompts
不同的prompts pratice会对结果产品较大的影响

**Comment by fireinwind** [comment]
这个还是强力支持AOAI的.

**Comment by NiSuooo** [comment]
密钥信息已经发至邮箱。我这边测试连接没有问题，如果请求报错可以发邮件帮忙查看。
