### ISSUE TITLE
建议增加自定义翻译引擎的功能，可以由用户通过翻译引擎的 API 自己添加想用的翻译引擎

### ISSUE THREAD

**Issue by zh0ngtian** [ripperhe/Bob#53]
我看有人提 issue 希望增加搜狗、DeepL 等翻译引擎，我认为还有其他用户有其他翻译引擎的需求，如果可以由有能力的用户使用翻译引擎的 API 自定义翻译引擎，会不会更方便些？

**Comment by Ytinifni-zc** [comment]
附议，现在DeepL的翻译引擎做的相当不错
https://www.deepl.com/

**Comment by pwelyn** [comment]
支持一下 这个功能需要

**Comment by w11235** [comment]
deepl确实不错，希望可以加入

**Comment by ripperhe** [comment]
抱歉，回复晚了。
很好的想法 👍，预计会在下下个版本加上这个自定义的功能

**Comment by ripperhe** [comment]
0.5.x 版本支持自定义插件
