### ISSUE TITLE
希望增加单词联想/补全功能

### ISSUE THREAD

**Issue by Cenbylin** [ripperhe/Bob#536]
有时候隐约记得一个词大概怎么写/前面几个字母，或者只知道发音自己猜。

想请问是否能提供输入提示功能（补全+词性），如下图（同类产品，但远不如Bob好用）：

<img width="236" alt="image" src="https://github.com/ripperhe/Bob/assets/15857382/4c2427b5-5f13-430f-8f28-01f8de3c5a9c">

甚至进一步做联想、同义、易混淆就更好了 :)

**Comment by zydou** [comment]
这个是输入法应该做的事情, 不应该加到翻译软件中. 你可以试试这个开源的英文输入法, 完美解决你的需求. https://github.com/dongyuwei/hallelujahIM

**Comment by Cenbylin** [comment]
> 这个是输入法应该做的事情, 不应该加到翻译软件中. 你可以试试这个开源的英文输入法, 完美解决你的需求. https://github.com/dongyuwei/hallelujahIM

谢谢！
