### ISSUE TITLE
截图翻译时，会直接切换到桌面做圈选

### ISSUE THREAD

**Issue by nootnoo** [ripperhe/Bob#55]
使用截图翻译时，会直接切换到桌面做圈选，无法圈选已经开启的的照片或网站，全屏或视窗都无法。滑词翻译是正常的。是个好程式，谢谢您

## 运行环境
* Device: 
* macOS: 
* Bob Version:

**Comment by ripperhe** [comment]
截图翻译需要「屏幕录制」权限，打开「系统偏好设置-安全性与隐私-隐私-屏幕录制」，然后将 Bob 的勾选框选中即可

**Comment by nootnoo** [comment]
> 截图翻译需要「屏幕录制」权限，打开「系统偏好设置-安全性与隐私-隐私-屏幕录制」，然后将 Bob 的勾选框选中即可

好的了解，非常谢谢您的帮助和回覆，这是个很强大的应用
