### ISSUE TITLE
请加入DeepL支持，这玩意儿的人话程度真的高

### ISSUE THREAD

**Issue by MarcusPierce** [ripperhe/Bob#57]

**Comment by JimmyLv** [comment]
墙裂支持！！

[DEEPL：来自未来的优质翻译器 - 少数派](https://sspai.com/post/59776)

**Comment by Andrewshihs** [comment]
api 价格不便宜啊

**Comment by YuiMashiro** [comment]
搜狗目前也做的不错

**Comment by geekdada** [comment]
楼上各位，插件我写好了 geekdada/bob-plugin-deepl-translate

官方收费高我就做了转发，目前测试期间 2.5 刀 6 万字符，如果有兴趣的话欢迎邮件联系我 me#royli.dev 。

**Comment by ripperhe** [comment]
各位，时隔两年，Bob 最新版也加上 DeepL 了
