### ISSUE TITLE
"翻译结果"快捷键 OPTION-C 修改后不生效。

### ISSUE THREAD

**Issue by lonelygo** [ripperhe/Bob#59]
## 运行环境
* Device:MacBook Pro (Retina, 16-inch, 2019) 
* macOS: 10.15.4
* Bob Version:0.4.0 

## 描述问题

 OPTION-C 与其他工具快捷键冲突，使用“系统偏好设置”-“键盘”-“快捷键”-“APP快捷键”修改为：OPTION-F，如下图：  

![image](https://user-images.githubusercontent.com/8328467/79957548-4e3fb880-84b4-11ea-8ecc-3b3803129bd4.png)  

实际使用中，“翻译结果”的触发快捷键**仍然**为**OPTION-C**，修改后的快捷键并未实际生效。  

疑为APP并未接收到系统对快捷键的修改，请排查，谢谢。

**Comment by ripperhe** [comment]
@lonelygo 
在 Bob「偏好设置-通用」直接将「翻译结果」的快捷键设置为 option + F 不可以么？（疑问句）

**Comment by lonelygo** [comment]
> @lonelygo
> 在Bob“偏好设置-通用”直接将“翻译结果”的快捷键设置为option + F不可以么？（疑问句）

好吧，都没有研究过设置里面有没有，我的锅（手动狗头）
