### ISSUE TITLE
建议加入翻译后按esc键隐藏翻译界面

### ISSUE THREAD

**Issue by KylinChan** [ripperhe/Bob#6]
除了按esc不能隐藏翻译界面之外使用地很舒服，感谢开源，希望可以加入翻译后按esc键隐藏翻译界面。

**Comment by ripperhe** [comment]
在翻译页面可以使用 cmd + w 关闭翻译窗口（不会退出软件）

**Comment by LarenDorr** [comment]
@ripperhe 感觉esc更顺手，只用按一个键（特地来提这个issue，发现有人提了😂

**Comment by ripperhe** [comment]
@KylinChan @LarenDorr 好的，这样的话，那下个版本加上，cmd + w  和 esc 均可关闭翻译页面

**Comment by KylinChan** [comment]
@ripperhe 感谢

**Comment by ripperhe** [comment]
@KylinChan @LarenDorr [0.3.0](https://github.com/ripperhe/Bob/releases/tag/v0.3.0) 版本已支持
