### ISSUE TITLE
软件运行后，没有提示添加权限，屏幕取词失败

### ISSUE THREAD

**Issue by zclpop** [ripperhe/Bob#60]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

软件运行后，没有提示添加权限，屏幕取词失败

**Comment by ripperhe** [comment]
1. 打开 系统偏好设置 > 安全性与隐私 > 隐私 > 屏幕录制，确保勾选上了 Bob
2. 如果「屏幕录制」里没有 Bob，考虑重启电脑再使用一次截图翻译，看设置中「屏幕录制」是否有 Bob
3. 如果还是没有，去终端执行以下代码（将屏幕录制权限重置，这将会导致其他需要屏幕录制权限的软件需要重新授权），然后重启电脑再试试截图翻译，然后再看看设置中是否有Bob...
```
tccutil reset ScreenCapture
```

再不行我也没招了，苹果的权限提示真的有些BUG

**Comment by iMuFeng** [comment]
```
tccutil reset ScreenCapture com.ripperhe.Bob
```
这样不会重置其他 app 的权限
