### ISSUE TITLE
能否出一个linux版的了？

### ISSUE THREAD

**Issue by snmin** [ripperhe/Bob#65]
linux系统下苦于没有截图翻译的软件学习起来很吃力，能否也出一个Linux版的bob了？

**Comment by ripperhe** [comment]
😓抱歉，暂时没精力去开发了...

**Comment by JingxinLee** [comment]
> linux系统下苦于没有截图翻译的软件学习起来很吃力，能否也出一个Linux版的bob了？

Goldendict + OCR
