### ISSUE TITLE
希望加入二维码扫描翻译

### ISSUE THREAD

**Issue by cc978** [ripperhe/Bob#66]
毕竟占了很重要的快捷键和开机自启 😅 成为了重要的日常软件，而截图扫描又是那么的直接功能。
另外，希望不要转化英文点为句号，不要多加空格，方便用来截取 URL 等 raw 数据来使用

**Comment by ripperhe** [comment]
你是说想让截图翻译的时候能识别图中二维码的内容再翻译吗？如果是的话，我感觉这个需求有点小众了，场景不多。

另外图片识别文本是文本识别接口做的处理，如果我再去处理一遍标点或者空格，可能在识别URL等数据的时候效果会好些，但是在更多的情况，接口本身的处理结果是更优的，所以总的来说这样做可能会降低使用体验

**Comment by linmi** [comment]
看起来说的是识别二维码，生成结果。

**Comment by ripperhe** [comment]
@cc978 哈哈哈 虽然很久了，但是还是回复你一下， 0.9.0 的独立 OCR 支持二维码识别了
