### ISSUE TITLE
在网易邮箱大师邮件撰写页面 划词翻译 会崩溃

### ISSUE THREAD

**Issue by HaoshuaiXu** [ripperhe/Bob#67]
## 运行环境
* Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
* macOS:10.15.4 (19E287) 
* Bob Version:0.4.0 

## 描述问题

在“网易邮箱大师”的邮件撰写页面，使用划词翻译，Bob会崩溃

**Comment by ripperhe** [comment]
请升级到 0.7.0 版本再试试
