### ISSUE TITLE
能否可以增加一个即时翻译的开关选项？

### ISSUE THREAD

**Issue by 85Ryan** [ripperhe/Bob#7]
非常好的翻译工具！
谢谢！

一个小建议：

能否可以增加一个 即时翻译 的开关选项？

**Comment by ripperhe** [comment]
及时翻译指的是选中词语就直接翻译吗？

**Comment by ripperhe** [comment]
感谢支持！🤝
请问一下及时翻译指的是选中词语之后直接翻译吗？

**Comment by 85Ryan** [comment]
不好意思，上面没写清楚 🤣

是输入翻译时，现在的模式是输入词语后需要按回车键才翻译，最好能够处理成 输入词语 后即时呈现翻译，不过这样可能会增加回调次数，所以，是否可以增加一个适当的延时，或者在设置选项中增加一个开关选项供自由选择。

当然，现在这样处理也是可以的。

**Comment by 85Ryan** [comment]
另外，还有一个小问题，我不确定是不是这个APP的问题：

在 iBooks 电子书中，选择语句时，划词翻译识别不了语句，选择一个单词时可以识别，截图翻译也可以识别。

**Comment by ripperhe** [comment]
@85Ryan 
1. 好的，及时翻译这个我设计好节流策略之后加上
2. iBooks 识别不了句子这个问题，你选中一串句子，然后 cmd + c 一下，然后到某个地方粘贴一下，看粘贴出来是什么

**Comment by 85Ryan** [comment]
@ripperhe 

谢谢！

iBooks 复制来来会自动添加后缀，应该就是这个原因了！

```
“When the value of a condition is true, we say that this condition is satisfied.”

摘录来自: Unknown. “Table of Contents。” Apple Books. 
```

**Comment by ripperhe** [comment]
@85Ryan 我试用了一下 iBooks，确实会有问题；

我分析了一下是这样的，在 iBooks 选中句子的时候，按下 cmd + c 好像就卡住了，需要等待一会儿才能复制完成（我觉得这是 iBooks 的 Bug），然后 Bob 是模拟发出 cmd + c 指令，然后再 0.1 秒之后去获取剪切板的数据，但是游湖 iBooks 可能还在卡住的状态，还没复制成功，所以这个时候获取到的文本为空

我后面看一下能不能监听剪切板的变化，在模拟发出 cmd + c 指令之后，监听到剪切板变化了再去获取文本进行翻译，也许这样就能解决这个问题

**Comment by 85Ryan** [comment]
@ripperhe  对的，确实是这样的，复制为卡顿一会～

**Comment by 85Ryan** [comment]
@ripperhe 另外，我觉得，如果这个问题仅是 iBooks 的问题，其实没有多大必要针对它单独做优化的，截图翻译能解决问题 😁😁
