### ISSUE TITLE
双屏情况下副屏被激活时，不能调起翻译页面。

### ISSUE THREAD

**Issue by PuddingCoder** [ripperhe/Bob#70]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Early 2015)
* macOS: 10.15.4
* Bob Version:  0.4.0

## 描述问题

窗口位置选择图图标下方，双屏情况下副屏被激活时，不能调起翻译页面。（跟随鼠标时可以调起）

**Comment by ripperhe** [comment]
感谢反馈，下个版本修复。

**Comment by ripperhe** [comment]
请升级 0.5.2 版本
