### ISSUE TITLE
希望百度翻译结果，可以把“记忆技巧”也包含进去

### ISSUE THREAD

**Issue by Yuki-Judai** [ripperhe/Bob#73]
希望百度翻译结果，可以把“记忆技巧”也包含进去。这个数据在网页版翻译结果下面，例如，记忆技巧：combine 结合 + ation 行为 → 结合，联合。有的单词有，有的没有。可以在查词时同时看看词根词缀构词。

**Comment by ripperhe** [comment]
实在抱歉，我现在集成的百度翻译 API 不包含这方面的内容。
