### ISSUE TITLE
翻译 api 失败

### ISSUE THREAD

**Issue by songhao8080** [ripperhe/Bob#74]
翻译 api 失败

## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

![image](https://user-images.githubusercontent.com/10607039/83703602-9ff66980-a642-11ea-80f4-ffd07d30b99d.png)

**Comment by jiujiubad** [comment]
我也出现『请求异常: 翻译失败』，前几天都每天，今晚才出现的异常

**Comment by weiliang903** [comment]
same issue for me.

<img width="302" alt="截屏2020-07-28 19 15 51" src="https://user-images.githubusercontent.com/20644345/88659028-f645cd00-d106-11ea-8da1-bbd12ed334e2.png">

**Comment by ripperhe** [comment]
请升级 0.5.2 版本
