### ISSUE TITLE
请问一下作者有没有win版本计划，太好用了，或者win有没有类似功能软件推荐一下

### ISSUE THREAD

**Issue by forhetale** [ripperhe/Bob#76]

**Comment by ripperhe** [comment]
暂时没有。

Windows 的我不是太清楚，不过听说有人用这个软件，你可以尝试下， 我没试过

https://github.com/CopyTranslator/CopyTranslator

**Comment by tsuyoshi727** [comment]
win的q-translation很好用，翻译接口非常全
