### ISSUE TITLE
无法打开“Bob.app”，因为Apple无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by stfenjobs** [ripperhe/Bob#77]
## 运行环境
* Device:  macbook pro18
* macOS: 10.15.5 
* Bob Version: v0.4.0

## 描述问题

安装后，运行提示 
![image](https://user-images.githubusercontent.com/6580897/85393458-9eec9400-b57f-11ea-9753-bc296b39ec09.png)

提示 此软件需要更新， 请问该咋办呀

**Comment by ripperhe** [comment]
需要开启「允许任何来源」

打开「终端」，输入以下命令，回车，再输入密码，再回车

```
sudo spctl --master-disable
```

**Comment by stfenjobs** [comment]
谢谢
