### ISSUE TITLE
您好，请按照模板填写，谢谢啦 🙏

### ISSUE THREAD

**Issue by Spicy-Spicy** [ripperhe/Bob#79]
## 运行环境
* Device: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
* macOS: 10.15.5 (19F101)
* Bob Version: Bob-master 16.34.16 我也不是很懂这个版本

## 描述问题

是这样的，我下载了过后，是自动解压好的文件夹，然后我将文件夹拖拽到应用程序里面，但是没有出现Bob的应用程序，也无法运行，就只有一个文件夹。重新拖拽以及下载过后，仍然是这样的。请问是什么情况嗯？
<img width="621" alt="截屏2020-06-29 16 42 07" src="https://user-images.githubusercontent.com/67580877/85992441-7b19ca00-ba27-11ea-9698-bcd63fca32d1.png">
这个就是拖拽过后的页面。
谢谢

**Comment by ripperhe** [comment]
你应该是下载到源代码了，应该下载安装包文件。

进入这个网页 <https://github.com/ripperhe/Bob/releases>，点击下图中的位置进行下载

![Xnip2020-06-29_22-51-33](https://user-images.githubusercontent.com/13943595/86021051-3dcf2f80-ba5b-11ea-9c09-325261fa0ad6.png)
