### ISSUE TITLE
打开bob 出现 malicious software 错误信息。

### ISSUE THREAD

**Issue by xiao5612327** [ripperhe/Bob#81]
## 运行环境
* Device: 
* macOS: 
* Bob Version: 

## 描述问题

安装完 bob，打开以后出现这个问题
“Bob” can’t be opened because Apple cannot check it for malicious software.

**Comment by ZionQIAN** [comment]
为了安装可以尝试
暂时性解决方案：是右键点击图标，选择“open”，强制性打开运行软件即可；
也可以在mac操作系统中，选择“allow apps downloaded from: anyway”。

**Comment by ripperhe** [comment]
之前没有对 App 进行公证，所以会有这个问题。0.5.2 已经解决了这个问题，请升级最新版本。
