### ISSUE TITLE
接口异常

### ISSUE THREAD

**Issue by lebonnuit** [ripperhe/Bob#82]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, Early 2015)
* macOS: 10.13.6
* Bob Version: 0.4.0

## 文本识别异常-接口异常

![image](https://user-images.githubusercontent.com/56405349/88270637-83a0b000-cd08-11ea-8b77-49979c9d1d45.png)

**Comment by underthestars-zhy** [comment]
我也遇到了
MacOS：10.11

**Comment by underthestars-zhy** [comment]
重新安装可以解决

**Comment by ripperhe** [comment]
如果还有问题，请升级 0.5.2 版本
