### ISSUE TITLE
百度翻译总是提示请求异常

### ISSUE THREAD

**Issue by tsuyoshi727** [ripperhe/Bob#83]
## 运行环境
* Device: MacBook Pro (Retina, 13-inch, 2019)
* macOS: 10.15.5
* Bob Version: 0.4.0

## 描述问题
百度翻译总是提示”请求异常“，其他的翻译接口都没有出现这个问题，重启或者等待一段时间也都试过了
<img width="304" alt="截屏2020-07-29 下午5 49 07" src="https://user-images.githubusercontent.com/67669424/88786221-d7a60b80-d1c4-11ea-8559-f78edeaf90dd.png">

**Comment by weiliang903** [comment]
已卸载

**Comment by yuhan1010** [comment]
> ## 运行环境
> * Device: MacBook Pro (Retina, 13-inch, 2019)
> * macOS: 10.15.5
> * Bob Version: 0.4.0
> 
> ## 描述问题
> 百度翻译总是提示”请求异常“，其他的翻译接口都没有出现这个问题，重启或者等待一段时间也都试过了
> <img alt="截屏2020-07-29 下午5 49 07" width="304" src="https://user-images.githubusercontent.com/67669424/88786221-d7a60b80-d1c4-11ea-8559-f78edeaf90dd.png">

我也是这样

**Comment by ripperhe** [comment]
请升级 0.5.2 版本
