### ISSUE TITLE
划词翻译每次都需要框选两三遍才可以

### ISSUE THREAD

**Issue by wangyifani** [ripperhe/Bob#85]
## 运行环境
* Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
* macOS: 10.14.6
* Bob Version: e.g. 0.4.0

## 描述问题
每次使用划词翻译，都需要框选还几遍，第一次框选结束没有弹出翻译结果，还是让框选，第二次就 ok 了

**Comment by wwk7225** [comment]
我其实也遇到过类似的，一般是从其他窗口切换回来后的第一次翻译会出问题。
0.5.x版本下还暂时还没遇到这个问题，或许可以升级看看？

**Comment by ripperhe** [comment]
0.5.2 已修复这个问题，如果还有，请在这个 issue @ 我
