### ISSUE TITLE
升级0.5.1后如何显示翻译结果的更多释义

### ISSUE THREAD

**Issue by 85Ryan** [ripperhe/Bob#90]
## 运行环境
* Device: iMac (Retina 5K, 27-inch, 2019)
* macOS: 10.15.7
* Bob Version: 0.5.1

## 描述问题

刚升级到 0.5.1，也申请了 Google Translation API，可以翻译结题却不能像之前版本一样显示单词的更多释义（下图），请问新的版本能否实现呢？

![1601998882215](https://user-images.githubusercontent.com/3353632/95225142-07f5d000-082e-11eb-9c83-79ac87af9fd3.jpg)

谢谢～

**Comment by leon-zhu** [comment]
同遇到这样的问题，希望开发者跟进下~谢谢

**Comment by ripperhe** [comment]
Bob 目前接入的接口没有提供这些字段，达不到这样的效果。

可以考虑使用插件，我试用了下面这个插件，效果跟你图中还是不太一样，不过你可以给他提 issue

<https://github.com/roojay520/bobplugin-google-translate>
