### ISSUE TITLE
Bob 是否可以接入Tencent TranSmart ?

### ISSUE THREAD

**Issue by wongFanx** [ripperhe/Bob#92]
今年的网页翻译一直在使用腾讯的 [Tencent TranSmart](https://transmart.qq.com/index), 相当不错. 
经过多方面对比, 我认为 Tencent TranSmart 在翻译质量上较 google, 百度, 搜狗, 有道等主流翻译有相对明显的效果提升.
不知道Bob是否可以通过内置或者插件支持呢?

**Comment by ripperhe** [comment]
我没有找到 API 文档

**Comment by ripperhe** [comment]
后续有朋友发了文档，看过之后觉得腾讯交互翻译本身主要在于「交互」，需要软件和 API 高度定制才行，和 Bob 不是一套操作逻辑，这里就不准备加了
