### ISSUE TITLE
最新5.x版本添加有道翻译后，无法点击发音。 

### ISSUE THREAD

**Issue by TopScrew** [ripperhe/Bob#93]
## 运行环境
* Device: 
* macOS: 10.15.6
* Bob Version: 5.0.1

## 描述问题
有道字典翻译中，会有英式和美式发音，点击后发音失败。只能使用Apple自带的发音。
![image](https://user-images.githubusercontent.com/35072495/95468224-e1ac6d80-09b0-11eb-9bd9-fbc4ad2c468d.png)

还有个小问题是，以前4版本不是自带有道吗？5版本怎么砍了，还得用私钥登录。已倒车回到4版本

**Comment by ripperhe** [comment]
1. 如果你是按照这个文档（<https://ripperhe.gitee.io/bob/#/service/translate/youdao>）申请的秘钥，应该是可以发音的；如果你现在还想解决这个问题，可以再认真看下文档，如果不用了，请忽略
2. Bob 本身不收费，用的人多了，用自己秘钥是必然的事情，如果不喜欢，可以继续使用老版本或者考虑使用其他软件哈 🤝
