### ISSUE TITLE
feat: v0.51 删除了隐藏菜单栏图标功能，希望能加回来。

### ISSUE THREAD

**Issue by JosephMing** [ripperhe/Bob#94]
* Device: MacBook Pro (Retina, 15-inch, 2019)
* macOS: 10.15.7
* Bob Version: 0.5.1

不知作者基于什么样的考虑，才删除了此功能，希望能加回来。因为此软件已做为我的标准系统扩展，无需在菜单栏常驻。

**Comment by coppea** [comment]
支持，已经集成popclip，所以不需要菜单栏显示

**Comment by FrancisSano** [comment]
> 支持，已经集成popclip，所以不需要菜单栏显示

![image](https://user-images.githubusercontent.com/31059354/95644056-38679380-0ae6-11eb-8262-51eb5685dacd.png)

0.51 release note 明确说了删除，而且我在「偏好设置」中确实没有发现隐藏的设置项。

**Comment by ripperhe** [comment]
@FrancisSano 

删除隐藏主要是考虑到某些情况下显示翻译窗口需要菜单栏图标，另外后续的一些提示会放在菜单栏图标以及弹出的菜单中。

至于是否要加回来，我再考虑考虑。

**Comment by coppea** [comment]
真的，菜单栏图标确实太多了，这个图标点击的频率太低了，建议隐藏或者像其他应用图标设置无

**Comment by banishee** [comment]
big sur的菜单栏图标间隔太大了，希望可以把手动隐藏图标的设置加回来

**Comment by shirenran** [comment]
同意，对于我来说我只需要一个option+D的功能，所以希望可以隐藏掉菜单栏图标

**Comment by AlickH** [comment]
同希望能加回隐藏功能，我可以用popclip翻译选中单词，用alfred翻译输入的单词，根本用不上菜单栏图标

**Comment by Cavolo** [comment]
希望能加回隐藏菜单栏图标功能，有快捷键和popclip集成了。

**Comment by SuperMotor** [comment]
有快捷键显示“手动翻译”界面了，可以在翻译界面上添加“设置”和“更多”等按钮，这样就和一些剪贴板的软件相似了，这也可以删除菜单栏的图标了

**Comment by Cavolo** [comment]
刘海屏空间更少了，希望添加隐藏选项。

**Comment by ripperhe** [comment]
朋友们，我把它加回来了，升级 0.7.0 吧
