### ISSUE TITLE
求你了 换个图标吧！

### ISSUE THREAD

**Issue by KEVINJ1E** [ripperhe/Bob#95]
求你了 换个图标吧！
求你了 换个图标吧！
求你了 换个图标吧！

**Comment by wwk7225** [comment]
偏好设置》高级》菜单栏图标
其实第三个候选似乎更习惯，也可以“自定义”

**Comment by ripperhe** [comment]
@KEVINJ1E  
1. 菜单栏图标可以按照 @wwk7225 说的方法更换
2. App 图标暂时不会更换，不过你可以自己手动更换，可参考 <https://sspai.com/post/54101>

**Comment by BusyHe** [comment]
哈哈，真的有人会提出这个需求
