### ISSUE TITLE
BUG-不支持该语言

### ISSUE THREAD

**Issue by evi1ox** [ripperhe/Bob#97]
## 运行环境
* Device: MacBook Pro (Retina, 15-inch)
* macOS: 10.15.3
* Bob Version: 0.5.2

## 描述问题
朗读中文|英文提示 `不支持该语言`
![image](https://user-images.githubusercontent.com/24634543/96255044-db3d7780-0fe8-11eb-9a8e-8db2d65e5d77.png)

**Comment by ripperhe** [comment]
已在 0.5.3 修复了这个问题

**Comment by evi1ox** [comment]
![image](https://user-images.githubusercontent.com/24634543/100540961-c60c6780-327b-11eb-837a-7734dd24cda8.png)
0.5.3 bug

**Comment by ripperhe** [comment]
加我 QQ 发我日志 453942056
